﻿<!doctype html>
<html>
<head>
<meta charset='utf-8'/>
<link href='C:\Program Files\MarkdownMate\libs\css\preview\dark.css' rel='stylesheet'></link>
<link href='C:\Program Files\MarkdownMate\libs\css\codeblock\dark.css' rel='stylesheet'></link>
<title>MarkdownMate Preview</title>

<script type='text/javascript' src='C:\Program Files\MarkdownMate\libs\highlight\highlight.pack.js'></script>
<script type='text/javascript' src='C:\Program Files\MarkdownMate\libs\mm\mm_toc.js'></script>
<script type='text/javascript' src='C:\Program Files\MarkdownMate\libs\jquery\jquery-1.11.3.min.js'></script>
<script type='text/x-mathjax-config'>
MathJax.Hub.Config({
    showProcessingMessages: false,
    tex2jax: { inlineMath: [['$','$'],['$$','$$']] },
    TeX: { equationNumbers: {autoNumber: 'AMS'} },
    messageStyle: 'none'
});
</script>
<script>
	var global_style="<style>*{font-family: 'Tahoma', 楷体;} code, pre, code>span, code>span>span, code>span>span>span, code>span>span>span>span{font-family: 'Courier New', 楷体;} </style>";
	document.write( global_style );
</script>
</head>
<body>
<div id='content'>
<h1>SQL基础教程</h1>
<h2>第一章 数据库和SQL</h2>
<h3>1-1 数据库的定义</h3>
<p><strong>DBMS: Database Management System 数据库管理系统</strong><br><strong>DBMS的种类</strong></p>
<ol>
<li>层次行数据库(Hierarchical Database,HDB)<br><strong>最古老的数据库之一,它把数据通过层次结构(木结构)的方式表现出来.层次型数据库曾经是数据库的主流,现在已经很少使用了</strong></li><li><p>关系型数据库(Relational Database,RDB)<br><strong>也称关系数据库,是现在应用最广泛的数据库.关系型数据库1969年诞生,可谓历史悠久.和Excel工作表一样,也采用行列二维表结构来管理数据.同时还使用专门的SQL(Structured Query Language,结构优化查询语言)语言对数据进行操作</strong></p>
<p>  案例:</p>
<table>
<thead>
<tr>
<th>品编号</th>
<th>商品名称</th>
<th>商品分类</th>
<th>销售单价</th>
<th>进货单价</th>
<th>登记日期</th>
</tr>
</thead>
<tbody>
<tr>
<td> 0001</td>
<td>T恤衫</td>
<td>衣服</td>
<td>1000</td>
<td>500</td>
<td>2009-09-20</td>
</tr>
<tr>
<td> 0002</td>
<td>打孔器</td>
<td>办公用品</td>
<td>500</td>
<td>320</td>
<td>2009-09-11</td>
</tr>
<tr>
<td> 0003</td>
<td>运动T恤</td>
<td>衣服</td>
<td>4000</td>
<td>2800</td>
<td>&nbsp;</td>
</tr>
<tr>
<td> 0004</td>
<td>菜刀</td>
<td>厨房用具</td>
<td>3000</td>
<td>2800</td>
<td>2009-09-20</td>
</tr>
<tr>
<td> 0005</td>
<td>高压锅</td>
<td>厨房用具</td>
<td>6800</td>
<td>5000</td>
<td>2009-01-15</td>
</tr>
<tr>
<td> 0006</td>
<td>叉子</td>
<td>厨房用具</td>
<td>500</td>
<td>&nbsp;</td>
<td>2009-09-20</td>
</tr>
<tr>
<td> 0007</td>
<td>擦菜板</td>
<td>厨房用具</td>
<td>880</td>
<td>790</td>
<td>2009-04-28</td>
</tr>
<tr>
<td> 0008</td>
<td>圆珠笔</td>
<td>办公用品</td>
<td>100</td>
<td>&nbsp;</td>
<td>2009-11-11</td>
</tr>
</tbody>
</table>
<p>  这种类型的DBMS称为关系数据库管理系统(Relational Database Management System,RDBMS).比较具有代表性的DBMS有如下几种</p>
<ul>
<li>Oracle Database: 甲骨文的RDBMS</li><li>SQL Server: 微软公司</li><li>DB2: IBM公司 </li><li>Postgresql: 开源</li><li>MySQL: 开源</li></ul>
</li><li><p>面向对象数据库(Object Oriented Database,OODB)</p>
<p><strong>编程语言当中有一种被称为面向对象的语言(主要是Java和C++).该类数据库把数据以及对数据的操作集合起来以对象为单位进行管理,因此得名.面向对象数据库就是用来保存这些对象的数据库</strong></p>
</li><li><p>XML数据库(XML Database,XMLDB)</p>
<p><strong>最近几年,XML作为网络上进行数据交互传输的形式逐渐普及起来,XML数据库可以对XML形式的大量数据进行告诉处理</strong></p>
</li><li><p>键值存储系统(Key-Value Store,KVS)</p>
<p><strong>这是一种单纯用来保存查询所使用的主键(Key)和值(Value)的组合的数据库.具有编程语言经验的读者可以把它想象成关联数组或者是散列(Hash).近年来,随着键值存储系统被应用到Google等需要大量数据进行超高速查询的Web服务当中,它正逐渐为人们关注</strong></p>
</li></ol>
<h3>1-2 数据库的结构</h3>
<h4>使用RDBMS时,最常见的系统结构就是 客户端/服务器(C/S类型)</h4>
<h4>根据SQL语句的内容返回的数据,同样必须是二维表的形式,这也是关系数据库的特征之一.执行结果如果不是二维表的SQL语句则无法执行.</h4>
<h5>表的列(垂直的方向)称为字段,它代表了保存在表中的数据项目;与之相对表的行(水平方向)称为记录,它相当于一条数据;关系数据库必须以行为单位进行数据读写.</h5>
<ul>
<li>法则1-1: 关系数据表以行为单位读写数据</li><li>法则1-2: 一个单元格只能输入一个数据</li></ul>
<h3>1-3 SQL概要</h3>
<h4>标准SQL</h4>
<p>   <strong>标准SQL就是国际标准化组织(ISO)为SQL制定了相应的标准,以此为基准的SQL称为标准SQL</strong></p>
<ul>
<li>法则1-3:学会标准的SQL就可以在各种RDBMS中书写SQL语句了.</li></ul>
<h4>SQL语句及其种类</h4>
<p>   <strong>SQL用关键字、表名、列名等组合而成的一条语句(SQL语句)来描述操作的内容.关键字是指那些含义或使用方法事先已定义好的英语单词,例如&quot;对表进行查询&quot;或者&quot;参考这个表&quot;等包含各种意义的关键字,根据对RDBMS赋予的指令种类不同,SQL语句可以氛围以下三类:</strong></p>
<ul>
<li><p>DDL(Data Definition Language,数据定义语言)用来穿件或者删除存储数据用的数据库以及数据库中的表等对象.DDL包含以下几种指令.</p>
<ul>
<li>CREATE: 创建数据库和表等对象</li><li>DROP: 删除数据库和表等对象</li><li>ALTER: 修改数据库和表等对象的结构</li></ul>
</li><li><p>DML(Data Manipulation Language,数据操作语言)用来查询或者变更表中的记录.DML包含一下几种指令:</p>
<ul>
<li>SELECT: 查询表中的数据</li><li>INSERT: 向表中插入新数据</li><li>UPDATE: 变更表中的数据</li><li>DELETE: 删除表中的数据</li></ul>
</li><li><p>DCL(Data Control Language,数据控制语言) 用来确认或者取消对数据库中的数据进行变更.除此之外,还可以对RDBMS的用户是否有权限操作数据库中的对象(数据库表等)进行设定.DCL包含以下几种指令:</p>
<ul>
<li>COMMIT: 确认数据库中的数据进行的变更</li><li>ROLLBACK: 取消对数据库中的数据进行的变更</li><li>GRANT: 赋予用户操作权限</li><li>REVOKE: 取消用户权</li></ul>
</li></ul>
<p><strong><em>实际使用中90%的SQL语句都属于DML</em></strong></p>
<ul>
<li>法则1-4: SQL 根据功能不同可以分为三类,其中使用最多的是DML.</li></ul>
<h4>SQL的基本书写规则</h4>
<ol>
<li><strong>SQL语句要以分号(;) 结尾</strong> <ul>
<li>法则1-5: SQL语句要以分号(;) 结尾</li></ul>
</li><li><strong>SQL语句不区分大小写</strong><ul>
<li>法则1-6: 关键字不区分大小写<br><strong>建议使用以下规则来书写SQL语句</strong><ul>
<li>关键字大写</li><li>表名的首字母大写</li><li>其余(列名等)小写</li></ul>
</li></ul>
</li><li><strong>常数的书写格式是固定的</strong><br>SQL语句常常需要直接书写字符串,日期或者数字,这些称为常数在输入字符串和日期的时候需要用单引号括起来,而数字则直接输入<br>字串如&#39;abc&#39;;日期如&#39;10 Jan 2010&#39;;&#39;2010-01-26&#39;等<ul>
<li>法则1-7: 字串和日期常数需要用单引号(&#39;)括起来,数字常数则无需加注单引号,直接书写数字即可.</li></ul>
</li><li><strong>单词需要用半角空格或者换行符来分隔</strong><ul>
<li>法则1-8: SQL语句的单词之间需要使用半角空格或者换行符来进行分隔</li></ul>
</li></ol>
<h3>1-4 表的创建</h3>
<h4>数据库的创建</h4>
<pre><code>    命令格式:
        CREATE DATABASE &lt;DatabaseName&gt;;
    案例:
        CREATE DATABASE shop;
</code></pre><h4>表的创建</h4>
<pre><code>    命令格式:
        CREATE TABLE &lt;TableName&gt;
        (&lt;列名1&gt; &lt;数据类型&gt; &lt;该列所需约束&gt;,
        &lt;列名2&gt; &lt;数据类型&gt; &lt;该列所需约束&gt;,
        &lt;列名3&gt; &lt;数据类型&gt; &lt;该列所需约束&gt;,
        &lt;列名4&gt; &lt;数据类型&gt; &lt;该列所需约束&gt;,
                    .
                    .
                    .
        &lt;该表的约束1&gt;,&lt;该表的约束2&gt;
        );
    案例:
        CREATE TABLE Shohin            //创建表Shohin
        (shohin_id    CHAR(4)        NOT NULL,    
        shohin_mei    VARCHAR(100)        NOT NULL,
        shohin_bunrui    VARCHAR(100)        NOT NULL,
        hanbai_tanka    INTEGER        ,
        shiire_tanka    INTEGER        ,
        torokubi        DATE        ,
        PRIMARY KEY (shohin_id)
        );
</code></pre><h4>命名规则</h4>
<p>   <strong>我们只能用半角英文字母,数字,下划线作为数据库,表,和列的名称;而且以特殊符号开头的名称并不多见;标准SQL的规则是半角字母开头</strong></p>
<ul>
<li>法则1-9: 数据库名称,表名,列名等可以使用三种字符: ①半角英文字母 ②半角数字 ③下划线(_)</li><li>法则1-10: 名称必须以半角英文字母作为开头</li><li>法则1-11: 在同一个数据库中不能创建两个相同名称的表,在同一张表里,也不能创建两个相同名称的列.</li></ul>
<h4>数据类型的指定</h4>
<p>   <strong>数据类型表示数据的种类,包括数字型、字符型、和日期型等.每一列都不能存储与该类型不符的数据,我们暂时先使用四种基本的数据类型</strong></p>
<ul>
<li>INTEGER 整数型: 用来指定存储整数的列的数据类型,不能存储小数</li><li>CHAR 字符型: 用来指定存储字符串类型的数据类型.可以像CHAR(10)或者CHAR(200)这样在括号中指定该列可以存储的字符串长度(最大长度),字符串以<em>定长字符串</em>的形式存储在被指定为CHAR型的列中.当列中存储的字符串长度达不到最打长度时,使用半角空格进行补足. 如我们向CHAR(8)的列中输入&#39;abc&#39;的时候,会以&#39;abc　　　　　&#39;的形式保存</li><li>VARCHR 可变长字符串型: 同CHAR一样,VARCHAR型也是用来指定存储字符串的列的数据类型(字符串型).也可以通过括号内的数字来指定字符串的长度(最大长度).但是该类型的列是<em>可变长字符串</em>的形式来保存字符串的.<em>定长字符串</em>在字符数未达到最大长度时会用半角空格不足,<em>可变长字符串</em>不同,即使字符数未达到最大长度,也不会用半角空格补足.</li><li>DATE 日期类型:用来存储日期(年-月-日)的列的数据类型</li></ul>
<h4>约束的设置</h4>
<p>   约束是除了数据类型之外,对列中存储的数据进行限制和追加条件的功能.上例中Shohin表中设置了shohin_id列、shohin_mei列还有shohin_bunrui列的NOT NULL<br>   数据类型的右侧设定了NOT NULL的约束.NULL代表空白(无记录)的关键字,在NULL 前加了NOT,就是给该列设定了不能输入空白,也就是必须输入的约束(如果什么都不输入就会报错)<br>   另外,在创建Shohin表的CREATE TABLE 语句后面还有下面这样的记述,其作用是给shohin_id列设定主键约束的.*<br>    <code>PRIMARY KEY(shohin_id)</code><br>   所谓主键,是指定特定数据时使用的列的组合.键值种类多样,主键(PRIMARY KEY)就是可以<strong>特定一行数据</strong>(唯一可以确定一行的数据,比如ID列)的列,也就是说,如果把Shohin_id的列指定为主键,就可以通过该列取出特定的商品数据了.<br>   反之,如果向shohin_id列中输入了重复数据,就无法取出唯一的特定数据了(因为无法确定唯一的一行数据).</p>
<h3>1-5 表的删除和更新</h3>
<h4>表的删除</h4>
<pre><code>命令格式:
DROP TABLE &lt;表名&gt;;
案例:
DROP TABLE Shohin;
</code></pre><ul>
<li>法则1-12: 删除了的表是无法恢复的;在执行DROP TABLE前请务必仔细确认.</li></ul>
<h4>表定义的更新</h4>
<p><strong>有时好不容易把表创建出来之后发现少了几列,其实这时无需把表删了重新创建,只需使用变更表定义的<code>ALTER TABLE</code>语句就可以了.</strong></p>
<pre><code>命令格式:
ALTER TABLE &lt;表名&gt; ADD COLUMN &lt;列的定义&gt;;
案例:我们可以在Shohin表中添加这样一列,shohin_mei_kana,该列可存储100位可变长的字符串.
ALTER TABLE shohin ADD COLUMN shohin_mei_kana VARCHAR(100);
</code></pre><p><strong>反之,我们也可以删除表中的某一列</strong></p>
<pre><code>命令格式:
ALTER TABLE &lt;表名&gt; DROP COLUMN &lt;列名&gt;;
案例: 删除Shohin表中的shohin_mei_kana列
ALTER TABLE Shohin DROP COLUMN shohin_mei_kana;
</code></pre><ul>
<li>法则1-13: 表定义变更之后无法恢复,再执行ALTER TABLE语句前请务必仔细确认.</li></ul>
<h4>向Shohin表中插入数据</h4>
<pre><code>案例:
--DML:插入语句

BEGIN TRANSACTION;
INSERT INTO Shohin VALUES (&#39;0001&#39;, &#39;T恤衫&#39;, &#39;衣服&#39;, 1000, 500, &#39;2009-09-20&#39;);
INSERT INTO Shohin VALUES (&#39;0002&#39;, &#39;打孔器&#39;, &#39;办公用品&#39;, 500, 320, &#39;2009-09-11&#39;);
INSERT INTO Shohin VALUES (&#39;0003&#39;, &#39;运动T恤&#39;, &#39;衣服&#39;, 4000, 2800, NULL);
INSERT INTO Shohin VALUES (&#39;0004&#39;, &#39;菜刀&#39;, &#39;厨房用具&#39;, 3000, 2800, &#39;2009-09-20&#39;);
INSERT INTO Shohin VALUES (&#39;0005&#39;, &#39;高压锅&#39;, &#39;厨房用具&#39;, 6800, 5000, &#39;2009-01-15&#39;);
INSERT INTO Shohin VALUES (&#39;0006&#39;, &#39;叉子&#39;, &#39;厨房用具&#39;, 500, NULL &#39;2009-09-20&#39;);
INSERT INTO Shohin VALUES (&#39;0007&#39;, &#39;擦菜板&#39;, &#39;厨房用具&#39;, 880, 790, &#39;2008-04-28&#39;);
INSERT INTO Shohin VALUES (&#39;0008&#39;, &#39;圆珠笔&#39;, &#39;办公用品&#39;, 100, NULL, &#39;2009-11-11&#39;);

COMMIT
</code></pre><p><strong>使用插入行的指令语句INSERT,就可以把数据都插入到表中了,开头的BEGIN TRANSCTION语句是开始插入行的指令语句,结尾的COMMIT语句是确定插入行的指令语句,这些语句将在后面详细介绍.</strong><br><strong><em>注意像上面这样多行语句的要选中他们之后执行才会主句执行!</em></strong></p>
<h4>表的修改(重命名)</h4>
<p><strong>假如我们在创建表的时候,不小心输错了表名,而后又录入了数据,如果我们删除表再重新建表,重新录数据,太麻烦,这时候我们就可以用RENAME来修改表名</strong></p>
<pre><code>POSTGRESQL 特有的重命名命令
命令格式:
ALTER TABLE &lt;TableName&gt; RENAME TO &lt;NewTableName&gt;;
案例:
ALTER TABLE Shohin RENAME TO Shaolin; //把表Shohin重命名为Shaolin.

MYSQL重命名表的命令:
RENAME TABLE Shohin TO Shaolin;
</code></pre><h2>第二章 查询基础</h2>
<h3>2-1 SELECT语句基础</h3>
<h4>列的查询</h4>
<p> 从表中选取数据时需要使用SELECT语句,也就是只从表中选出(SELECT)必要数据的意思.通过SELECT语句查询并选取出必要数据的过程称为<strong>匹配查询</strong>或 <strong>查询</strong>;</p>
<pre><code>命令格式:
SELECT &lt;列名&gt;,...
FROM &lt;表名&gt;;
案例: 从Shohin表中查询出Shohin\_id列,Shohin\_mei列,和shiire_tanka列
SELECT shohin_id,shohin_mei,shiire_tanka
FROM Shohin;
</code></pre><p>   显示结果如下</p>
<table>
<thead>
<tr>
<th>Shohin_id</th>
<th>Shohin_mei</th>
<th>shiire_tanka   </th>
</tr>
</thead>
<tbody>
<tr>
<td>  0001</td>
<td>T恤</td>
<td>500</td>
</tr>
<tr>
<td>  0002</td>
<td>打孔器</td>
<td>320</td>
</tr>
<tr>
<td>  0003</td>
<td>运动T恤</td>
<td>2800</td>
</tr>
<tr>
<td>  0004</td>
<td>菜刀</td>
<td>2800</td>
</tr>
<tr>
<td>  0005</td>
<td>高压锅</td>
<td>5000</td>
</tr>
<tr>
<td>  0006</td>
<td>叉子</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>  0007</td>
<td>擦菜板</td>
<td>790</td>
</tr>
<tr>
<td>  0008</td>
<td>圆珠笔</td>
<td>&nbsp;</td>
</tr>
</tbody>
</table>
<p>从上面案例可以看出SELECT语句包含了SELECT 和FROM 两个字句.字句是SQL语句的组成要素,是以SELECT或者FROM等作为其实短语.<br>SELECT字句中列举了希望从表中查询初级的列的名称,而FROM子句则指定了选取出数据的表的名称<br>SELECT语句的第一行的SELECT shohin_id,shohin_mei,shiire_tanka就是SELECT子句,查询出的顺序可以任意指定,查询多列时,需要用逗号进行分隔排列.<strong>查询结果中列的顺序和SELECT子句中的顺序相同</strong></p>
<h4>查询出表中所有的列</h4>
<p>想要查询出全部列时,可以使用代表所有列的<strong>星号(*)</strong></p>
<pre><code>命令格式
SELECT *
FROM &lt;表名&gt;;

案例:
SELECT *
FROM Shohin;

其查询结果等同于
SELECT shohin_id,shohin_mei,shohin_bunrui,hanbai_tanka,shiire_tanka,torokubi
FROM Shohin;
</code></pre><ul>
<li>法则2-1 星号(*)代表全部列的意思</li></ul>
<p><em>如果使用星号的话,就无法设定列的显示顺序了.这是就会按照CREATE TABLE语句定义对列进行排序.</em><br><strong><em>特别注意,如果在连字句中间随意插入空行,会造成执行错误,请特别注意</em></strong></p>
<h4>为列设定别名</h4>
<p>SQL语句可以使用<strong><em>AS关键字</em></strong>为列设定别名;作用是在查询结果中用别名来代替原来的列名</p>
<pre><code>命令格式:
SELECT &lt;id1&gt; AS &lt;alias1&gt;,
       &lt;id2&gt; As &lt;alias2&gt;,
       ...
       &lt;id3&gt; As &lt;alias3&gt;
FROM Shohin;

案例:
SELECT shohin_id AS id,
    shohin_mei AS namae,
        ...
    shiire_tanka AS tanka
FROM Shohin;
</code></pre><p>别名可以使用汉语,使用汉语时,需要用<strong><em>双引号</em></strong>括起来,请注意一定要用双引号,不可以用<del>单引号</del>.</p>
<pre><code>SELECT shohin_id AS &quot;商品编号&quot;,
shohin_mei AS &quot;商品名称&quot;,
shiire_tanka AS &quot;进货单价&quot;
FROM shohin;
</code></pre><ul>
<li>法则2-2 设定汉语别名时,需要用双引号(&quot; &quot;)括起来</li></ul>
<h4>常数的查询</h4>
<p>SELECT子句不仅可以书写别名,还可以书写常数.</p>
<pre><code>案例代码:
SELECT &#39;商品&#39; AS mojiretsu,
 38 AS kazu,
 &#39;2009-02-24&#39; AS hizuke,
 shohin_id,shohin_mei
FROM shohin;
</code></pre><p><strong><em>在SQL语句中使用字符串或者日期常数时,必须使用单引号将其括起来</em></strong></p>
<h4>从结果中删除重复行</h4>
<p>想要删除重复行时,可以通过在SELECT子句中使用<strong><em>DISTINCT(去重)</em></strong>来实现</p>
<pre><code>代码如下:
SELECT DISTINCT shohin_bunrui
FROM shohin;
</code></pre><ul>
<li>法则2-3: 在SELECT语句中使用DISTINCT可以删除重复行(也就是去重)<br>在使用DISTINCT时,NULL也被视为一类数据,存在多条NULL数据行时,也会结合为一条NULL数据.<br>同时 DISTINC也可以用在多列之前使用,多列之间用逗号隔开,而且DISTINCT只能放在第一个列名前面.<br>多列去重时,只会去除所有列都重复的行.<br>比如<pre><code>SELECT DISTINCT shohin_bunrui, torokubi
FROM shohin;
</code></pre></li></ul>
<h4>根据WHERE语句来选择记录</h4>
<p>前面的例子都是将表中存储的数据全都取出来,但实际上并不是每次都需要选取出全部数据,大部分情况都是要选取出满足&quot;商品种类为衣服&quot;、&quot;销售单价在1000元以上&quot;等某些条件的数据.<br>SELECT语句通过WHERE子句来指定查询数据的条件.在<strong><em>WHERE子句</em></strong>中可以指定条件.执行含有这些条件的SELECT语句,就可以查询出符合该条件的记录了.</p>
<pre><code>语法格式:
SELECT &lt;列名&gt;,...
 FROM &lt;表名&gt;
 WHERE &lt;条件表达式&gt;;

案列:选取商品种类为&quot;衣服&quot;的记录
 SELECT shohin_mei, shohin_bunrui
 FROM Shohin
 WHERE shohin_bunrui = &#39;衣服&#39;
</code></pre><p>WHERE子句中的shohin_bunrui = &#39;衣服&#39; 就是用来反映查询条件的表达式(条件表达式).等号是比较两边内容是否相等的符号,上述条件就是将shohin_bunrui列的值和&#39;衣服&#39;进行比较,判断是否相等.shohin表的所有记录都会进行比较;<br>接下来会从查询的记录中选取出SELECT语句指定的shohin_mei和shohin_bunrui列,如执行结果所示.也就是<strong><em>首先通过WHERE字句查询出符合指定条件的记录,然后再选取出SELECT语句指定的列(也就是先选行,再选列)</em></strong>.<br>上述的案例中,为了确认选取出的数据是否正确,通过SELECT子句把作为查询条件的shohin_bunrui列也选取出来了,其实这并不是必须的.如果只想知道商品名称的话,可以向下面这样写:</p>
<pre><code>SELECT shohin_mei
FROM Shohin
WHERE shohin_bunrui = &#39;衣服&#39;;

显示结果如下:
  shohin_mei
--------------
    T恤衫
运动T恤
</code></pre><p><strong><em>SQL中子句的顺序是固定的,不能随便更改</em></strong>. WHERE子句必须紧跟在FROM子句之后.书写顺序发生改变的话,会造成执行错误.</p>
<ul>
<li>法则2-4 WHERE子句要紧跟在FROM子句之后.</li></ul>
<h4>注释的书写方法</h4>
<ul>
<li>1行注释: 在语句前面输入&quot;--&quot;,必须和语句写在同一行</li><li>多行注释: 语句书写在&quot;/<em>&quot; 和&quot;</em>/&quot; 之间,可以跨多行</li></ul>
<ul>
<li>法则2-5: 注释是SQL语句用来标识说明或者注意是想的部分.分为一行注释和多行注释.</li></ul>
<h3>2-2 算数运算符和比较运算符</h3>
<h4>算术运算符</h4>
<p>SQL语句中可以使用计算表达式.</p>
<pre><code>案例:要求把shohin表中商品的单价(hanbai_tanka)的两倍以hanbai_tanka×2列的形式读取出来

代码:
SELECT shohin_mei,hanbai_tanka,hanbai_tanka * 2 AS &quot;hanbai_tanka×2&quot;
FROM Shohin;
</code></pre><p><strong>SQL语句中可以使用的四则运算的主要运算符</strong></p>
<table>
<thead>
<tr>
<th>含义</th>
<th>运算符</th>
</tr>
</thead>
<tbody>
<tr>
<td>加法运算</td>
<td>+</td>
</tr>
<tr>
<td>减法运算</td>
<td>-</td>
</tr>
<tr>
<td>乘法运算</td>
<td>*</td>
</tr>
<tr>
<td>除法运算</td>
<td>/</td>
</tr>
</tbody>
</table>
<ul>
<li>法则2-6: SELECT子句中可以使用常数或者表达式</li></ul>
<p>当然,SQL中也可以像平常的运算表达式那样使用括号.括号中运算表达式的优先级会得到提升,优先进行运算.</p>
<h4>需要注意NULL</h4>
<p>SQL语句中进行运算时,需要特别注意含有NULL的运算.比如下面几个运算表达式:</p>
<ul>
<li>5 + NULL</li><li>10 - NULL</li><li>1 * NULL</li><li>4 / NULL</li><li>NULL / 9</li><li>NULL / 0</li></ul>
<p>正确答案全部都是<strong><em>NULL</em></strong>,<strong><em>实际上所有包含NULL的计算,结果肯定是NULL</em></strong>.</p>
<h4>拓展:FROM子句真的需要吗?</h4>
<p>实际上FROM子句在SELECTL语句中并不是必不可少的,只是用SELECT子句进行计算也是可以的.</p>
<pre><code>SELECT (100 + 200) *3 AS keisan;

执行结果:
 keisan
--------
    900
</code></pre><p>实际上,通过执行SELECT语句来代替计算器的情况基本上是不存在的,不过极少数情况下,还是可以通过使用没有FROM子具有的SELECT 来实现某种业务的.例如,希望得到的内容为空,只包含一行临时数据的情况.</p>
<h4>比较运算符</h4>
<p>在之前我们使用符号 = 从Shohin表中选取出了商品种类&quot;shohin_bunrui&quot;为字符串&#39;衣服&#39;的记录.下面我们再使用符号 = 选取销售单价(hanbai_tanka)为500元的记录</p>
<pre><code>代码:
SELECT shohin_mei,shohin_bunrui
FROM Shohin
WHERE hanbai_tanka = 500;
</code></pre><p>执行结果:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui </th>
</tr>
</thead>
<tbody>
<tr>
<td>打孔器</td>
<td>办公用品</td>
</tr>
<tr>
<td>叉子</td>
<td>厨房用品</td>
</tr>
</tbody>
</table>
<p>接下来,我们使用&quot;不等于&quot;这样的代表否定含义的比较运算符 &quot;&lt;&gt;&quot;,选取出hanbai_tanka列的值不为500的记录.</p>
<pre><code>代码:
SELECT shohin_mei,shohin_bunrui
FROM Shohin
WHERE hanbai_tanka &lt;&gt; 500;
</code></pre><p>执行结果</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui </th>
</tr>
</thead>
<tbody>
<tr>
<td>T恤</td>
<td>衣服</td>
</tr>
<tr>
<td>运动T恤</td>
<td>衣服</td>
</tr>
<tr>
<td>菜刀</td>
<td>厨房用具</td>
</tr>
<tr>
<td>高压锅</td>
<td>厨房用具</td>
</tr>
<tr>
<td>擦菜板</td>
<td>厨房用具</td>
</tr>
<tr>
<td>圆珠笔</td>
<td>办公用品</td>
</tr>
</tbody>
</table>
<p>SQL中主要的比较运算符如下表所示,除了等于和不等于之外,还有进行大小比较的运算符.</p>
<table>
<thead>
<tr>
<th>运算符</th>
<th>含义</th>
</tr>
</thead>
<tbody>
<tr>
<td>=</td>
<td>和~相等</td>
</tr>
<tr>
<td>&lt;&gt;</td>
<td>和~不相等</td>
</tr>
<tr>
<td>>=</td>
<td>大于等于~</td>
</tr>
<tr>
<td>></td>
<td>大于~</td>
</tr>
<tr>
<td>&lt;=</td>
<td>小于等于~</td>
</tr>
<tr>
<td>&lt;</td>
<td>小于~</td>
</tr>
</tbody>
</table>
<p>这些比较运算符可以对字符、数字、和日期等几乎所有数据类型的列个值进行比较。<br>例如，从Shohin表中选取出销售单价(hanbai_tanka)大于等于1000元的记录</p>
<pre><code>代码:
SELECT shohin_mei,shohin_bunrui,hanbai_tanka
FROM Shohin
WHERE hanbai_tanka &gt;= 1000;
</code></pre><p>执行结果:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui</th>
<th>hanbai_tanka</th>
</tr>
</thead>
<tbody>
<tr>
<td>T恤</td>
<td>衣服</td>
<td>1000</td>
</tr>
<tr>
<td>运动T恤</td>
<td>衣服</td>
<td>4000</td>
</tr>
<tr>
<td>菜刀</td>
<td>厨房用具</td>
<td>3000</td>
</tr>
<tr>
<td>高压锅</td>
<td>厨房用具</td>
<td>6000</td>
</tr>
</tbody>
</table>
<p>再比如,选取除登记日期(torokubi)在2009年9月27日之前的记录.</p>
<pre><code>SELECT shohin_mei,shohin_bunrui,torokubi
FROM shohin
WHERE torokubi &lt; &#39;2009-09-27&#39;;
</code></pre><p>执行结果:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui</th>
<th>torokubi</th>
</tr>
</thead>
<tbody>
<tr>
<td>T恤</td>
<td>衣服</td>
<td>2009-09-20</td>
</tr>
<tr>
<td>打孔器</td>
<td>办公用品</td>
<td>2009-09-11</td>
</tr>
<tr>
<td>菜刀</td>
<td>厨房用具</td>
<td>2009-09-20</td>
</tr>
<tr>
<td>高压锅</td>
<td>厨房用具</td>
<td>2009-01-15</td>
</tr>
<tr>
<td>叉子</td>
<td>厨房用具</td>
<td>2009-09-20</td>
</tr>
<tr>
<td>擦菜板</td>
<td>厨房用具</td>
<td>2008-04-28</td>
</tr>
</tbody>
</table>
<ul>
<li>法则2-7:使用比较运算符时一定要注意不等号和等号的位置,一定要让不等号在左,等号在右.</li></ul>
<p>除此之外,还可以使用比较运算符对计算结果进行比较.<br>案例,我们现在需要统计出销售利润超过500的记录(也就是 hanbai_tanka - shiire_tanka的值)</p>
<pre><code>代码:

SELECT Shohin_mei,Shohin_bunrui,hanbai_tanka,shiire_tanka
FROM Shohin
WHERE hanbai_tanka - shiire_tanka &gt;= 500;
</code></pre><p>执行结果如下:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>hanbai_tanka</th>
<th>shiire_tanka</th>
</tr>
</thead>
<tbody>
<tr>
<td>T恤</td>
<td>1000</td>
<td>500</td>
</tr>
<tr>
<td>运动T恤</td>
<td>4000</td>
<td>2800</td>
</tr>
<tr>
<td>高压锅</td>
<td>6800</td>
<td>5000</td>
</tr>
</tbody>
</table>
<h4>对字符串使用不等号时的注意事项</h4>
<p>对字符串使用大于等于或者小于等于不等号时会得到什么样的结果呢?我们创建一个Chars表来做测试</p>
<pre><code>代码:
CREATE TABLE Chars(chr CHAR(3) NOT NULL,
PRIMARY KEY (chr));        //创建chars表

BEGIN TRANSACTION;        //向Chars表里插入数据

INSERT INTO Chars VALUES(&#39;1&#39;);
INSERT INTO Chars VALUES(&#39;2&#39;);
INSERT INTO Chars VALUES(&#39;3&#39;);
INSERT INTO Chars VALUES(&#39;10&#39;);
INSERT INTO Chars VALUES(&#39;11&#39;);
INSERT INTO Chars VALUES(&#39;22&#39;);

COMMIT;
</code></pre><p>执行结果:</p>
<table>
<thead>
<tr>
<th>chr(字符串类型)</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
</tr>
<tr>
<td>2</td>
</tr>
<tr>
<td>3</td>
</tr>
<tr>
<td>10</td>
</tr>
<tr>
<td>11</td>
</tr>
<tr>
<td>22</td>
</tr>
</tbody>
</table>
<p>此时如果我们执行Chars表中查询条件是chr列大于&#39;2&#39;,会是什么样的结果呢?</p>
<pre><code>SELECT chr
FROM Chars
WHERE chr &gt; &#39;2&#39;;
</code></pre><p>执行结果:</p>
<table>
<thead>
<tr>
<th>chr</th>
</tr>
</thead>
<tbody>
<tr>
<td>3</td>
</tr>
<tr>
<td>222</td>
</tr>
</tbody>
</table>
<p>这里的原因是WHERE子句里 chr &gt; &#39;2&#39;; 这里比较的是字符串,<strong><em>必须弄清楚 2和 &#39;2&#39;的区别</em></strong><br>之所以 会出现,&#39;3&#39; 和&#39;222&#39;比2大的原理是字典排序原理.就像书的章节, 1-1 排在1后面.这个必须弄清楚.</p>
<ul>
<li>法则2-8: 字符串类型的数据原则上按照字典顺序进行排序.不能与数字的大小混淆.</li></ul>
<h4>不能对 NULL使用比较运算符</h4>
<p>对比较运算符来说还有一点十分重要.那就是,作为查询条件的列中含有NULL的情况. 例如,我们把进货单价(Shiire_tanka)作为查询条件.请注意,商品&#39;叉子&#39;和&#39;圆珠笔&#39;的进货单价是NULL.</p>
<p>我们先来选取进货单价为2800元(Shiire_tanka = 2800)的记录.</p>
<pre><code>代码:
SELECT shohin_mei,shohin_bunrui,shiire_tanka
FROM shohin
WHERE shiire_tanka = 2800;
</code></pre><p>执行结果如下:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui</th>
<th>shiire_tanka</th>
</tr>
</thead>
<tbody>
<tr>
<td>运动T恤</td>
<td>衣服</td>
<td>2800</td>
</tr>
<tr>
<td>菜刀</td>
<td>厨房用具</td>
<td>2800</td>
</tr>
</tbody>
</table>
<p>然后我们再选取进货单价不是2800元(shiire_tanka &lt;&gt; 2800)的记录</p>
<pre><code>SELECT shohin_mei,shohin_bunrui,shiire_tanka
FROM Shohin
WHERE shiire_tanka &lt;&gt; 2800;
</code></pre><p>执行结果如下</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui</th>
<th>shiire_tanka</th>
</tr>
</thead>
<tbody>
<tr>
<td>T恤</td>
<td>衣服</td>
<td>500</td>
</tr>
<tr>
<td>打孔器</td>
<td>办公用品</td>
<td>320</td>
</tr>
<tr>
<td>高压锅</td>
<td>厨房用具</td>
<td>5000</td>
</tr>
<tr>
<td>擦菜板</td>
<td>厨房用具</td>
<td>790</td>
</tr>
</tbody>
</table>
<p>我们发现上两条查询记录的结果中都没有&quot;叉子&quot;和&quot;圆珠笔&quot;,这两条记录由于进货单价不明,无法判定为是不是2800元.</p>
<p>于是我们尝试了第三个方法:<del>注意这个方法的语句为错误语句</del></p>
<pre><code>代码:
SELECT shohin_mei,shohin_bunrui,shiire_tanka
FROM Shohin
WHERE shiire_tanka = NULL;
</code></pre><p>执行结果为一条记录也没有:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui</th>
</tr>
</thead>
<tbody>
<tr>
<td></td>
</tr>
</tbody>
</table>
<p>即使使用&lt;&gt;运算符也还是无法选取出NULL的记录.因此SQL提供了专门来判断是否为NULL 的运算符 IS NULL.想要选取NULL的记录时,可以用下面的代码:</p>
<pre><code>SELECT shohin_mei,shohin_bunrui,shiire_tanka
FROM Shohin
WHERE shiire_tanka IS NULL;
</code></pre><p>执行结果如下:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui</th>
<th>shiire_tanka</th>
</tr>
</thead>
<tbody>
<tr>
<td>叉子</td>
<td>厨房用具</td>
<td>NULL    </td>
</tr>
<tr>
<td>圆珠笔</td>
<td>办公用品</td>
<td>NULL    </td>
</tr>
</tbody>
</table>
<p>反之,希望选取不是NULL记录时,需要使用<strong><em>IS NOT NULL</em></strong>运算符:</p>
<pre><code>SELECT shohin_mei,shohin_bunrui,shiire_tanka
FROM shohin
WHERE shiire_tanka IS NOT NULL;
</code></pre><p>执行结果如下:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui</th>
<th>shiire_tanka</th>
</tr>
</thead>
<tbody>
<tr>
<td>T恤</td>
<td>衣服</td>
<td>500</td>
</tr>
<tr>
<td>打孔器</td>
<td>办公用品</td>
<td>320</td>
</tr>
<tr>
<td>运动T恤</td>
<td>衣服</td>
<td>2800</td>
</tr>
<tr>
<td>菜刀</td>
<td>厨房用具</td>
<td>2800</td>
</tr>
<tr>
<td>高压锅</td>
<td>厨房用具</td>
<td>5000</td>
</tr>
<tr>
<td>擦菜板</td>
<td>厨房用具</td>
<td>790</td>
</tr>
</tbody>
</table>
<ul>
<li>法则2-9: 希望选取NULL记录时,需要在条件表达式中使用IS NULL运算符.希望选取不是NULL的记录时,需要在条件表达式中使用IS NOT NULL运算符.</li></ul>
<h3>2-3逻辑运算符</h3>
<h4>NOT运算符</h4>
<p>在前面我们了解了想要指定&quot;不是~&quot;这样的否定条件时,要用&lt;&gt;运算符.除此之外还存在另一个表示否定,并且使用范围更广的运算符NOT.</p>
<p>NOT不能单独使用必须和其他查询条件组合起来使用.例如选取出销售单价(Hanbai_tanka)大于等于1000元记录的SELECT语句:</p>
<pre><code>SELECT shohin_mei,shohin_bunrui,hanbai_tanka
FROM Shohin
WHERE hanbai_tanka &gt;=1000;
</code></pre><p>执行结果如下:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui</th>
<th>hanbai_tanka</th>
</tr>
</thead>
<tbody>
<tr>
<td>T恤</td>
<td>衣服</td>
<td>1000</td>
</tr>
<tr>
<td>运动T恤</td>
<td>衣服</td>
<td>4000</td>
</tr>
<tr>
<td>菜刀</td>
<td>厨房用具</td>
<td>3000</td>
</tr>
<tr>
<td>高压锅</td>
<td>厨房用具</td>
<td>6800</td>
</tr>
</tbody>
</table>
<p>向上面的SELECT语句的查询条件中添加NOT运算符之后:</p>
<pre><code>SELECT shohin_mei,shohin_bunrui,hanbai_tanka
FROM Shohin
WHERE NOT haiban_tanka &gt;=1000
</code></pre><p>执行结果如下:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui</th>
<th>hanbai_tanka</th>
</tr>
</thead>
<tbody>
<tr>
<td>打孔器</td>
<td>办公用品</td>
<td>500</td>
</tr>
<tr>
<td>叉子</td>
<td>厨房用具</td>
<td>500</td>
</tr>
<tr>
<td>擦菜板</td>
<td>厨房用具</td>
<td>880</td>
</tr>
<tr>
<td>圆珠笔</td>
<td>办公用品</td>
<td>100</td>
</tr>
</tbody>
</table>
<p>我们发现这条语句的结果等同于</p>
<pre><code>SELECT shohin_mei,shohin_bunrui,hanbai_tanka
FROM Shohin
WHERE hanbai_tanka &lt; 1000;
</code></pre><p>通过上面的例子,我们发现不使用NOT运算符,我们也可以编写出效果相同的查询条件.不仅如此,不使用NOT运算符的查询条件更容易让人理解.<br>尽管如此,我们也不能完全否定NOT运算符的作用.在便携复杂的SQL语句时,经常会看到NOT的身影. 但是我们不要滥用NOT运算符</p>
<ul>
<li>法则2-10 NOT运算符用来否定某一条件,但是不能滥用.</li></ul>
<h4>AND 运算符和 OR运算符</h4>
<p>在WHERE子句中使用AND运算符或者OR运算符,可以对多个查询条件进行组合.<br>AND运算符<strong><em>在其两侧的查询条件都成立时,整个查询条件才成立</em></strong>.其意思相当于&quot;并且&quot;.<br>OR运算符<strong><em>在其两侧的查询条件有一个成立,整个查询条件就成立</em></strong>.其意思相当于&quot;或者&quot;;当然 两个条件都成立时,整个查询条件也成立.</p>
<p>案例1:从Shohin表中选取出&quot;商品分类是厨房用具(shohin_bunrui = &#39;厨房用具&#39;),并且销售单价大于等于3000元(hanbai_tanka &gt;= 3000) 的商品&quot;的查询条件</p>
<pre><code>代码:
SELECT  shohin_mei,shohin_bunrui,hanbai_tanka
FROM Shohin
WHERE shohin_bunrui = &#39;厨房用具&#39;
AND hanbai_tanka &gt;= 3000;
</code></pre><p>执行结果如下:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui</th>
<th>hanbai_tanka</th>
</tr>
</thead>
<tbody>
<tr>
<td>菜刀</td>
<td>厨房用具</td>
<td>3000</td>
</tr>
<tr>
<td>高压锅</td>
<td>厨房用具</td>
<td>6800</td>
</tr>
</tbody>
</table>
<p>案例2:选取出&quot;商品种类为厨房用具(shohin_bunrui = &#39;厨房用具&#39;),或者销售单价大于等于3000元(hanbai_tanka &gt;= 3000)的商品&quot;:</p>
<pre><code>SELECT shohin_mei,shohine_bunrui,hanbai_tanka
FROM shohin
WHERE shohin_bunrui = &#39;厨房用具&#39;
OR hanbai_tanka &gt;= 3000;
</code></pre><p>执行结果如下:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui</th>
<th>hanbai_tanka</th>
</tr>
</thead>
<tbody>
<tr>
<td>运动T恤</td>
<td>衣服</td>
<td>4000</td>
</tr>
<tr>
<td>菜刀</td>
<td>厨房用具</td>
<td>3000</td>
</tr>
<tr>
<td>高压锅</td>
<td>厨房用具</td>
<td>6800</td>
</tr>
<tr>
<td>叉子</td>
<td>厨房用具</td>
<td>500</td>
</tr>
<tr>
<td>擦菜板</td>
<td>厨房用具</td>
<td>880</td>
</tr>
</tbody>
</table>
<ul>
<li>法则2-11: 多个查询条件进行组合时,使用AND运算符或者OR运算符</li></ul>
<h4>通过括号进行强化</h4>
<p>假如我们需要的查询条件是下面这样的:</p>
<p>&quot;商品种类是办公用品&quot;<br>&quot;登记日期是2009年9月11日或者2009年9月20日&quot;</p>
<p>满足上面条件的商品只有&quot;打孔器&quot;,我们把这些条件原封不动的写入表达式</p>
<pre><code>SELECT shohin_mei,shohin_bunrui,torokubi
FROM Shohin
WHERE shohin_bunrui = &#39;办公用品&#39;
AND torokubi = &#39;2009-09-11&#39;
OR torokubi = &#39;2009-09-20&#39;;
</code></pre><p>执行结果如下:</p>
<table>
<thead>
<tr>
<th>shohin_mei</th>
<th>shohin_bunrui</th>
<th>torokubi</th>
</tr>
</thead>
<tbody>
<tr>
<td>T恤</td>
<td>衣服</td>
<td>2009-09-20</td>
</tr>
<tr>
<td>打孔器</td>
<td>办公用品</td>
<td>2009-09-11</td>
</tr>
<tr>
<td>菜刀</td>
<td>厨房用具</td>
<td>2009-09-20</td>
</tr>
<tr>
<td>叉子</td>
<td>厨房用具</td>
<td>2009-09-20</td>
</tr>
</tbody>
</table>
<p>按找我们想要的匹配条件,按道理应该出的结果是打孔器,但实际结果却不一样.<br>原因是<strong><em>AND比OR的优先级高</em></strong>,上面代码的条件表达式实际上会被解释为</p>
<pre><code>[ shohin_bunrui = &#39;办公用品&#39; AND torokubi = &#39;2009-09-11&#39;]
OR [torokubi = &#39;2009-09-20&#39;]

也就是

&quot;商品种类是办公用品,并且登记日期是2009年9月11日&quot; 或者&quot;登记日期是2009年9月20日&quot;
</code></pre><p>那么,想要优先执行OR运算时,我们可以使用半角括号把OR运算符及两侧的查询条件括起来:</p>
<pre><code>SELECT shohin_mei,shohin_bunrui,torokubi
FROM Shohin
WHERE shohin_bunrui = &#39;办公用品&#39;
AND (torokubi = &#39;2009-09-11&#39;
OR torokubi = &#39;2009-09-20&#39;);
</code></pre><p>执行结果则只显示打孔器了.</p>
<ul>
<li>法则2-12 AND的运算优先级高于OR运算符.想要有限运行OR运算时可以使用括号.</li></ul>
<h4>逻辑运算符和真值</h4>
<p>AND 逻辑积</p>
<table>
<thead>
<tr>
<th>P</th>
<th>Q</th>
<th>积</th>
<th>P AND Q</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>1</td>
<td>1×1</td>
<td>1</td>
</tr>
<tr>
<td>1</td>
<td>0</td>
<td>1×0</td>
<td>0</td>
</tr>
<tr>
<td>0</td>
<td>1</td>
<td>0×1</td>
<td>0</td>
</tr>
<tr>
<td>0</td>
<td>0</td>
<td>0×0</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>OR 逻辑和</p>
<table>
<thead>
<tr>
<th>P</th>
<th>Q</th>
<th>和</th>
<th>P OR Q</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>1</td>
<td>1+1</td>
<td>1</td>
</tr>
<tr>
<td>1</td>
<td>0</td>
<td>1+0</td>
<td>1</td>
</tr>
<tr>
<td>0</td>
<td>1</td>
<td>0+1</td>
<td>1</td>
</tr>
<tr>
<td>0</td>
<td>0</td>
<td>0+0</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>NOT</p>
<table>
<thead>
<tr>
<th>P</th>
<th>翻转</th>
<th>NOT P</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>1→0</td>
<td>0</td>
</tr>
<tr>
<td>0</td>
<td>0→1</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>既不是真,也不是假,结果到底是什么呢?其实这是SQL中特有的情况,这时真值是除真假之外的第三种值:<strong><em>不确定(UNKNOWN)</em></strong>.一般逻辑运算并不存在这第三种值.SQL之外的语言也基本上只有真假这两种真值,与通常的逻辑运算被称为二值逻辑相对,只有SQL中的逻辑运算被称为<strong><em>三值逻辑</em></strong>.<br>下面是三值逻辑中的AND 和OR的真值表</p>
<p>AND (<strong><em>其实可以理解为,结果按照坏的那个取</em></strong>)</p>
<table>
<thead>
<tr>
<th>P</th>
<th>Q</th>
<th>P AND Q</th>
</tr>
</thead>
<tbody>
<tr>
<td>真</td>
<td>真</td>
<td>真</td>
</tr>
<tr>
<td>真</td>
<td>假</td>
<td>假</td>
</tr>
<tr>
<td>真</td>
<td>不确定</td>
<td>不确定</td>
</tr>
<tr>
<td>假</td>
<td>真</td>
<td>假</td>
</tr>
<tr>
<td>假</td>
<td>假</td>
<td>假</td>
</tr>
<tr>
<td>假</td>
<td>不确定</td>
<td>假</td>
</tr>
<tr>
<td>不确定</td>
<td>真</td>
<td>不确定</td>
</tr>
<tr>
<td>不确定</td>
<td>假</td>
<td>假</td>
</tr>
<tr>
<td>不确定</td>
<td>不确定</td>
<td>不确定</td>
</tr>
</tbody>
</table>
<p>OR (<strong><em>其实可以理解为,结果按照好的那个取</em></strong>)</p>
<table>
<thead>
<tr>
<th>P</th>
<th>Q</th>
<th>P OR Q</th>
</tr>
</thead>
<tbody>
<tr>
<td>真</td>
<td>真</td>
<td>真</td>
</tr>
<tr>
<td>真</td>
<td>假</td>
<td>真</td>
</tr>
<tr>
<td>真</td>
<td>不确定</td>
<td>真</td>
</tr>
<tr>
<td>假</td>
<td>真</td>
<td>真</td>
</tr>
<tr>
<td>假</td>
<td>假</td>
<td>假</td>
</tr>
<tr>
<td>假</td>
<td>不确定</td>
<td>不确定</td>
</tr>
<tr>
<td>不确定</td>
<td>真</td>
<td>真</td>
</tr>
<tr>
<td>不确定</td>
<td>假</td>
<td>不确定</td>
</tr>
<tr>
<td>不确定</td>
<td>不确定</td>
<td>不确定</td>
</tr>
</tbody>
</table>
<h2>第三章 聚合与排序</h2>
<h3>3-1 对表进行聚合查询</h3>
<h4>聚合函数</h4>
<p>通过SQL对数据进行某种操作或计算时需要使用函数.例如,计算表中全部数据行数时可以使用<strong>count函数</strong>.该函数就是使用count(计数)来命名的.除此之外,SQL中还有很多其他用于合计的函数,下面是5个常用的函数</p>
<ol>
<li>COUNT: 计算表中的记录数(行数).</li><li>SUM: 计算表中数值列的数据的合计值.</li><li>AVG: 计算表中数值列的数据的平均值.</li><li>MAX: 求出表中数值列的数据的最大值.</li><li>MIN: 求出表中数值列的数据的最小值.</li></ol>
<p>如上所示,用于合计的函数称为聚合函数或者集合函数.我们统称为聚合函数.所谓聚合,就是将多行汇总成一行.实际上所有的聚合函数都这样,输入多行输出一行.</p>
<h4>计算表中数据的行数</h4>
<p>函数的函是盒子的意思.<br>计算Shohin表里全部数据行的命令:</p>
<pre><code>SELECT COUNT(*)
FROM Shohin;
</code></pre><p>返回结果</p>
<pre><code>count
-----
  8
</code></pre><p>COUNT() 括号中的输入值称为<strong><em>参数</em></strong>或者<strong><em>parameter</em></strong>,输出值称为<strong><em>返回值</em></strong></p>
<h4>计算NULL以外数据的行数</h4>
<p>想要计算表中全部数据行时,可以用SELECT COUNT(*) ~这样使用星号.如果想得到shiire_tanka列(进货单价)中非空行数的话,可以通过将对象列设定为参数来实现:</p>
<pre><code>SELECT COUNT(shiire_tanka)
FROM shohin;
</code></pre><p>得到的返回值为</p>
<pre><code>count
-----
  6
</code></pre><p>由上面的操作我们得出如下结论:</p>
<ul>
<li>法则3-1 COUNT函数的结果根据参数的不同而不同,COUNT(*)会得到包含NULL的数据行数,而COUNT(&lt;列名&gt;)会得到NULL之外的数据行数;而且星号(*)是COUNT函数特有的参数.</li></ul>
<h4>计算合计值</h4>
<p>我们使用计算合计值的SUM参数,求出销售单价的合计值:</p>
<pre><code>SELECT SUM(shiire_tanka)
FROM shohin;
</code></pre><p>得到的返回值为</p>
<pre><code> sum
-------
 12,210
</code></pre><p>注意:由于SUM 的参数是列名(shiire_tanka),在计算之前就把NULL给排除掉了;所以NULL其实并不在计算表达式当中.</p>
<ul>
<li>法则3-2 聚合函数会将NULL排除在外.但是COUNT(*)例外,并不会排除NULL.</li></ul>
<h4>计算平均值</h4>
<p>计算销售单价和进货单价的平均值</p>
<pre><code>SELECT AVG(hanbai_tanka), AVG(shiire_tanka)
FROM shohin;
</code></pre><p>执行结果</p>
<pre><code> avg      avg
-------+------- 
2097.5     2035
</code></pre><p>计算平均值的情况与SUM函数相同,会事先删除NULL再进行计算.</p>
<h4>计算最大值和最小值</h4>
<p>想要计算出多条记录中的最大值和最小值,可以分别使用<strong>MAX</strong> 和 <strong>MIN</strong>函数,它们的使用方法和SUM一样,需要将列作为参数.<br>案例:计算销售价格和进货价格的最小值</p>
<pre><code>SELECT MAX(hanbai_tanka), MIN(hanbai_tanka)
FROM shohin;
</code></pre><p>得到的结果为</p>
<pre><code> max      min
-------+------- 
6800      100
</code></pre><p>但是,MAX/MIN函数和SUM/AVG函数有一点不同,那就是SUM/AVG函数只能对数值类型的列使用,而MAX/MIN函数原则上可以适用于任何数据类型的列.<br>如:对日期类型的 torokubi</p>
<pre><code>SELECT MAX(torokubi), MIN(torokubi)
FROM shohin;
</code></pre><p>得到的结果如下:</p>
<pre><code>     max       min
-----------+-------------- 
2009-11-11    2008-04-28
</code></pre><ul>
<li>法则3-3: MAX/MIN函数几乎使用所有数据类型的列.SUM/AVG函数只适用于数值类型的列<br>经过测试,针对字符串类型,MAX/MIN按照字典法排的(Z大A小).</li></ul>
<h4>使用聚合函数删除重复值(关键字 DISTINCT)</h4>
<p>案例: 假如我们要统计出商品种类的个数[换言之,就是要求每行一个种类(种类去重)];这里我们同样要用到关键字DISTINCT</p>
<pre><code>SELECT COUNT(DISTINCT shohin_bunrui)
FROM shohin;
执行结果: 
   count
----------
    3
</code></pre><p><strong><em>个人理解:括号的优先级,这里我们是括号里先去重,再统计去重后的行数,也就是种类个数.</em></strong></p>
<p>如果我们把DISTINCT放在COUNT 前面会出现什么结果呢?</p>
<pre><code>SELECT DISTINCT COUNT(shohin_bunrui)
FROM shohin;

执行结果: 
   count
----------
    8

个人理解:括号的优先级,这里我们是先统计shohin_bunrui行数;至于DISTINCT,因为参数不对[变成了COUNT(shohin_bunrui)的结果]应该是没有执行.
</code></pre><ul>
<li>法则3-4: 想要计算值的种类时,可以在COUNT函数的参数中使用DISTINCT</li></ul>
<p>DISTINCT 去重不仅限于COUNT函数,所有的聚合函数都可以使用.<br>案例:</p>
<pre><code>SELECT SUM(hanbai_tanka),SUM(DISTINCT hanbai_tanka)
FROM shohin;

执行结果:
     sum       sum
-----------+-------------- 
    16780      16280

右侧结果比左侧少了500 是因为右侧去重了500(打孔器和叉子的价格都是500,被去重了一个)
</code></pre><ul>
<li>法则3-5: 在聚合函数的参数中使用DISTINCT,可以去重重复数据.</li></ul>
<h3>3-2对表进行分组</h3>
<h4>GROUP BY子句</h4>
<p>如果我们想先把表按照某个列的定义来进行聚合(聚合就是分组,比如按照商品种类来分组,或者登记日期来分组),就可以使用GROUP BY子句</p>
<pre><code>命令格式:
SELECT &lt;列名1&gt;,&lt;列名2&gt;,&lt;列名3&gt;,...  //查询的目标列
FROM &lt;表名&gt;                            
GROUP BY &lt;列名1&gt;,&lt;列名2&gt;,&lt;列名3&gt;,...    //分组的参考列

案例: 按照商品种类统计数据行数
SELECT shohin_bunrui,COUNT(*)
FROM Shohin
GROUP BY shohin_bunrui;

执行结果:
Shohin_bunrui|count
-------------+-----
衣服         |    2
办公用品         |    2
厨房用具         |    4
</code></pre><p>如上所示,使用GROUP BY 子句,会将表中的数据分为多个组进行处理;在GROUP BY子句中指定的列称为<strong>聚合键</strong> 或者 <strong>分组列</strong>.<br>由于能决定表的切分方式,所以是非常重要的列,当然GROUP BY子句也和SELECT子句一样,可以通过都好分割指定多列.</p>
<ul>
<li>法则3-6: GROUP BY就像是切分表的一把刀</li></ul>
<p>此外, GROUP BY 子句的书写位置也有严格要求,一定要卸载FROM语句(如果有WHERE子句,也要写在WHERE语句之后).如果无视子句的书写顺序,会报错</p>
<p>到目前为止我们暂定一个子句的<strong>书写顺序</strong><br><em>1.SELECT→2.FROM→3.WHERE→4.GROUP BY</em></p>
<ul>
<li>法则3-7: SQL子句顺序不能改变,也不能互相替换</li></ul>
<h4>聚合键中包含NULL的情况</h4>
<p>截下来我们将对进货单价(Shiire_tanka)作为聚合键对表进行切分.<br>在GROUP BY子句中指定进货单价:</p>
<pre><code>SELECT shiire_tanka,COUNT(*)
FROM Shohin
GROUP BY shiire_tanka;

执行结果:
Shohin_bunrui|count
-------------+-----    
         |    2
320         |    1
500         |    1
5000         |    1
2800         |    2
790         |    1
</code></pre><p>从上面的结果我们可以看出,当聚合键(分组列)中包含NULL时,也会将NULL作为一组特定的数据.</p>
<ul>
<li>法则3-8: 聚合键(分组列)中包含NULL时,在结果中会以<strong>&quot;不确定&quot;行(空行)</strong>的形式展示出来</li></ul>
<h4>使用WHERE子句时GROUP BY的执行结果</h4>
<p>在使用了GROUP BY子句的SELECT语句中,也可以正常使用WHERE子句,子句的书写顺序如前所述,语法结果如下:</p>
<pre><code>命令格式:
SELECT &lt;列名1&gt;,&lt;列名2&gt;,&lt;列名3&gt;,...  //查询的目标列
FROM &lt;表名&gt;
WHERE                                 //查询条件                            
GROUP BY &lt;列名1&gt;,&lt;列名2&gt;,&lt;列名3&gt;,...    //分组的参考列

案例:同时使用WHERE子句和GROUP BY 子句

SELECT shiire_tanka,COUNT(*)
FROM Shohin
WHERE shohin_bunrui = &#39;衣服&#39;
GROUP BY shiire_tanka;
</code></pre><p>上面案例的SELECT语句由于首先使用了WHERE子句对记录进行过滤,所以实际上作为聚合对象的记录如下表所示,只有2行:</p>
<table>
<thead>
<tr>
<th>shohin_bunrui(商品分类)</th>
<th>shohin_mei(商品名称)</th>
<th>shohin_id(商品编号)</th>
<th>hanbai_tanka(销售单价)</th>
<th>shiire_tanka(进货单价)</th>
<th>torokubi(登记日期)</th>
</tr>
</thead>
<tbody>
<tr>
<td>衣服</td>
<td>T恤衫</td>
<td>0001</td>
<td>1000</td>
<td>500</td>
<td>2009-09-20</td>
</tr>
<tr>
<td>衣服</td>
<td>运动T恤</td>
<td>0003</td>
<td>4000</td>
<td>2800</td>
<td>&nbsp;</td>
</tr>
</tbody>
</table>
<p>使用进货单价对这两条记录进行分组得到如下的执行结果:</p>
<pre><code>shiire_tanka|count
-------------+-----
500    | 1
2800    | 1
</code></pre><p>GROUP BY 和WHERE 并用时,SELECT 语句的<strong><em>执行顺序</em></strong>如下所示</p>
<p>FROM→WHERE→GROUP BY→SELECT</p>
<h4>与聚合函数和GROUP BY子句有关的常见错误</h4>
<ol>
<li><p>在SELECT子句中书写了多余的列</p>
<p> 在使用COUNT这样的聚合函数时,SELECT子句中的元素有严格的限制.实际上,使用聚合函数时,SELECT子句中只能存在以下三种元素:</p>
<ul>
<li>常数</li><li>聚合函数</li><li><p>GROUP BY子句中指定的列名(也就是组合键or分组列)</p>
<p>这里经常会出现的错误是<strong>把聚合键之外的列名字写在SELECT子句中</strong>.就会出错</p>
<p>比如下面这个错误代码:</p>
<pre><code>SELECT shohin_mei,shiire_tanka,COUNT(*)        //SELECT子句中出现了GROUP BY子句中没有的列名 shohin_mei
FROM Shohin
GROUP BY shiire_tanka;

执行就会报错:

[42803] ERROR: column &quot;shohin.shohin_mei&quot; must appear in the GROUP BY clause or be used in an aggregate function
  位置：8
</code></pre><p><em>其实仔细想一想就能明白,通过某个聚合键将表分组之后,结果中一行数据就代表一组.例如,使用进货单价将表进行分组以后,一行就代表了一个进货单价.问题就出在这里,聚合键和商品名</em><strong>并不一定是一对一的</strong>也可以想想执行顺序.<br>FROM→ WHERE→ GROUP BY→ HAVING→  SELECT→ ORDER BY</p>
</li></ul>
</li></ol>
<pre><code>    shohin_mei|shiire_tanka|count
    ----------+------------+-----
                 ┊
                2800       |   2
         ↑       ┊ 
    这里应该显示什么呢??

像这样与聚合键相对应的、同时存在多个值的列出现在SELECT子句中的情况,理论上是不存在的.
</code></pre><ol>
<li><p>在GROUP BY子句中书写了列的别名</p>
<p> 这也是一个非常常见的错误.在前面我们学过,SELECT 子句中的项目可以通过AS关键字来指定别名.但是在GROUP BY子句中是不能使用别名的.<br> 如下面就是一段错误的代码(在POSTGRESQL和MYSQL中不会报错,但是不建议使用)</p>
<pre><code> SELECT shohin_bunrui AS sb,COUNT(*)
 FROM shohin
 GROUP BY sb;
</code></pre><p> 造成这样的错误其实是因为SQL语句的执行顺序,FROM→WHERE→GROUP BY→SELECT;<strong>这段语句在POSTGRESQL和MYSQL中不会报错,但是不建议使用</strong></p>
<ul>
<li>法则3-10: 在GROUP BY子句中不能使用SELECT子句中定义的别名</li></ul>
</li><li><p>GROUP BY子句的结果能排序吗?</p>
<p> GROUP BY子句的结果通常都包含多行,有时可能是成千上万行.那么,这些结果究竟是按照什么顺序排列的呢?</p>
<p> 答案是:&quot;<strong>随机的!!!</strong>&quot;,这些结果默认显示顺序都是随机的.如果要按照某种特定顺序进行排列的话,需要在SELECT语句中进行指定.我们将在后面学习.</p>
<ul>
<li>法则3-11: GROUP BY子句结果的显示是无序的.</li></ul>
</li><li><p>在WHERE子句中使用聚合函数</p>
<p> 假如我们想要取出恰好包含2行数据的组该怎么办呢?满足要求的是办公用品和衣服<br> 表面处理方法:</p>
<pre><code> SELECT shohin_bunrui,COUNT(*)
 FROM shohin
 WHERE COUNT(*) = 2
 GROUP BY Shohin_bunrui;

 执行报错:    [42803] ERROR: aggregate functions are not allowed in WHERE
     位置：49    //提示聚合函数不能出现在WHERE子句中
</code></pre><p> 只有SELECT 和 HAVING子句(以及后面要学的ORDER BY子句)中能够使用COUNT等聚合函数.并且,HAVING子句可以非常方便的实现</p>
<ul>
<li>法则3-12: 只有SELECT子句和HAVING子句(以及ORDER BY子句)中能够使用聚合参数</li></ul>
</li></ol>
<h3>3-3 为聚合结果指定条件</h3>
<h4>HAVING子句</h4>
<p>下面我们就来取出&quot;聚合结果正好为2行的组&quot;;说到指定条件我们一般首先想到WHERE子句.但是WHERE子句只能指定记录(行)的条件,而不能用来指定组的条件(如,&quot;数据行数为2&quot;或者&quot;平均值为500&quot;等).<br>因此,对集合指定条件就需要使用其他的子句了.此时就可以用HAVING子句.</p>
<pre><code>语法结构:
SELECT &lt;列名1&gt;,&lt;列名2&gt;,&lt;列名3&gt;...
FROM &lt;表名&gt;
GROUP BY &lt;列名1&gt;,&lt;列名2&gt;,&lt;列名3&gt;...
HAVING &lt;分组结果对应的条件&gt;
</code></pre><p>注意: HAVING子句必须写在GROUP BY子句之后.其在DBMS内部的执行顺序也排在GROUP BY子句之后.<br>顺序为: SELECT→FROM→WHERE→GROUP BY→HAVING</p>
<ul>
<li>法则3-13: HAVING子句要写在GROUP BY之后.</li></ul>
<p>案例1:下面我们就来操作通过商品种类进行聚合分组后的结果,指定&quot;包含数据行数为2行&quot;这一条件的SELECT语句</p>
<pre><code>代码:
SELECT shohin_bunrui,COUNT(*)
FROM Shohin
GROUP BY shohin_bunrui
HAVING COUNT(*) = 2;

执行结果如下:
shohin_bunrui|count
-------------+-----
   衣服      |   2
  办公用品    |   2
</code></pre><p>案例2:选取销售单价的平均值大于等于2500元</p>
<pre><code>不使用HAVING子句的情况:
SELECT shohin_bunrui,AVG(hanbai_tanka)
FROM Shohin
GROUP BY shohin_bunrui;

执行结果:
shohin_bunrui|avg
-------------+-----
   衣服      |   2500
  办公用品    |   300
  厨房用具    |   2795

使用HAVING子句的情况:
SELECT shohin_bunrui,AVG(hanbai_tanka)
FROM shohin
GROUP BY shohin_bunrui
HAVING AVG(hanbai_tanka) &gt;= 2500;

执行结果为:
shohin_bunrui|avg
-------------+-----
   衣服      |   2500
  厨房用具    |   2795
</code></pre><h4>HAVING子句的构成要素</h4>
<p>HAVING子句和包含GROUP BY子句时的SELECT子句一样,能够使用的要素要有一定的限制.限制内容也是完全相同的,HAVING子句中能使用的三种要素:</p>
<pre><code>- 常数
- 聚合函数
- GROUP BY子句中指定的列名(聚合键或者分组列)
</code></pre><pre><code>代码:
SELECT shohin_bunrui,COUNT(*)
FROM Shohin
GROUP BY shohin_bunrui
HAVING COUNT(*) = 2;
这段代码中, COUNT(*) 是聚合函数,2是常数.完全满足上述要求.

反之,如果写成下面这个样子就会出错
SELECT Shohin_bunrui,COUNT(*)
FROM Shohin
GROUP BY shohin_bunrui
HAVING Shohin_mei = &#39;圆珠笔&#39;;

会报这个错误:
ERROR: column &quot;shohin.shohin_mei&quot; must appear in the GROUP BY clause or be used in an aggregate function
        列名&quot;shohin_mei&quot;必须包含在GROUP BY子句里,或者在聚合函数里使用
</code></pre><p> 为了更好理解我们可以把一次的聚合(就是使用GROUP BY子句时,SELECT子句聚合)之后结果类似下表,作为HAVING子句的起始点.</p>
<table>
<thead>
<tr>
<th>shohin_bunrui</th>
<th>COUNT(*)</th>
</tr>
</thead>
<tbody>
<tr>
<td> 厨房用具</td>
<td>4</td>
</tr>
<tr>
<td> 衣服</td>
<td>2</td>
</tr>
<tr>
<td> 办公用具</td>
<td>2</td>
</tr>
</tbody>
</table>
<p>聚合之后(如上表)结果中并不存在shohin_mei这个列,SQL当然也就无法为表中不存在的列设定条件啦.</p>
<h4>相对于HAVING子句,更适合卸写在WHERE子句中的条件</h4>
<p>我们发现有些条件既可以写在HAVING子句当中,也可以写在WHERE子句当中.这些条件就是<strong>聚合键所对应的条件</strong></p>
<p>比较下面两段代码:</p>
<pre><code>1st section:

SELECT shohin_bunrui,COUNT(*)
FROM Shohin
WHERE shohin_bunrui = &#39;衣服&#39;
GROUP BY shohin_bunrui;

执行结果:
shohin_bunrui|count
-------------+-----
   衣服      |   2

2nd section:

SELECT Shohin_bunrui,COUNT(*)
FROM Shohin
GROUP BY shohin_bunrui
HAVING Shohin_bunrui = &#39;衣服&#39;;

执行结果也是:
shohin_bunrui|count
-------------+-----
   衣服      |   2
</code></pre><p>虽然条件分别写在WHERE子句和HAVING子句当中,但是条件的内容和返回的结果完全相同.因此,大家可能觉得两种书写方式都没问题<br>但是作者认为<strong>聚合键所对应的条件还是应该书写在WHERE子句当中</strong>;原因有两个:</p>
<ol>
<li><p>根本原因是WHERE子句和HAVING子句的作用不同,HAVING子句是用来指定&quot;组&quot;的条件的.因此,&quot;行&quot;所对应的条件还是应该写在WHERE子句当中.这样一来书写出的SELECT语句不但可以分清两者格子的功能,理解起来也更容易.</p>
<pre><code> WHERE子句 = 指定行所对应的条件
 HAVING子句 = 指定组所对应的条件
</code></pre></li><li><p>其次就是HAVING子句和WHERE子句的执行速度<br> 进行聚合操作时,DBMS内部就会进行排序处理.排序处理会大大增加机器的负担,即所谓的高负处理.因此,只有尽可能减少排序的行数,才能增加处理速度;通过WHERE子句指定条件时,由于排序之前就对数据进行了过滤,所以能够减少排序的数据量.<br> 但是HAVING子句是在排序后才对数据进行分组的,因此与在WHERE子句中指定条件比起来,需要排序的数据量就会多得多.<br> 另外WHERE子句更具速度优势的另一个理由是,可以对WHERE子句指定条件所对应的列创建索引,这样也可以大幅提高处理速度.创建索引是一种非常普遍的提高DBMS性能的方法,效果也十分明显,对WHERE子句来说也是十分有利</p>
</li></ol>
<h3>3-4对查询结果进行排序</h3>
<h4>ORDER BY子句</h4>
<pre><code>ORDER BY 语句格式:
SELECT &lt;列名1&gt;,&lt;列名2&gt;,&lt;列名3&gt;...
FROM &lt;表名&gt;
ORDER BY &lt;排序基准列1&gt;,&lt;排序基准列2&gt;,&lt;排序基准列3&gt;...

案例: 按照销售单价由低到高(升序)进行排列
SELECT Shohin_id,shohin_bunrui,hanbai_tanka,shiire_tanka
FROM Shohin
ORDER BY hanbai_tanka;

执行结果:
Shohin_id,shohin_bunrui,hanbai_tanka,shiire_tanka
0008        办公用品           100    
0006        厨房用具           500    
0002        办公用品           500         320
0007        厨房用具           880           790
0001        衣服           1000           500
0004        厨房用具           3000           2800
0003        衣服           4000           2800
0005        厨房用具           6800           5000
</code></pre><p>不论何种情况,ORDER BY子句都要写在SELECT语句的末尾.这是因为对数据进行排序的操作必须在结果即将返回时执行.ORDER BY 子句中书写名称为<strong>排序键</strong>;<br>该子句和其他子句的执行顺序关系如下:<br>SELECT 子句→ FROM子句→ WHERE子句→ GROUP BY子句→ HAVING子句→ ORDER BY子句</p>
<h4>指定升序或降序</h4>
<p>升序ASC(Ascendent) 降序DESC(Descendent)</p>
<p>案例: 按照销售单价由高到低(降序)排列</p>
<pre><code>SELECT shohin_id,shohin_mei,shohin_bunrui,hanbai_tanka,shiire_tanka,torokubi
FROM Shohin
ORDER BY hanbai_tanka DESC;

执行结果:
shohin_id,shohin_mei,shohin_bunrui,hanbai_tanka,shiire_tanka,torokubi
0005    高压锅    厨房用具    6800    5000    2009-01-15
0003    运动T恤    衣服    4000    2800    
0004    菜刀    厨房用具    3000    2800    2009-09-20
0001    T恤    衣服    1000    500    2009-09-20
0007    擦菜板    厨房用具    880    790    2008-04-28
0002    打孔器    办公用品    500    320    2009-09-11
0006    叉子    厨房用具    500        2009-09-20
0008    圆珠笔    办公用品    100        2009-11-11
</code></pre><ul>
<li>法则3-16: 升序用ASC(Ascendent) 降序用(Descendent),未指定ORDER BY子句中排列顺序时默认使用升序进行排列;但是先比左边排序键,左边排序键一样的时候再比第二个排序键</li></ul>
<h4>指定多个排序键</h4>
<p>通过上面我们对销售单价进行升序排列SELECT语句的执行结果,我们发现销售单价为500的商品有两件.相同价格的商品的顺序没有特地指定,或者说是随即排序的.如果想要对该顺序的商品进行更细致的排序的话,就需要再添加一个<strong>排序键</strong>,</p>
<p>在此我们以添加商品序号的升序为例:</p>
<pre><code>SELECT shohin_id,shohin_mei,hanbai_tanka,shiire_tanka
FROM Shohin
ORDER BY hanbai_tanka,shohin_id;

执行的结果:
0008    圆珠笔    100    
0002    打孔器    500    320
0006    叉子    500    
0007    擦菜板    880    790
0001    T恤    1000    500
0004    菜刀    3000    2800
0003    运动T恤    4000    2800
0005    高压锅    6800    5000
</code></pre><p>这样一来,就可以在ORDER BY 子句中同时指定多个排序键了.会优先使用左侧的键,如果该列存在相同值的话,会接着参考右侧的键.当然,也可以使用3个以上的键.</p>
<h4>NULL的顺序</h4>
<p>当我们使用销售单价(shiire_tanka)列作为排序键,圆珠笔和叉子对应的值为NULL.究竟NULL会按什么顺序来排呢?</p>
<pre><code>SELECT shohin_id,shohin_mei,shohin_bunrui,hanbai_tanka,shiire_tanka
FROM Shohin
ORDER BY shiire_tanka;
</code></pre><p>结果发现:<strong>NULL会汇集在开头或者结尾</strong></p>
<ul>
<li>法则3-17: 排序键中有NULL时,会在开头或末尾进行汇总</li></ul>
<h4>在排序键中使用显示用别名</h4>
<pre><code>案例代码:
SELECT  Shohin_id AS id,shohin_mei,shohin_bunrui,hanbai_tanka AS ht,shiire_tanka
FROM Shohin
ORDER BY ht,id;

执行结果:
0008    圆珠笔    办公用品    100    
0002    打孔器    办公用品    500    320
0006    叉子    厨房用具    500    
0007    擦菜板    厨房用具    880    790
0001    T恤    衣服    1000    500
0004    菜刀    厨房用具    3000    2800
0003    运动T恤    衣服    4000    2800
0005    高压锅    厨房用具    6800    5000
</code></pre><p>不能在GROUP BY中使用的别名,在ORDER BY中却可以使用,这是因为SQL语句在DMBS内部的执行顺序决定的<br>FROM→ WHERE→ GROUP BY→ HAVING→ SELECT→ ORDER BY<br>这只是一个粗略的总结.一定要记住SELECT子句是<strong>在GROUP BY子句之后,ORDER BY之前</strong>.因此在执行GROUP BY子句是,SELECT语句定义的别名无法被识别,对于在SELECT子句之后执行的ORDER BY子句却可以识别.</p>
<ul>
<li>法则3-18: 在ORDER BY子句中可以使用SELECT子句中定义的别名.</li></ul>
<h4>ORDER BY子句中可以使用的列</h4>
<p>ORDER BY子句中可以使用存在于表中,但是并不包含在SELECT子句中的列</p>
<pre><code>SELECT Shohin_bunrui,hanbai_tanka,shiire_tanka
FROM Shohin
ORDER BY shohin_id;

执行结果:
衣服    1000    500
办公用品    500    320
衣服    4000    2800
厨房用具    3000    2800
厨房用具    6800    5000
厨房用具    500    
厨房用具    880    790
办公用品    100
</code></pre><p>除此之外,还可以使用聚合参数</p>
<pre><code>代码:
SELECT Shohin_bunrui,COUNT(*)
FROM shohin
GROUP BY shohin_bunrui
ORDER BY COUNT(*) DESC;

执行结果:
厨房用具    4
衣服    2
办公用品    2
</code></pre><ul>
<li>法则:3-19: 在ORDER BY 子句中可以使用SELECT子句中未使用的列和聚合函数.</li></ul>
<h4>不要使用列编号</h4>
<p>在ORDER BY子句中,还可以使用在SELECT子句中出现的列所对应的编号.列编号是指<strong><em>SELECT子句中的列按照从左到右的顺序进行排列时所对应的编号</em></strong>.因此下面两段代码含义是相同的</p>
<pre><code>1st Section
SELECT shohin_id,shohin_mei,hanbai_tanka,shiire_tanka
FROM Shohin
ORDER BY hanbai_tanka DESC,shohin_id;

2nd Section
SELECT shohin_id,shohin_mei,hanbai_tanka,shiire_tanka
FROM Shohin
ORDER BY 3 DESC,1;
</code></pre><p>但是<strong>这种做法是不被推荐的</strong>,原因如下:</p>
<ol>
<li><strong>代码阅读起来比较难</strong>,使用编号时,如果只看ORDER BY子句是无法知道当前是按照哪一列进行排序的,只能去SELECT子句的列表中按顺序进行确认,当代码量大的时候,就很麻烦了.</li><li><p>根本问题,SQL-92中已经明确了<strong>该排序功能将来会被删除</strong>.</p>
</li><li><p>法则3-20: 在ORDER BY不要使用列编号.</p>
</li></ol>
<h2>第四章 数据更新</h2>
<h3>4-1 数据的插入(INSERT语句的使用方法)</h3>
<p>在前面我们知道了用来创建表的CREATE TABLE语句,通过CREATE TABLE语句创建出来的表,可以将其比作一个空空如也的箱子.只有把数据装到这个箱子后,它才能称为数据库.用来装入数据库的SQL语句就是INSERT(插入)<br>INSERT(插入)的流程</p>
<p>①CREATE TABLE语句只负责创建表,但是创建出的表中没有数据</p>
<p>②通过INSERT语句插入数据</p>
<p>③向表中插入数据</p>
<p>下面我们创建一个 ShohinIns的表</p>
<pre><code>CREATE TABLE ShohinIns1
(shohin_id CHAR(4) NOT NULL,
shohin_mei VARCHAR(100) NOT NULL,
shohin_bunrui VARCHAR(100) NOT NULL,
hanbai_tanka INTEGER     ,
shiire_tanka INTEGER    ,
torokubi DATE    ,
PRIMARY KEY (shohin_id));
</code></pre><p>这里只是创建了一个表,并没有插入数据,接下来,我们就想ShohinIns表中插入数据.</p>
<h4>INSERT语句的基本语法</h4>
<p>INSERT语句的基本语法</p>
<pre><code>INSERT INTO &lt;表名&gt;(列1,列2,列3...) VALUES (值1,值2,值3...);
</code></pre><p>假如我们要向ShohinIns表中插入一行数据,各列值如下:</p>
<pre><code>INSERT INTO ShohinIns(shohin_id,shohin_mei,shohin_bunrui,hanbai_tanka,shiire_tanka,torokubi)
VALUES (&#39;0001&#39;,&#39;T恤衫&#39;,&#39;衣服&#39;,1000,500,&#39;2009-09-20&#39;);
</code></pre><p>由于Shohin_id列(商品编号) 和shohin_mei列(商品名称)是字符型,所以插入的数据需要用单引号括起来.日期型的torokubi(登记日期)也是如此.</p>
<p>列名和值用逗号隔开,分别在( )内,这种形式称为清单.代码清单中的INSERT语句包含下面两个清单:</p>
<ol>
<li>列清单 → (shohin_id,shohin_mei,shohin_bunrui,hanbai_tanka,shiire_tanka,torokubi)</li><li>值清单 → (&#39;0001&#39;,&#39;T恤衫&#39;,&#39;衣服&#39;,1000,500,&#39;2009-09-20&#39;)</li></ol>
<p>当然,表名后面的列清单和VALUES子句中列的数量必须保持一致.列数不一致时会出错,无法插入数据.</p>
<p>此外,原则上,执行一次INSERT语句会插入一行数据,因此插入多行时,通常需要循环执行所需行数次的INSERT语句</p>
<ul>
<li>法则4-1: 原则上执行一次INSERT语句会插入一行数据</li></ul>
<h4>多行INSERT</h4>
<p>通常INSERT 和多行INSERT</p>
<pre><code>-- 通常INSERT
INSERT INTO ShohinIns VALUES (&#39;0002&#39;,&#39;打孔器&#39;,&#39;办公用品&#39;,500,320,&#39;2009-09-20&#39; );
INSERT INTO ShohinIns VALUES (&#39;0003&#39;,&#39;运动T恤&#39;,&#39;衣服&#39;,4000,2800,NULL );
INSERT INTO ShohinIns VALUES (&#39;0004&#39;,&#39;菜刀&#39;,&#39;厨房用具&#39;,3000,2800,&#39;2009-09-20&#39; );

-- 多行INSERT
INSERT INTO ShohinIns VALUES (&#39;0002&#39;,&#39;打孔器&#39;,&#39;办公用品&#39;,500,320,&#39;2009-09-20&#39; );
                             (&#39;0003&#39;,&#39;运动T恤&#39;,&#39;衣服&#39;,4000,2800,NULL );
                             (&#39;0004&#39;,&#39;菜刀&#39;,&#39;厨房用具&#39;,3000,2800,&#39;2009-09-20&#39; );
</code></pre><p>该语法很容易理解,并且减少了书写语句的数量,很方便,但是使用该语句时,请注意一下几点:</p>
<p>首先,INSERT语句书写内容及插入的数据是否正确.当然此时都会发生INSERT错误,但是由于是多行插入,和特定的单一行INSERT相比,想要找出哪个地方出错了,就变得十分困难</p>
<p>其次,该多行INSERT的语法并不适合所有的DBMS.该多行语法<strong>不适用于ORACLE</strong>.</p>
<h4>列清单的省略.</h4>
<p>对表进行全列INSERT的时候,可以省略表名后面的列清单.这时VALUES子句的值会默认按照从左到右的顺序赋予每一列.因此,下面的两个INSERT语句会插入同样的数据:</p>
<pre><code>-- 包含列清单:
INSERT INTO ShohinIns(shohin_id,shohin_mei,shohin_bunrui,hanbai_tanka,shiire_tanka,torokubi)
VALUES (&#39;0001&#39;,&#39;T恤衫&#39;,&#39;衣服&#39;,1000,500,&#39;2009-09-20&#39;);

-- 不包含列清单:
INSERT INTO ShohinIns VALUES (&#39;0001&#39;,&#39;T恤衫&#39;,&#39;衣服&#39;,1000,500,&#39;2009-09-20&#39;);
</code></pre><h4>插入NULL</h4>
<p>INSERT 语句中想给某一列赋予NULL值时,可以直接在VALUES子句的值清单中写入NULL,但是想要插入NULL的列一定不能设置NOT NULL约束.想设置了NOT NULL约束的列中插入NULL时,INSERT语句会出错,数据插入失败.<br>插入失败是指希望通过INSERT语句插入的数据无法正常插入到表中,但之前已经插入的数据并不会被破坏.<br>不仅INSERT,DELET和UPDATE等更新语句也一样.SQL语句执行失败时都不会对表中数据造成影响.</p>
<h4>插入默认值</h4>
<p>我们还可以向表中插入默认值(初始值).默认值的设定,通过在创建表的CREATE TABLE语句中设置<strong>DEFAULT 约束</strong>来实现.</p>
<pre><code>在创建表时设定默认值
CREATE TABLE ShohinIns
(shohin_id  CHAR(4) NOT NULL,
 hanbai_tanka INTEGER DEFAULT 0,    --销售单价默认值设定为0
)
</code></pre><p>通过显示方法设定默认值</p>
<pre><code>INSERT INTO ShohinIns (shohin_id,shohin_mei,shohin_bunrui,hanbai_tanka,shiire_tanka,torokubi)
VALUES (&#39;0007&#39;,&#39;擦菜板&#39;,&#39;厨房用具&#39;,DEFAULT,790,&#39;2009-04-28&#39;);
</code></pre><p>这样一来,RDBMS就会在插入记录是,自动把默认值赋给对应的列.<br>我们可以使用SELECT语句来确认通过INSERT语句插入的数据行</p>
<pre><code>SELECT * FROM shohinins WHERE shohin_id = &#39;0007&#39;;
</code></pre><p>因为hanbai_tanka列(销售单价)默认值为0,所以hanbai_tanka的列被赋予了值0.</p>
<p>通过隐示方法插入默认值<br>插入默认值时也可以不使用DEFAULT关键字.只要在列清单和VALUES中省略设定了默认值的列就可以了</p>
<pre><code>INSERT INTO ShohinIns (shohin_id,shonhin_mei,shohin_bunrui,shiire_tanka,torokubi)    //在列清单中省略了hanbai_tanka.
VALUES(&#39;0007&#39;,&#39;擦菜板&#39;,&#39;厨房用品&#39;,790,&#39;2009-09-20&#39;)    //在值清单中也省略了hanbai_tanke列的值.
</code></pre><p>这样也可以给hanbai_tanka赋默认值 0.</p>
<p>在实际情况中.我们最好使用显示方法来设置默认值.因为这样更容易理解.</p>
<p>说到省略名,还有一点要说明一下.如果省略了<strong><em>没有设定默认值的列</em></strong>的话,<strong><em>该列的值</em></strong>就会被设定为NULL.因此如果省略的是设置了NOT NULL约束的列的话,INSERT语句就会出错.</p>
<ul>
<li>法则4-2: 省略INSERT语句中的列名,就会自动设定为该列的默认值(没有默认值时会设定为NULL).</li></ul>
<h4>从其他表中复制数据</h4>
<p>我们新建一张ShohinCopy表,要求它的结构和之前的Shohin表完全一样,只是更改一下表名而已.</p>
<pre><code>CREATE TABLE ShohinCopy
( shohin_id    CHAR(4)  NOT NULL,
 shohin_mei VARCHAR(100) NOT NULL,
 shohin_bunrui VARCHAR(100) NOT NULL,
 hanbai_tanka INTEGER ,
 shiire_tanka INTEGER    ,
 torokubi DATE    ,
 PRIMARY KEY (shohin_id));        //完成ShohinCopy表的创建

-- 将Shohin表里的数据复制到ShohinCopy表中:
INSERT INTO ShohinCopy (shohin_id,shohin_mei,shohin_bunrui,hanbai_tanka,shiire_tanka,torokubi)
SELECT shohin_id,shohin_mei,shohin_bunrui,hanbai_tanka,shiire_tanka,torokubi
FROM shohin;
</code></pre><p>执行该<strong><em>INSERT...SELECT</em></strong>语句时,如果原来Shohin表中有8行数据,那么ShohinCopy中也会插入完全相同的8行数据.当然Shohin表中原有数据是不会发生改变的.因此INSERT...SELECT语句可以在需要进行数据备份时使用.</p>
<p><strong>多重多样的SELECT语句</strong></p>
<p>在INSERT语句中的SELECT语句,也可以使用WHERE子句或者GROUP BY等子句等.目前为止学到的各种SELECT语句也都可以使用(<strong>但是,即便指定了ORDER BY子句也没有任何意义,因为无法保证表内部记录的排列顺序</strong>).对关联表之间存取数据来说,非常方便.<br>下面我们试试包含GROUP BY子句的SELECT语句进行INSERT.</p>
<pre><code>创建ShohinBunrui表:
CREATE TABLE ShohinBunrui
( shohin_bunrui VARCHAR(32)  NOT NULL,
sum_hanbai_tanka    INTEGER     ,
sum_shiire_tanka    INTEGER     ,
PRIMARY KEY (shohin_mei));
</code></pre><p>该表是用来存储根据商品种类(Shohin_bunrui)计算出来销售单价合计值以及进货单价合计值的表.我们下面用INSERT...SELECT语句从Shohin表中选取出数据插入到Shohin_bunri中吧</p>
<pre><code>INSERT INTO shohin_bunrui (shohin_bunrui,sum_hanbai_tanka,sum_shiire_tanka)
SELECT shohin_bunrui,sum(hanbai_tanka),sum(shiire_tanka)
FROM Shohin
GROUP BY shohin_bunrui;        从shohin中取到值并插入到shohin\_bunrui中

SELECT * FROM shohin_bunrui    //确认插入的数据行

执行结果:
衣服    5000    3300
办公用品    600    320
厨房用具    11180    8590
</code></pre><ul>
<li>法则4-3: INSERT语句的SELECT语句中,可以使用WHERE子句或者GROUP BY子句等任何SQL语法(但是使用ORDER BY 子句并不会产生任何效果)</li></ul>
<h3>4-2 数据的删除(DELETE语句的使用方法)</h3>
<h4>DROP TABLE语句和DELETE语句</h4>
<p>删除数据的方法,大体可分为以下两种:</p>
<ol>
<li><strong>DROP TABLE语句</strong>可以将表完全删除;</li><li><strong>DELETE语句</strong>会留下表(容器),而删除表中的全部数据.</li></ol>
<p>1中的DROP TABLE语句会完全删除整张表,因此删除之后再向插入数据,就得使用CREATE TABLE重新创建一张表了.<br>反之,2中的DELETE语句在删除数据(行)的同时会保留数据表,因此只需要通过INSERT语句就可以再次向表中插入数据.<br>不管使用那种方法删除数据时都要慎重,一旦发生误删,想要恢复数据,都十分困难.</p>
<h4>DELETE语句的基本语法</h4>
<pre><code>保留数据表,清空全部数据的基本语法:
DELETE FROM &lt;表名&gt;;

案例:清空ShohinCopy表内数据,保留ShohinCopy表
DELETE FROM ShohinCopy;
</code></pre><p>如果DELETE语句中忘了写FROM,而是写成了DELETE &lt;表名&gt;,或者写了多余的列名,都会出错;其实从英语语法角度来说也是很好理解的.<br>要加FROM是因为DELETE(INSERT,或者UPDATE)操作的对象都是表内的数据,而不是表本身,所以中间要加<strong>介词</strong><br>而写了多余的列名错误是由于DELETE语句的对象是行而不是列,所以DELETE语句无法删除部分列的数据.</p>
<ul>
<li>法则4-4: DELETE语句的删除对象并不是表或者列,而是记录(行).</li></ul>
<h4>指定删除对象的DELETE语句(搜索型DELETE)</h4>
<p>想要删除部分数据行时,可以像SELECT语句那样使用WHERE子句指定删除条件.这种指定了删除对象的DELETE语句称为&#39;搜索型DELETE&#39;,虽然&quot;搜索型DELETE&quot;是正是用语,但实际上这种说法并不常用,而是简单的称作DELETE语句</p>
<pre><code>删除部分数据行的搜索型DELETE语法结构:
DELETE FROM &lt;表名&gt;
WHERE;

案例:删除销售单价(hanbai_tanka)大于等于4000的数据
DELETE FROM shohincopy
WHERE hanbai_tanka &gt;=4000
</code></pre><p>WHERE子句的书写方式和前面介绍的SELECT完全一样.我们用SELECT语句确认一下</p>
<pre><code>SELECT * FROM Shohincopy;
发现结果只剩下6行,被删除了两行
</code></pre><ul>
<li>法则4-5: 可以通过WHERE子句指定对象条件来删除部分数据.</li></ul>
<h4>拓展:删除和时期(DELETE 和 TRUNCATE)</h4>
<p>标准SQL中用来从表中删除数据的只有DELETE语句.但是很多数据库产品中还有另外一种被称为TRUNCATE的语句.<br>TRUNCATE是舍弃的意思,具体用法为: <code>TRUNCATE &lt;表名&gt;</code><br>与DELETE不同的是,TRUNCATE只能删除表中的全部数据,是清空的意思,它并他不能通过WHERE子句来指定条件删除部分数据.也正式因为它不能具体地控制删除对象,所以其处理速度比DELETE要快很多.实际上DELETE在DML语句中也是属于处理时间比较长的,因此需要删除全部数据行的时候,使用TRUNCATE可以缩短执行时间.</p>
<h3>4-3 数据的更新(UPDATE语句的使用方法)</h3>
<p>使用INSERT语句向表中插入数据之后,有时却想要再更改数据.比如,&quot;将商品的销售单价登记错了&quot;等等.这时并不需要把数据删除之后再重新插入,只要用UPDATE语句就可以改变表中的数据了.<br>和INSERT语句、DELETE语句一样，UPDATE语句也属于DML语句。通过执行该语句，我们就可以改变表中的数据了。其基本语法如下：</p>
<pre><code>UPDATE &lt;表名&gt;
SET &lt;列名&gt; = &lt;表达式&gt;;

案列:将ShohinCopy表中的商品登记日期改成&quot;2009-10-10&quot;
UPDATE ShohinCopy
SET torokubi = &#39;2009-10-10&#39;

执行结果如下:
0001    T恤    衣服    1000    500    2009-10-10
0002    打孔器    办公用品    500    320    2009-10-10
0004    菜刀    厨房用具    3000    2800    2009-10-10
0006    叉子    厨房用具    500        2009-10-10
0007    擦菜板    厨房用具    880    790    2009-10-10
0008    圆珠笔    办公用品    100        2009-10-10
</code></pre><p>此时,连登记日期原本为NULL 的数据行(运动T恤)的值也更新为2009-10-10了.</p>
<h4>指定条件的UPDATE(搜索型UPDATE)</h4>
<p>更新数据也可以像DELETE语句那样使用WHERE子句.这种指定更新对象的UPDATE语句称为搜索型UPDATE语句.</p>
<pre><code>语法格式:
UPDATE &lt;表名&gt;
SET &lt;列名&gt; = &lt;表达式&gt;
WHERE &lt;条件&gt;;

案例:将商品种类(shohin_bunrui)为&#39;厨房用具&#39;的记录的销售单价(hanbai_tanka),更新为原来的10倍:
UPDATE ShohinCopy
SET hanbai_tanka = hanbai_tanka * 10
WHERE shohin_bunrui = &#39;厨房用具&#39;;
</code></pre><p>该语句通过WHERE子句shohin_bunrui=&#39;厨房用具&#39;将更新对象限定为3行,然后通过SET子句的表达式hanbai_tanka * 10将原来的单价扩大了10倍.SET子句中复制表达式的右边不仅可以是单纯的值,也可以是包含列的表达式.</p>
<h4>使用NULL进行更新</h4>
<p>使用UPDATE也可以将列更新为NULL(该更新俗称<strong>NULL清空</strong>),此时只要将赋值表达式右边的值直接写为NULL即可.</p>
<pre><code>如:
UPDATE ShohinCopy
SET torokubi = NULL
WHERE shohin_id = &#39;0008&#39;;

--确认更新内容:
SELECT * FROM shohincopy ORDER BY shohin_id;

执行结果为:
0001    T恤    衣服    1000    500    2009-10-10
0002    打孔器    办公用品    500    320    2009-10-10
0004    菜刀    厨房用具    3000    2800    2009-10-10
0006    叉子    厨房用具    500        2009-10-10
0007    擦菜板    厨房用具    880    790    2009-10-10
0008    圆珠笔    办公用品    100
</code></pre><p>和INSERT语句一样,UPDATE语句也可以将NULL作为一个值来使用,但是只有未设置NOT NULL约束和主键约束的列才可以清空为NULL,如果将设置了上述约束的列更新为NULL,这执行结果会报错.</p>
<ul>
<li>法则4-6: 使用UPDATE语句可以将值清空为NULL(但只限于未设置NOT NULL约束的列).</li></ul>
<h4>多列更新</h4>
<p>UPDATE语句的SET子句支持同时将多个列作为更新对象.如我们要将厨房用具的销售单价(hanbai_tanka)更新为原来的10倍,如果同时想将进货单价(shiire_tanka)更新为原来的一半,该怎么做呢?</p>
<pre><code>当然我们可以逐步实现:
-- 先更新销售单价
UPDATE shohincopy,
SET hanbai_tanka =  hanbai_tanka * 10
WHERE shohin_bunrui = &#39;厨房用具&#39;;

-- 再更新进货单价:
UPDATE shohincopy
SET shiire_tanka =  shiire_tanka / 2
WHERE shohin_bunrui = &#39;厨房用具&#39;;
</code></pre><p>上面的方法虽然也能正确地更新数据,但是执行两次UPDATE语句不但有些浪费,而且增加了SQL语句的及数量.我们可以将其合并为一条UPDATE来处理,合并的方法有两种:</p>
<pre><code>方法1:　使用逗号将列分隔开
UPDATE ShohinCopy
SET hanbai_tanka = hanbai_tanka * 10,
    shiire_tanka = shiire_tanka / 2
WHERE shohin_bunrui = &#39;厨房用具&#39;;

方法2:将列用()括起来
UPDATE ShohinCopy
SET (hanbai_tanka,shiire_tanka) = (hanbai_tanka * 10, shiire_tanka / 2)
WHERE shohin_bunrui = &#39;厨房用具&#39;;
</code></pre><p>方法1和方法2的执行结果是一样的,但是需要注意的是方法1是所有DBMS都可以使用,方法2有些DBMS是无法使用的.因此<strong>建议使用第一种方法</strong>.</p>
<h3>4-4事务(TRANSACTION)</h3>
<h4>什么是事务</h4>
<p>事务就是<strong>需要在同一个处理单元中执行的一系列更新处理的集合</strong><br>比如,将&quot;运动T恤的销售单价降价1000元&quot;、&quot;将T恤的销售价格上调1000元&quot;;这时的事务就是有如下两条更新处理所组成</p>
<pre><code>⑴ 将运动T恤的价格降价1000元
UPDATE ShohinCopy
SET hanbai_tanka = hanbai_tanka -1000
WHERE shohin_mei = &#39;运动T恤&#39;;

⑵ 将T恤的价格上涨1000元
UPDATE shohincopy
SET hanbai_tanka = hanbai_tanka + 1000
WHERE shohin_mei = &#39;T恤&#39;;
</code></pre><p>上述⑴和⑵的操作一定要作为同一个处理单元执行.遇到这种需要在同一个处理单元中执行一系列更新操作的情况,一定要使用事务来进行处理.</p>
<ul>
<li>法则4-7: 事务是需要在同一个处理单元中执行的一系列更新处理的集合,一个事务中包含多少歌更新或者包含那些处理,DBMS中并没有固定的标准,而是根据用户的要求决定的.</li></ul>
<h4>创建事务</h4>
<pre><code>事务的语法:

事务开始语句;

    DML语句1;
    DML语句2;
    DML语句3;
       ┆
事务结束语句(COMMIT或者ROLLBACK);
</code></pre><p>使用事务开始语句和事务结束语句将一系列DML语句(INSERT/UPDATE/DELETE语句)括起来,就实现了一个事务处理.<br>这个时候需要特别注意的是事务的开始语句,实际上在标准SQL中并没有定义事务的开始语句,而是由哥哥DBMS自己来定义的比较有代表性的如下:</p>
<ul>
<li><p>SQL SERVER、Postgresql</p>
<p>  BEGIN TRANSACTION</p>
</li><li><p>MYSQL</p>
<p>  START TRANSACTION</p>
</li><li><p>Oracle、DB2</p>
<p>  无</p>
</li></ul>
<p>在POSTGRESQL中上面那两个UPDATE(⑴和⑵)创建出的事务如下:</p>
<pre><code>BEGIN TRANSACTION;

UPDATE ShohinCopy
SET hanbai_tanka = hanbai_tanka -1000
WHERE shohin_mei = &#39;运动T恤&#39;;
UPDATE shohincopy
SET hanbai_tanka = hanbai_tanka + 1000
WHERE shohin_mei = &#39;T恤&#39;; 

COMMIT;
</code></pre><p>反之,事务的结束需要用户明确地给出指示.事务结束的指令有如下两种:</p>
<ul>
<li><p>COMMIT--提交处理</p>
<p>  COMMIT是提交事务包含的全部更新处理的结束指令.相当于文件处理中的覆盖保存.一旦提交,就无法恢复到事务开始钱的状态了,因此,在提交之前一定要确认是否真的需要进行这些更新</p>
<p>  COMMIT 流程: (1) 事务开始语句→ (2) 执行更新DML → (3) 执行COMMIT ((2)中所有的更新全部都被反应到数据库中)</p>
<p>  万一由于误操作提交了包含错误更新的事务,就只能重新回到重新建表,重新插入数据这样的繁琐的老路上了.由于可能会造成数据无法恢复的后果,请务必注意.</p>
<ul>
<li>法则4-8: 虽然我们可以不清楚事务开始的时点,但是在事务结束时一定要仔细进行确认.</li></ul>
</li><li><p>ROLLBACK--取消处理</p>
<p>  ROLLBACK是取消事务包含的全部更新处理的结束指令.相当于文件处理中的放弃保存.一旦回滚,数据库就会回复到事务开始之前的状态.通常回滚并不会像提交那样造成大规模的数据损失.<br>  ROOLBACK流程: (1) 事务开始语句 → (2)执行更新语句DML → (3) 执行ROLLBACK (结束后的状态:和(1)执行前相同)</p>
</li></ul>
<h4>事务处理合适开始</h4>
<p>几乎所有的数据库产品的事务都无需开始指令.因为大部分情况下,事务在数据库连接建立时就已经悄悄开始了,并不需要用户再明确发出开始指令.</p>
<p>像这样不使用指令而悄悄开始事务的情况下,应该如何区分各个事务呢?通常会有如下两种情况:</p>
<p>A. 每条SQL语句就是一个事务(自动提交模式: PostgreSQL中所有的指令语句都在事务内执行,即使不执行BEGIN,这些命令语句也会在执行时悄悄被括在BEGIN和COMMIT(如果成功的话)之间)<br>B. 直到用户执行COMMIT或者ROLLBACK为止算作一个事务.</p>
<h4>ACID特性</h4>
<ul>
<li><p>原子性(Atomicity)<br>  是指在事务结束时,其中所包含的更新处理要么全部执行,要么全不执行的特性.上面的例子中,事务结束时,是不可能出现运动T恤的价格下降了,T恤的价格没有上涨的情况.该事务的结束的状态,要么两者都执行了(COMMIT),要么两者都未执行(ROLLBACK).</p>
</li><li><p>一致性(Consistency)<br>  是指事务中包含的处理,要满足数据库提前设置的约束,如主键约束或者NOT NULL约束等.例如,设置了NOT NULL约束的列是不能更新为NULL的,试图插入违反主键约束的记录就会出错,无法执行.对事务来说,这些不合法的SQL就会被回滚.<br>  也就是说这些SQL处理会被取消不会执行;而符合条件的SQL就会被执行.</p>
</li><li><p>隔离性(Isolation)<br>  指的是保证不同事务之间互不干扰的特性.该特性保证了事务之间不会互相嵌套.此外,在某个事务中进行的更改,在该事务结束之前,对其他事务而言是不可见的.因此,即使某个事务向表中添加了记录,在没有提交之前,其他事务是看不到新添加的记录的.</p>
</li><li><p>持久性(Durability)<br>  持久性也可以称为耐久性,指的是事务(不论是提交还是回滚),一旦结束,DBMS会保证该时点的数据状态得以保存的特性.即使由于系统故障导致数据丢失,数据库也一定能通过某种手段进行恢复,其中最常见的就是将事务的执行记录保存到硬盘等存储介质中(日志),发生故障时,可以通过日志回复到故障发生前的状态</p>
</li></ul>
<h2>第五章 复杂查询</h2>
<h3>5-1 视图</h3>
<h4>视图和表</h4>
<p>视图究竟是什么?用一句话来概述:就是&quot;从SQL的角度来看视图就是一张表&quot;. 实际上在SQL语句中并不需要区分那些是表,那些是视图.只需要知道在更新时它们之间存在一些不同就可以了.<br>它们的区别只有一个,那就是&quot;是否保存了实际的数据&quot;;通常我们在创建表时,会通过INSERT语句将数据保存到数据库之中.而数据库中的数据实际上会被保存到计算机的存储设备(通常是硬盘)中.因此,我们通过SELECT语句查询数据时,实际上就是从存储设备(硬盘)中读取数据,进行各种计算后,再将结果返回给用户这样的一个过程;但是使用视图时并不会将数据保存到存储设备之中,而且也<strong>不会将数据保存到其他任何地方</strong>.实际上视图保存的是SELECT语句.我们从视图中读取数据时,视图会在内部执行该SELECT语句并创建出一张临时表.</p>
<p>视图的有点大体有两点:</p>
<ol>
<li><p>由于视图无需保存数据.因此可以节省存储设备的容量.例如:我们之前创建了用来汇总商品种类(shohin_bunrui)的表.由于该表中的数据最终都会保存到存储设备之中,因此会占用存储设备的数据领域.但是,如果把同样的数据作为视图保存起来的话,就只需要下面这样的代码语句就可以了,这样就节省了存储设备的数据领域</p>
<pre><code> SELECTR shohin_bunrui,SUM(hanbai_tanka),SUM(shiire_tanka)
 FROM Shohin
 GROUP BY shohin_bunrui;
</code></pre><p> 本示例中表的数据量充其量只有几行,所以用视图并不会大幅缩小数据的大小.但是在实际业务中数量往往非常大,这时使用视图所节省的容量就往往非常可观了.</p>
<ul>
<li>法则5-1: 表中存储的是实际数据,而视图中保存的是从表中去数据所使用的SELECT语句.</li></ul>
</li><li><p>就是可以将频繁使用的SELECT语句保存成视图,这样就不用每次都重新书写了.创建好视图之后,只需要在SELECT语句中进行调用,就可以方便地得到想要的结果了.特别是在计算合计,以及由于包含复杂查询条件导致SELECT语句非常庞大时,使用视图可以大大提高效率.而且,视图中的数据会随着原表的变化而自动更新.视图归根到底就是SELECT语句,所谓&quot;参照视图&quot;也就是&quot;执行SELECT语句&quot;的意思.因此可以保证数据的最新状态.这是将数据保存在表中不具备的优势.</p>
<ul>
<li>法则5-2: 应该经常使用SELECT 语句做成视图</li></ul>
</li></ol>
<h4>创建视图的方法</h4>
<pre><code>创建视图的语句:
CREATE VIEW 视图名称(&lt;视图列名1&gt;,&lt;视图列名2&gt;,......)
AS
&lt;SELECT语句&gt;;
</code></pre><p>SELECT语句需要书写在AS关键字之后,SELECT语句中列的排列顺序和视图中列的排列顺序相同,SELECT语句中的第一列就是视图中的第一列,SELECT语句中的第二列就是视图中的第二列,依次类推.视图的列名在视图名称之后的列表中定义.</p>
<pre><code>西面我们用Shohin表作为基本表来创建视图:

CREATE VIEW ShohinSum(shohin_bunrui,cnt_shohin)    //视图的列名
AS                
-- 下面就是视图定义中的主体(内容只是一条SELECT语句)
SELECT shohin_bunrui,COUNT(*)    
FROM Shohin
GROUP BY shohin_bunrui;
</code></pre><p>这样我们就在数据库中创建了一副名为ShohinSum的视图.请注意,务必不能省略第二行中的关键字AS.<br>之后我们就可以使用视图了</p>
<pre><code>在视图ShohinSum中查看物品种类及种类的条数
SELECT shohin_bunrui,cnt_shohin
FROM ShohinSum;

其结果如下:
衣服    2
办公用品    2
厨房用具    4
</code></pre><p>通过上述视图ShohinSum定义的主体(SELECT语句)我们可以看出,该视图将根据商品种类(shohin_bunrui)统计出的商品数量(cut_shohin)作为结果保存了起来.这样如果大家在工作中需要频繁进行统计时,就不用每次都书写使用GROUP BY和COUNT函数的SELECT语句,从Shohin表中去的数据了.创建视图之后,就可以通过非常简单的SELECT语句,随时得到想要的合计结果了.并且如前所述,<strong>Shohin表中的数据更新之后,视图也会自动更新</strong>,非常灵活方便.</p>
<p>之所以能够实现上述功能,是因为<strong>视图就是保存好的SELECT语句</strong>.定义视图时,可以使用任何SELECT语句.既可以使用WHERE、GROUP BY、HAVING，也可以通过SELECT * 来指定全部列。</p>
<h5>使用视图的查询</h5>
<p>在FROM子句中使用视图的查询，通常有如下两个步骤：</p>
<ol>
<li>首先执行定义的SELECT语句</li><li>根据得到的结果，再执行在FROM子句中使用视图的SELECT语句</li></ol>
<p>也就是说，使用视图的查询通常需要执行2条以上的SELECT语句。这里没有说“2条”，而是&quot;2条以上&quot;是因为还可能出现以视图为基础创建出类似楼中楼那样的<strong>多重视图</strong>,例如下面的案例</p>
<pre><code>以ShohinSum为基础再创建出视图ShohinSumJim
CREATE VIEW ShohinSumJim (shohin_bunrui,cnt_shohin)
AS
SELECT shohin_bunrui,cnt_shohin
FROM ShohinSum         //以视图ShohinSum为基础
WHERE Shohin_bunrui = &#39;办公用品&#39;;

确认是否创建出视图:
SELECT shohin_bunrui,cnt_shohin
FROM shohinSumJim;

执行结果:
shohin_bunrui|count
-------------+-----
    办公用品        2
</code></pre><p>虽然语法上没有错误,但是我们还是应该尽量表面在视图的基础上创建视图.这是因为对多数DMBS来说,<strong>多重视图会降低SQL性能</strong>.因此最好还是使用单一视图.</p>
<ul>
<li>法则5-3: 应该避免在视图的基础上创建视图.</li></ul>
<h4>视图的限制1: 定义视图时不能使用ORDER BY子句</h4>
<p>虽然之前我们说过在定义视图时可以使用任意SELECT语句,但其实有一种情况例外,那就是不能使用ORDER BY子句.因此下面的视图语句是错误的:</p>
<pre><code>-- 不能这样定义视图:
CREATE VIEW ShohinSUM ( shohin_bunrui,cnt_shohin)
AS
SELECT shohin_bunrui, COUNT(*)
FROM Shohin
GROUP BY shohin_bunrui
ORDER BY shohin_bunrui;        //定义视图时不能使用ORDER BY 语句.
</code></pre><p>为什么不能使用ORDER BY 子句呢?因为视图和表一样.<strong>数据行都是没有顺序的.</strong>实际上,有些DBMS在定义视图时是可以使用ORDER BY子句的(POSTGRESQL),但这并不是通用的语法.因此,在定义视图时请不要用ORDER BY 语句.</p>
<h4>视图的限制2: 对视图进行更新</h4>
<p>之前我们说过,在SELECT语句中视图可以和表一样进行使用.那么对于INSERT,DELETE,UPDATE这类更新语句(更新数据库的SQL) 来说会怎么样呢?</p>
<p>实际上虽然这其中有很严格的限制.但是某些时候也可以对视图进行更新.标准SQL中有这样的规定:如果定义视图的SELECT语句能够满足某些条件,那么这个视图就可以被更新,下面就是比较有代表性的条件:</p>
<ol>
<li>SELECT子句中未使用DISTINCT</li><li>FROM子句中只有一张表</li><li>未使用GROUP BY 子句</li><li>未使用HAVING子句</li></ol>
<p>此前我们学过,FROM子句里通常只有一张表,因此,我们可能觉得 2里的条件有点奇怪,但其实 FROM子句中也可以并列使用多张表.我们在学习完&quot;表结合&quot;的操作后就明白了.</p>
<p>其他的条件大多数都与聚合有关.简单来说,像上面例子中使用的ShohinSum那样,使用视图来保存原表聚合结果时,是无法判断如何将视图更改反映到原表中的,比如对ShohinSum执行如下INSERT语句</p>
<pre><code>INSERT INTO ShohinSum VALUES(&#39;电器制品&#39;,5);
</code></pre><p>这样的语句会发生错误.因为视图ShohinSum是通过GROUP BY子句对原表进行聚合得到的.为什么通过聚合得到的视图不能进行更新呢?<br>视图贵庚到底还是从表派生出来的,因此如果原表可以更新的话,那么视图中的数据也可以更新.反之亦然,如果视图发生了改变,而原表没有进行相应更新的话,就无法保证数据的一致性了.<br>使用<code>INSERT INTO ShohinSum VALUES(&#39;电器制品&#39;,5);</code>,像视图ShohinSum中添加数据(&quot;电器制品&quot;,5)时,原表Shohin应该如何更新才好?按理说应该向表中添加商品种类为&quot;电器制品&quot;的5行数据,但是这些商品对应的&quot;商品编号、商品名称和销售单价等”我们都不清楚。数据库在这里就遇到了麻烦。</p>
<ul>
<li>法则5-5： 视图和表需要同时进行更新，因此通过聚合得到的视图无法进行更新.</li></ul>
<h5>能够更新视图的情况</h5>
<p>像下面这段代码，不是通过聚合得到的视图就可以进行更新。</p>
<pre><code>CREATE VIEW ShohinJim ( shohin_id,shohin_mei,shohin_bunrui,hanbai_tanka,shiire_tanka,torokubi)
AS
--下面既没有聚合也没有结合的SELECT语句
SELECT *
FROM Shohin
WHERE shohin_binrui = &#39;办公用品&#39;;
</code></pre><p>对于上面只包含办公用品类商品的视图ShohinJim来说,就可以执行下面的INSERT语句</p>
<pre><code>INSERT INTO ShohinJim VALUES(&#39;0009&#39;,&#39;印章&#39;,95,10,&#39;2009-11-30&#39;);
// 向视图中天加一行
</code></pre><p><strong><em>注意事项</em></strong></p>
<p>由于PostgreSQL中的视图会被初始设定为制度,所以执行上面的INSERT语句时,会才发生下面这样的错误:</p>
<pre><code>ERROR: 不能向视图中插入数据
HINT: 需要一个无条件的ON INSERT DO INSTEAD
</code></pre><p>因此,在执行INSERT语句之前,需要使用下面的指令,允许更新操作.在DB2和MySQL等其他DBMS中,并不需要执行这样的指令</p>
<p><strong>允许PostgreSQL对视图进行更新</strong></p>
<pre><code>CREATE OR REPLACE RULE insert_rule
AS ON INSERT
TO ShohinJim DO INSTEAD
INSERT INTO Shohin VALUES(
    new.shohin_id
    new.shohin_mei
    new.shohin_bunrui
    new.hanbai_tanka
    new.shiire_tanka
    new.torokubi);
</code></pre><p>我们用SELECT语句来确认数据行是否添加成功</p>
<pre><code>SELECT * FROM ShohinJim;

执行结果: 数据行已经成功添加到视图中了:

0002    打孔器    办公用品    500    320    2009-09-11
0008    圆珠笔    办公用品    100        2009-11-11
0009    印章    办公用品    95    10    2009-11-20
</code></pre><p>原表</p>
<pre><code>SELECT * FROM ShohinJim

执行结果: 数据行已经成功添加到原表中了:
0001    T恤    衣服    1000    500    2009-09-20
0002    打孔器    办公用品    500    320    2009-09-11
0003    运动T恤    衣服    4000    2800    
0004    菜刀    厨房用具    3000    2800    2009-09-20
0005    高压锅    厨房用具    6800    5000    2009-01-15
0006    叉子    厨房用具    500        2009-09-20
0007    擦菜板    厨房用具    880    790    2008-04-28
0008    圆珠笔    办公用品    100        2009-11-11
0009    印章    办公用品    95    10    2009-11-20
</code></pre><p>UPDATE语句和DELETE语句当然也可以想操作表时那样正常执行,但是对于原表来说却需要设置各种各样的约束(主键和NOT NULL等),需要特别注意</p>
<h4>删除视图</h4>
<p>删除视图需要使用 <strong>DROP VIEW语句</strong>. </p>
<pre><code>语法结构如下:
DROP VIEW 视图名称(&lt;视图列名1&gt;,&lt;视图列名2&gt;,...)

案例:删除ShohinSum视图:
DROP VIEW ShohinSum;

特定的SQL:
在PostgreSQL中,如果想要删除以视图为基础创建出来的多重视图的话,由于存在关联的视图,会发生以下错误.
执行结果(使用PostgreSQL)
ERROT: 由于存在关联视图,所以无法删除视图ShohinSum
DETAIL: 视图shoshinsumjim与视图shohinsum相关联
HINT:  删除关联对象请使用DROP...CASCADE

PostgreSQL 删除相关联视图: DROP VIEW ShohinSum CASCADE
</code></pre><p><strong><em>备忘</em></strong><br>下面我们再次将Shohin恢复到初始状态(8行),执行以下DELETE语句,删除之前的1行数据</p>
<pre><code>删除商品编号为&#39;0009(印章)&#39;的语句
DELETE FROM shohin WHERE shohin_id = &#39;0009&#39;;
</code></pre><h3>5-2 子查询</h3>
<p>简而言之,子查询就是一次性的视图(SELECT语句).与视图不同,子查询在SELECT语句执行完毕之后就会消失</p>
<h4>子查询和视图</h4>
<p>前面我们学习了视图这个非常方便的工具,本节将学习以视图为基础的子查询.子查询的特点概括起来就是一张一次性视图</p>
<p>我们先来复习视图的概念,视图并不是用来保存数据的,而是通过保存读取数据的SELECT语句的方法来为用户提供便利的工具.反之,子查询就是将<strong>用来定义视图的SELECT语句</strong>直接用于FROM子句当中.<br>截下来,就让我们拿前一届使用的视图ShohinSum(商品合计)来与子查询进行一番比较吧.</p>
<p>首先我们再来看一下视图ShohinSum和确认用的SELECT语句</p>
<pre><code>--根据商品种类统计商品数量的视图
CREATE VIEW ShohinSum(hanbai_tanka,cnt_shohin)
AS
SELECT shohin_bunrui,COUNT(*)
FROM shohin
GROUP BY shohin_bunrui;

-- 确认视图是否已经创建成功
SELECT shohin_bunrui,cnt_shohin;
FROM ShohinSum;

能够实现同样功能的子查询如下:
--直接在FROM子句中使用定义视图的SELECT语句

SELECT shohin_bunrui,count(*)
FROM (SELECT shohin_bunrui COUNT(*) AS cn_shohin
    FROM Shohin
    GROUP BY Shohin_bunrui) AS ShohinSum

特定的SQL
    在Oracle的FROM语句中,不能使用 AS(会发生错误).因此,在Oracle中执行上面的代码时,需要将 &quot;) AS ShohinSum;&quot; 变成 &quot;) ShohinSum;&quot;
</code></pre><p>上面的两种方法得到的结果完全相同<br>衣服    2<br>办公用品    2<br>厨房用具    4</p>
<p>如上所示,子查询就是将用来定义视图的SELECT语句直接用于FROM子句当中.虽然&quot;AS ShohinSum&quot; 就是子查询的名称,但由于该名称是一次性的,因此不会像视图那样保存于存储节制(硬盘)之中,而是在SELECT语句执行后就消失了.子查询(Subquery)就是次级(subordinated) 查询(query).</p>
<p>实际上,该SELECT语句包含嵌套的(括号内的)结构,首先会执行FROM子句中的SELECT语句,然后才会执行外层的SELECT语句.</p>
<ul>
<li>法则5-6: 子查询作为内层查询会首先执行.</li></ul>
<h4>增加子查询的层数</h4>
<p>由于子查询的层数,原则上没有限制,因此可以像&quot;子查询的FROM子句中还可以继续使用子查询,该子查询的FROM子句中还可以再使用子查询...&quot;这样无限嵌套下去.</p>
<pre><code>SELECT shohin_bunrui,cnt_shohin
FROM(SELECT *
    FROM(SELECT shohin_bunrui,COUNT(*) AS cnt_shohin
     FROM Shohin
     GROUP BY shohin_bunrui) AS ShohinSum
     WHERE cnt_shohin = 4) AS ShohinSum2;

执行结果如下:
厨房用具    4
</code></pre><p>最内层的子查询(ShohinSum)与之前一样,根据商品种类(Shohin_bunrui)对数据进行聚合,其外层的子查将商品数量(cnt_shohin)限定为4,结果就得到了1行厨房用具的数据.<br>但是随着子查询嵌套层数的增加,SQL语句会变得越来越难读懂,性能也会越来越差.因此,请避免使用多层嵌套的子查询.</p>
<h4>子查询的名称</h4>
<p>之前的例子中我们给子查询设定了&quot;ShohinSum&quot;等名称.原则上子查询必须设定名称,因此请大家尽量从处理内容的角度出发为子查询设立恰当的名称.在上述例子中,子查询用来对Shohin表的数据进行汇集,因此我们使用了后缀Sum作为其名称.<br>为子查询设立名称时需要使用AS关键字,该关键字<em>有时(在ORACLE中)</em>也可以省略,为了规范最好还是打上.</p>
<h4>标量子查询</h4>
<p>接下来我们学习子查询中的标量子查询(Scalar subquery),可以理解为excel表格中的一个单元格里的值</p>
<h4>什么是标量</h4>
<p>标量就是单一的意思,在数据库之外的领域也经常用到.<br>上面我们学习的子查询基本上都会返回多行结果(虽然偶尔也会只返回一行数据).由于结构和表相同,所以也会有查询不到结果的情况.<br>而标量子查询则有一个特殊的限制,那就是<strong>必须且只能返回1行1列的结果.</strong>也就是返回表中某一行的某一列的值,如&quot;10&quot;或者&quot;北京&quot;这样的值.</p>
<ul>
<li>法则5-7: 标量子查询就是返回单一值的查询</li></ul>
<p>细心的读者可能会发现,由于返回的是单一的值,因此标量子查询的返回值可以用在 = 或者&lt;&gt; 这样需要单一值的比较运算符之中.这也正是标量子查询的优势所在.下面我们就来试试</p>
<h5>在WHERE子句中使用标量子查询</h5>
<p>在前面章节中,我们练习了通过各种各样的条件从Shohin(商品)表中读取数据.大家有没有想过通过下面这样的条件查询数据呢?</p>
<p><em>&quot;查询出销售单价高于平均单价的商品&quot;</em></p>
<p>或者说想知道价格处于上游的商品时,也可以通过上述条件进行查询.<br>然而这并不是用普通方法就能解决的.如果我们用像下面这样的函数就会出错</p>
<pre><code>//错误代码;失败的查询
SELECT shohin_id,shohin_mei,hanbai_tanka,
 FROM Shohin
WHERE hanbai_tanka &gt; AVG(hanbai_tanka);
</code></pre><p>虽然这样的SELECT语句看上去能满足我们的要求,但是由于在WHERE子句中不能使用聚合函数,因此这样的SELECT语句是错误的.<br>这时候标量子查询就可以发挥它的功效了.首先,如果想要求出Shohin表中商品的平均销售单价(hanbai_tanka),可以使用下面的SELECT语句</p>
<pre><code>SQL语句:
SELECT AVG(hanbai_tanka)
FROM Shohin
执行结果
2097.5
</code></pre><p>不难发现,上面的SELECT语句的查询结果是单一的值(2907.5).因此,我们可以直接将这个结果用到之前失败的查询中;正确的代码如下:</p>
<pre><code>//正确语句:
SELECT shohin_id,shohin_mei,hanbai_tanka
FROM Shohin
WHERE hanbai_tanka &gt; (SELECT AVG(hanbai_tanka) 
                    FROM shohin);
执行结果:
0003    运动T恤    4000
0004    菜刀    3000
0005    高压锅    6800
</code></pre><p>使用子查询的SQL会从子查询开始执行(可以理解为括号优先权)</p>
<h4>标量子查询的书写位置</h4>
<p>标量子查询的书写位置并不仅仅局限于WHERE子句中,通常任何可以使用单一值的位置都可以使用.也就是说__能够使用常数或者列名的地方,无论是SELECT子句、GROUP BY 子句、HAVING子句、还是ORDER BY子句,几乎所有地方都可以使用<br>例如,在SELECT子句当中使用之前计算平均值的标量子查询的SQL语句,如下所示:</p>
<pre><code>// 在SELECT子句中使用标量子查询
SELECT shohin_id,shohin_mei,hanbai_tanka,(SELECT  AVG(hanbai_tanka) FROM shohin) AS avg_tanka
FROM shohin;
执行结果
shohin_id,shohin_mei,hanbai_tanka,avg_tanka
0001    T恤    1000    2097.5
0002    打孔器    500    2097.5
0003    运动T恤    4000    2097.5
0004    菜刀    3000    2097.5
0005    高压锅    6800    2097.5
0006    叉子    500    2097.5
0007    擦菜板    880    2097.5
0008    圆珠笔    100    2097.5
</code></pre><p>我们还可以在HAVING子句中使用标量子查询</p>
<pre><code>//在HAVING子句中使用标量子查询
SELECT Shohin_bunrui,AVG(hanbai_tanka)
FROM Shohin
GROUP BY shohin_bunrui
HAVING AVG(hanbai_tanka) &gt; (SELECT AVG(hanbai_tanka) 
                            FROM shohin);
//执行结果
Shohin_bunrui,avg
衣服    2500
厨房用具    2795
</code></pre><p>该查询的含义是想要选取出按照商品种类计算出销售单价高于全部商品的平均销售单价的种类.如果在SELECT语句中不使用HAVING子句的话,那么平均销售单价为300元的办公用品也会被选取出来.但是,由于全部商品的平均销售单价是2097.5元.因此低于该平均值的办公用品会被HAVING子句中的条件排除在外.</p>
<h3>使用标量子查询的注意事项</h3>
<p><strong>标量子查询绝对不能返回多行结果.</strong>也就是说如果子查询返回了多行结果,那么它就不再是标量子查询,而仅仅是一个普通的子查询了.因此不能被用在=或者&lt;&gt;等需要一个输入值的运算符当中,也不能用在SELECT等子句当中.</p>
<pre><code>//例如,下面的SELECT子查询会出错
//由于不是标量子查询,因此不能在SELECT子句中使用
SELECT Shohin_id,shohin_mei,hanbai_tanka.(SELECT AVG(hanbai_tanka)
                                            FROM Shohin
                                            GROUP BY shohin_bunrui) AS avg_tanka
FROM Shohin;        
/*执行结果:
报错提示: ERROR: more than one row returned by a subquery used as an expression
        标量子查询中使用了返回的多行结果的表达式*/
</code></pre><p>发生错误的原因很简单,就是因为子查询返回如下的结果:<br>衣服    2500<br>办公用品    300<br>厨房用具    2795</p>
<p>在一行子句之中当然不能使用3行数据.因此,上述SELECT语句会返回&quot;因子查询反悔多行数据所以不能执行&quot;这样的错误信息.</p>
<h3>5-3 关联子查询</h3>
<h4>普通子查询和关联子查询的区别</h4>
<p>按此前所学,使用子查询就能取出销售单价(hanbai_tanka)高于全部商品平均销售单价的商品.这次我们稍微改变一下条件,选取出各商品分类中高于该分类的平均单价的商品</p>
<h5>按照商品分类与平均销售单价进行比较</h5>
<p>只通过语言描述可能难以理解,还是让我们看看具体示例,我们以厨房用具中的商品为例,该分组中包含了4中商品:<br>商品名称    单价<br>菜刀    3000<br>高压锅    6800<br>叉子    500<br>擦菜板    880</p>
<p>因此上述4种商品的平均价格为 (3000+6800+500+880)÷4=2795(元)</p>
<p>这样,我们就得治该分组内高于平均价格的商品就是菜刀和高压锅了,这两种商品就是我们要选取的对象</p>
<p>同样我们可以得出衣服分组平均价格为2500元,要选取的对象为运动T恤;办公用品的平均销售单价为300元,打孔器就是我们要选取的对象.</p>
<p>这样大家就知道我们应该进行什么样的操作了,__我们并不是要以全部商品为基础,而是要以细分的组为基础,对组内商品的平均价格和各商品的销售单价进行比较.</p>
<p>按照商品种类计算平均价不是什么难事,计算份额方法我们学过,使用GROUP BY方法即可</p>
<pre><code>SELECT AVG(hanbai_tanka)
FROM Shohin
GROUP BY shohin_bunrui;
</code></pre><p>但是,如果我们使用前一节(标量子查询的)方法,直接把上述SELECT语句使用到WHERE子句当中的话,就会发生错误.</p>
<pre><code>//错误的代码:
SELECT Shohin_id,shohin_mei,hanbai_tanka
FORM Shohin
WHERE hanbai_tanka &gt; (SELECT hanbai_tanka
                        FROM Shohin
                        GROUP BY Shohin_bunrui);
// 执行结果:报错[21000] ERROR: more than one row returned by a subquery used as an expression
标量子查询中使用了返回的多行结果的表达式
</code></pre><p>这里我们就需要使用关联子查询了.</p>
<h5>使用关联子查询的解决方案</h5>
<p>只需要在上面的SELECT语句中追加一行,就能得到我们想要的结果了.</p>
<pre><code>//正确代码:
SELECT Shohin_mei,hanbai_tanka
FROM Shohin AS S1    -- 为表Shohin创建一个别名S1
WHERE  hanbai_tanka &gt; (SELECT AVG(hanbai_tanka)
                        FROM Shohin AS S2  --为子查询中的表Shohin创建一个别名S2
//该条件就是成功的关键 →    WHERE S1.shohin_bunrui = S2.shohin_bunrui    
                        GROUP BY shohin_bunrui);
//执行结果:
打孔器    500
运动T恤    4000
菜刀    3000
高压锅    6800
</code></pre><p>这样我们就能选取出办公用具、衣服和厨房用具三类商品中高于该类商品平均单价的商品了.</p>
<p>这里起到关键作用的就是<strong>在子查询中添加的WHERE子句的条件.</strong>该条件的意思就是<strong><em>在同一(=的作用)商品种类中对各商品的销售单价和平均单价进行比较.</em></strong></p>
<ul>
<li>法则5-8 在细分的组内进行比较时,需要使用关联子查询 </li></ul>
<h4>关联子查询也是用来对集合进行切分的</h4>
<p>换个角度来看,其实关联子查询也和GROUP BY子句一样,可以对集合进行切分,下图显示了最为记录集合的表是如何按照商品种类被切分的.</p>
<p><img src="http://kfdown.a.aliimg.com/kf/HTB1QK3FNVXXXXcuXXXXq6xXFXXXr/126425022/HTB1QK3FNVXXXXcuXXXXq6xXFXXXr.jpg" title=""></p>
<p>我们需要计算各个商品分类中商品的平均销售单价,由于该单价会用来和商品表中的个条记录进行比较,因此关联子查询实际只能返回一行结果.这也是关联子查询不出错的关键.关联子查询执行时,DBMS内部的执行结果如下图:</p>
<p><img src="http://kfdown.a.aliimg.com/kf/HTB1f03rNVXXXXcxXFXXq6xXFXXXT/126425022/HTB1f03rNVXXXXcxXFXXq6xXFXXXT.jpg" title=""></p>
<p>如果商品种类发生了变化,那么用来进行比较的平均单价也会发生变化,这样就可以将各种商品的销售单价和平均单价进行比较了.关联子查询的内部执行结果对于初学者来说是比较难以理解的,但是像上图这样将其内部执行结果可视化,理解起来就非常容易了.</p>
<h4>结合条件一定要写在子查询中</h4>
<p>SQL初学者在使用关联子查询时经常犯一个错误,那就是将关联条件写在子查询之外的外层查询之中.比如下面的SELECT语句:</p>
<pre><code>//错误的语句
SELECT shohin_bunrui,shohin_mei,hanbai_tanka
FROM shohin AS S1
//错误的地方    WHERE S1.shohin_bunrui = S2.shohin_bunrui
AND hanbai_tanka &gt; (SELECT AVG(hanbai_tanka)
                    FROM shohin AS S2
                    GROUP BY shohin_bunrui);
// 报错: [42P01] ERROR: missing FROM-clause entry for table &quot;s2&quot; 位置：89
</code></pre><p>上述SELECT 语句只是将子查询中的关联条件已到了外层查询之中,并未添加任何更改.但是该SELECT语句会发生错误,不能正确执行.允许存在这样的书写方法可能并不奇怪,但是SQL的规则禁止这样书写方法.</p>
<h2>第六章 函数、谓词、CASE表达式</h2>
<h3>6-1 各种各样的函数</h3>
<h4>函数的种类</h4>
<p>前几章 我们学习了SQL的语法结构等必须要遵守的规则.本章将会进行一点改变,来学习一些SQL自带的便利工具→函数.<br>所谓函数,就是输入某一值得到相应输出结果的功能.输入值称为<strong><em>参数(Parameter)</em></strong>,输出值称为<strong><em>返回值</em></strong>.<br>函数大概分为一下几种.</p>
<ul>
<li>算数函数(用来进行数值计算的函数)</li><li>字符串函数(用来进行字符串操作的函数)</li><li>日期函数(用来进行日期操作的函数)</li><li>转换函数(用来进行转换数据类型和值的函数)</li><li>聚合函数(用来进行行数聚合的函数)</li></ul>
<p>我们前面已经学习了聚合函数的相关内容,应该对函数有初步的了解.聚合函数基本上只包含了COUNT、SUM、AVG、MAX、MIN这5种,而其他种类的函数总数可以轻松超过200种,虽然数量众多,但常用函数只有30-50种,不熟系的我们可以通过参考文档进行查询.<br>本节我们会学习一些具有代表性的函数.并不需要一次全部记住,只要知道有这样的函数就可以了.实际应用时可以通过参考文档进行查询.接下来,将会按照英文字母的顺序,分类介绍这些函数.</p>
<h4>算数函数</h4>
<p>算数函数是最基本的函数,我们之前已经学习过了,就是前面的加减乘除四则运算</p>
<ul>
<li><ul>
<li>(加法)</li></ul>
</li><li><ul>
<li>(减法)</li></ul>
</li><li>× (乘法)</li><li>÷ (除法)</li></ul>
<p>由于这些算数运算符具有&quot;根据输入值返回相应输出结果&quot;的功能,所以它们是出色的算数函数.在此我们将会给大家介绍除此之外的具有代表性的函数.<br>为了学习算数函数,我们先根据下面的代码创建一张示例表(SampleMath),在创建示例之前,我们先介绍一下 Numeric数据类型,NUMERIC数据类型是大多数DBMS都支持的一种数据类型,通过NUMERIC(全体位数,小数位数)的形式来指定数值大小.截下来,将会给大家介绍常用的算数函数→ROUND函数,由于PostgreSQL中的ROUND函数只能使用NUMERIC类型的数据,因此我们在示例中也使用了该数据类型.</p>
<pre><code>-- DDL:创建表:
CREATE TABLE SampleMath(
m NUMERIC (10,3),
n INTEGER,
p INTEGER);

-- DML:插入数据:
BEGIN TRANSACTION;

INSERT INTO SampleMath(m,n,p) VALUES(500,0,Null);
INSERT INTO SampleMath(m,n,p) VALUES(-180,0,NULL);
INSERT INTO SampleMath(m,n,p) VALUES(NULL,NULL,NULL);
INSERT INTO SampleMath(m,n,p) VALUES(NULL,7,3);
INSERT INTO SampleMath(m,n,p) VALUES(NULL,5,2);
INSERT INTO SampleMath(m,n,p) VALUES(NULL,4,NULL);
INSERT INTO SampleMath(m,n,p) VALUES(8,NULL,3);
INSERT INTO SampleMath(m,n,p) VALUES(2.27,1,NULL);
INSERT INTO SampleMath(m,n,p) VALUES(5.555,2,NULL);
INSERT INTO SampleMath(m,n,p) VALUES(NULL,1,NULL);
INSERT INTO SampleMath(m,n,p) VALUES(8.76,NULL,NULL);
COMMIT;
</code></pre><p>下面让我们确认一下创建好的表中的内容.其中应该包含了m,n,p三列</p>
<pre><code>SELECT * FROM SampleMath

执行结果:
500.000    0    
-180.000    0    

    7    3
    5    2
    4    
8.000        3
2.270    1    
5.555    2    
    1    
8.760
</code></pre><h5>绝对值</h5>
<pre><code>代码格式:
ABS(数值)
</code></pre><p>ABS是计算绝对值的函数.绝对值(ABSOLUTE VALUE) 就是不考虑数值的符号,表示一个数到远点距离的数值.简单来说绝对值的计算方法就是:0和证书的绝对值是其本身,负数的绝对值就是去掉负号后的结果.</p>
<pre><code>示例:

SELECT m,
    ABS(m) AS abs_col
    FROM SampleMath;

执行结果:
m        abs_col
500.000    500
-180.000    180




8.000    8
2.270    2.27
5.555    5.555

8.760    8.76
</code></pre><p>上述执行结果中右侧的abs<em>col列就是通过ABS函数计算出的m列的绝对值.请注意-180的绝对值就是去掉负号后的结果180.<br>通过上述结果我们可以发现,ABS函数的参数为NULL是,结果也是NULL.并非只有ABS函数如此,绝大多数函数对于NULL的结果都是NULL(__</em>转换函数COALESCE<em>_</em>).</p>
<h5>MOD函数</h5>
<pre><code>函数格式:
MOD(被除数,除数)
</code></pre><p>MOD是计算除法余数(剩余)的函数,是modulo的简称.例如,7/3的余数是1,因此MOD(7,3)的结果也是1,由于小数计算中并没有余数的概念,所以只能对整数类型的列使用MOD函数.</p>
<pre><code>计算除法(n÷p)的余数
SELECT n,p,
    MOD(n,p) AS mod_col
    FROM SampleMath;
执行结果:
n    p    mod_col
0        
0        

7    3    1
5    2    1
4        
    3    
1        
2        
1        
范例:mod_col: MOD(n,p) 的返回值(n÷p的余数)
</code></pre><p><strong><em>特殊的SQL</em></strong><br>SQL SERVER使用特殊的运算符&quot;%&quot; 来计算余数.使用下面的语句可以得到与上面语句同样的结果:</p>
<pre><code>-- SQL SERVER语句:
SELECT n,p,
    n % p AS mod_col
    FROM SampleMath;
</code></pre><h5>ROUND 四舍五入</h5>
<pre><code>ROUND 函数的语法:
ROUND(对象数值,保留小数的位数)
</code></pre><p>ROUND函数用来进行四舍五入操作,四舍五入在英语中称为ROUND.<br>如果指定四舍五入的位数为1,那么对小数点第二位进行四舍五入<br>案例:对m列的数值进行n列位数的四舍五入处理</p>
<pre><code>SELECT m,n,        //m是对象数值,n是四舍五入位数
    ROUND(m,n) AS round_col
    FROM SampleMath;
执行结果:
m        n    round_col
500.000    0    500
-180.000    0    -180

    7    
    5    
    4    
8.000        
2.270    1    2.3
5.555    2    5.56
    1    
8.760
</code></pre><h4>字符串函数</h4>
<p>到目前为止,我们学习的都是针对数值的算数函数,但其实算数函数只是SQL(其他编程语言通常也是如此)自带函数中的一部分.虽然算数函数是我们经常使用的函数,但是字符串函数也是同样经常被使用<br>在日常生活中,我们经常会像使用数字那样对字符串进行替换,截取,简化等操作.因此SQL也为我们提供了很多操作字符串的功能.<br>为了学习字符串函数,我们再来创建一张表(SampleStr)</p>
<pre><code>-- DDL:创建表
CREATE TABLE SampleStr(
str1 VARCHAR(40),
str2 VARCHAR(40),
str3 VARCHAR(40));

--DML:插入数据:
BEGIN TRANSACTION;

INSERT INTO SampleStr (str1,str2,str3) VALUES (&#39;opx&#39;,&#39;rt&#39;,NULL);
INSERT INTO SampleStr (str1,str2,str3) VALUES (&#39;abc&#39;,&#39;def&#39;,NULL);
INSERT INTO SampleStr (str1,str2,str3) VALUES (&#39;山田&#39;,&#39;太浪&#39;,&#39;傻货&#39;);
INSERT INTO SampleStr (str1,str2,str3) VALUES (&#39;aaa&#39;,NULL,NULL);
INSERT INTO SampleStr (str1,str2,str3) VALUES (NULL,&#39;xyz&#39;,NULL);
INSERT INTO SampleStr (str1,str2,str3) VALUES (&#39;@!#$%&#39;,NULL,NULL);
INSERT INTO SampleStr (str1,str2,str3) VALUES (&#39;ABC&#39;,NULL,NULL);
INSERT INTO SampleStr (str1,str2,str3) VALUES (&#39;aBC&#39;,NULL,NULL);
INSERT INTO SampleStr (str1,str2,str3) VALUES (&#39;abc太郎&#39;,&#39;abc&#39;,&#39;ABC&#39;);
INSERT INTO SampleStr (str1,str2,str3) VALUES (&#39;abcdefabc&#39;,&#39;abc&#39;,&#39;ABC&#39;);
INSERT INTO SampleStr (str1,str2,str3) VALUES (&#39;micmic&#39;,&#39;i&#39;,&#39;I&#39;);

COMMIT;

查看创建好的表中的内容: SELECT * FROM SampleStr

执行结果:
str1    str2    str3
opx    rt    
abc    def    
山田    太浪    傻货
aaa        
    xyz    
@!#$%        
ABC        
aBC        
abc太郎    abc    ABC
abcdefabc    abc    ABC
micmic    i    I
</code></pre><h5>拼接</h5>
<pre><code>拼接函数语法格式:
字符串1||字符串2
</code></pre><p>在实际业务中,我们经常会碰到abc+de=abcde 这样希望将字符串进行拼接的情况.在SQL中,可以通过两条并列的竖线变换成的&quot;||&quot;函数来实现<br>案例:拼接两个字符串</p>
<pre><code>-- Oracle,DB2,Postgresql
SELECT str1,str2
    str1||str2 AS str_concat
FROM SampleStr;

执行结果:
str1  str2   str_concat 
opx    rt    opxrt
abc    def    abcdef
山田    太浪    山田太浪
aaa        
    xyz    
@!#$%        
ABC        
aBC        
abc太郎    abc    abc太郎abc
abcdefabc    abc    abcdefabcabc
micmic    i    micmici
</code></pre><p>进行特殊字串拼接时,如果其中包含NULL,那么得到的结果也是NULL这是因为&quot;||&quot;也是变了形的函数.当然,三个以上的字符串也可以进行拼接</p>
<pre><code>三个字符串拼接:
SELECT str1,str2,str3,
str1||str2||str3 AS str_concat
FROM SampleStr
WHERE str1=&#39;山田&#39;;

执行结果:
str1    str2    str3    str_concat
山田    太浪    傻货    山田太浪傻货
</code></pre><p><strong><em>请注意,||拼接函数在SQL SERVER和MySQL中无法使用</em></strong></p>
<pre><code>特定的SQL:
SQL Server:使用&quot;+&quot;运算符(函数)来链接字符串.
SELECT str1,str2,str3.
str1+str2+str3 AS str_concat
FROM SampleStr;

MySQL使用Concat函数来完成字符串的拼接.
SELECT str1,str2,str3
CONCAT(str1,str2,str3) AS str_concat
FROM SampleStr;
</code></pre><h5>LENGTH 字符串长度</h5>
<p>想知道字符串中包含多少歌字符时,可以使用LENGTH(长度)函数</p>
<pre><code>Length 函数格式:
LENGTH 格式:
Oracle,DB2,PostgreSQL,MySQL:
SELECT str1,
LEGTH(str1) AS len_str
FROM SampleStr;

执行结果:
str1 len_str
opx    3
abc    3
山田    2
aaa    3

@!#$%    5
ABC    3
aBC    3
abc太郎    5
abcdefabc    9
micmic    6
</code></pre><p><strong><em>需要注意的是,该函数也无法在SQL Server中使用</em></strong></p>
<pre><code>特定的SQL
    SQL Server使用LEN函数来计算字符串的长度,具体如下:
    SELECT str1,
    LEN(str1) AS len_str
    FROM SampleStr;
</code></pre><h5>LOWER 小写转换</h5>
<pre><code>函数格式: LOWER(字符串)
</code></pre><p>LOWER函数只能针对英文字母使用,它会将参数中的字符串全部转换为小写.因此该函数不适合英文字母意外的场合.此外,该函数并不影响原本就是小写的字符</p>
<pre><code>案列:
SELECT str1,
LOWER(str1) AS low_str
FROM SampleStr
WHERE str1 IN (&#39;ABC&#39;,&#39;aBc&#39;,&#39;abc&#39;,&#39;山田&#39;);    //IN 是指前面的对象是后面参数中的一种即符合条件
</code></pre><p>既然存在小写转换函数,那么肯定也有大写转换函数,UPPER就是大写转换函数.</p>
<h5>REPLACE 字符串的替换</h5>
<pre><code>REPLACE函数的语法格式:
REPLACE (对象字符串,替换前的字符串,替换后的字符串)
</code></pre><p>使用REPLACE函数,可以将字符串的一部分替换为其他的字符串</p>
<pre><code>案例:替换字符串的一部分
SELECT str1,str2,str3,
REPLACE(str1,str2,str3) AS rep_str
FROM SampleStr;

执行结果:
str1 str2 str3 rep_str
opx    rt        
abc    def        
山田    太浪    傻货    山田
aaa            
    xyz        
@!#$%            
ABC            
aBC            
abc太郎    abc    ABC    ABC太郎
abcdefabc    abc    ABC    ABCdefABC
micmic    i    I    mIcmIc
</code></pre><h5>SUBSTRING字符串的截取</h5>
<pre><code>函数语法:
SUBSTRING (对象字符串 FROM 截取的起始位置 FOR 截取的字符数)
</code></pre><p>使用SUBSTRING函数可以截取出字符串中的一部分字符串.截取的起始位置从字符串最左侧开始计算.</p>
<pre><code>案例:截取字符串中第三位和第四位字符:
PostgreSQL和MySQL:
SELECT str1,
SUBSTRING (str1,FROM 3 FOR 2) AS sub_str
FROM SampleStr;

执行结果:
str1 sub_str
opx    x
abc    c
山田    
aaa    a

@!#$%    #$
ABC    C
aBC    C
abc太郎    c太
abcdefabc    cd
micmic    cm
</code></pre><p>虽然上述SUBSTRING函数的语法是标准SQL承认的正式语法,但是现在只有PostgreSQL和MySQL支持该语法.</p>
<pre><code>特定的SQL
SQL Server专用语法:    SUBSTRING(对象字符串,截取的起始位置,截取的字符数)
Oracle/DB2专用语法: SUBSTR(对象字符串,截取的起始位置,截取的字符数)
</code></pre><h5>UPPER函数:大写切换</h5>
<pre><code>语法结构:UPPER(字符串)
</code></pre><p>UPPER函数只能针对英文字母使用,它会将参数中的字符串全都转换成大写.因此该函数并不适用于英文字母以外的情况.此外,该函数并不影响原本就是大写的字符.</p>
<pre><code>SELECT str1,
    UPPER(str1) AS up_str
    FROM SampleStr
    WHERE str1 IN (&#39;ABC&#39;,&#39;aBC&#39;,&#39;abc&#39;,&#39;山田&#39; );
执行结果:
abc    ABC
山田    山田
ABC    ABC
aBC    ABC
</code></pre><h4>日期函数</h4>
<p>虽然SQL中有很多日期函数,但是其中大部分都依存于格子的DBMS,因此无法进行统一的说明.本届我们将学习那些被标准SQL承认,可以应用于大多数DBMS的函数.</p>
<h5>CURRENT_DATE函数</h5>
<p>CURRENT_DATE函数能够返回SQL执行的日期,也就是改函数执行时的日期.由于没有参数,所以无需使用括号.<br>执行日期不同,CURRENT_DATE函数的返回值也不同,如果在2009年12月13日执行该函数,会得到返回值&quot;2009-12-13&quot;.如果在2010年1月1日执行,就会得到返回值&quot;2010-01-01&quot;</p>
<pre><code>-- PostgreSQL MySQL
SELECT CURRENT_DATE

2016年11月11日执行该函数的结果:
date
----------
2016-11-11
</code></pre><h5>CURRENT_TIME</h5>
<p>CURRENT_TIME函数能够取的SQL执行的时间,也就是该函数执行时的时间,由于该函数也没有参数,所以同样无需使用括号.</p>
<pre><code>--postgresql mysql

SELECT CURRENT_TIME

执行结果:
22:23:22
</code></pre><p>该函数同样<strong><em>无法在SQL Server中执行,在Oracle和DB2中的语法同样略有不同</em></strong>.</p>
<h5>CURRENT_TIMESTAMP函数</h5>
<p>CURRENT_TIMESTAMP函数同时具有CURRENT_DATE+CURRENT_TIME的功能.使用该函数可以同时得到当前的日期和时间,当然也可以从结果中截取日期或者时间.</p>
<pre><code>取得当前日期和时间
SELECT CURRENT_TIMESTAMP
执行结果:
    now
-------------
2016-11-11 22:49:50.970661
</code></pre><h5>EXTRACT截取日期元素</h5>
<pre><code>语法结构:
EXTRACT(日期元素 FROM 日期)
</code></pre><p>使用EXTRACT函数可以截取出日期数据中的一部分,例如&quot;年&quot;、&quot;月&quot;、&quot;日&quot;或者&quot;小时&quot;、&quot;秒&quot;等等,改函数的返回值并不是日期类型而是数值类型<br>案例:截取日期元素</p>
<pre><code>SELECT  CURRENT_TIMESTAMP
        EXTRACT(YEAR FROM CURRENT_TIMESTAMP) AS year,
        EXTRACT(MONTH FROM CURRENT_TIMESTAMP) AS month,
        EXTRACT(DAY FROM CURRENT_TIMESTAMP) AS day,
        EXTRACT(HOUR FROM CURRENT_TIMESTAMP) AS hour,
        EXTRACT(MINUTE FROM CURRENT_TIMESTAMP) AS minute,
        EXTRACT(SECOND FROM CURRENT_TIMESTAMP) AS second;
执行结果:
            now                year  month day hour min second        
2016-11-13 12:20:11.801396    2016    11    13    12    20    11.801396
</code></pre><h4>转换函数</h4>
<p>最后我们要学习一类比较特殊的函数--&gt; 转换函数.虽说有些特殊,但是由于这些函数的语法和之前介绍的语法类似,数量也比较少,因此很容易记忆.<br>&quot;转换&quot;这个词的含义非常广泛,在SQL中主要有两层意思.一是<strong><em>数据类型的转换</em></strong>,简称&quot;<strong><em>类型转换</em></strong>&quot;,在英语中称为cast.另一层意思是<strong><em>值的转换</em></strong>.</p>
<h5>CAST--&gt; 类型转换</h5>
<pre><code>CAST语法结构:
CAST(转换前的值 AS 想要转换的数据类型)
</code></pre><p>进行类型转换需要使用CAST函数<br>之所以需要进行数据类型转换,是因为可能会插入与表中数据类型不匹配的数据,或者在进行运算时,由于数据类型不一致发生了错误,又或者是进行自动类型转换造成了处理速度的低下.这些时候都需要事前进行数据类型转换.</p>
<pre><code>案例:将字符串类型转换为数据类型
SELECT CAST(&#39;0001&#39; AS INTEGER) AS int_col;
执行结果:
int_col
-------
    1
</code></pre><p>将字符串类型转换为日期类型</p>
<pre><code>语句: SELECT CAST(&#39;2009-12-14&#39; AS DATE) AS date_col;
执行结果:
date_col
 ------
2009-12-14
</code></pre><p>从上述结果可以看到,将字符串类型转换为证书类型时,去掉前面的&quot;000&quot;之后就可以转换为证书了.但是将字符串转换为日期类型时,从结果并不能看出数据发生了什么变化,理解起来也比较困难.从中我们也可以看出,类型转换其实并不是为了方便用户使用而开发的功能,而是为了方便DBMS内部处理而开发的功能.</p>
<h5>COALESCE--&gt;将NULL转换为其他值</h5>
<pre><code>语法结构:
COALESCE(数据1,数据2,数据3...)
</code></pre><p>COALESCE 函数是SQL特有的函数.该函数会返回可变参数(参数的个数并不固定,可以自由设定个数的参数)中左侧开始第一个不是NULL的值.参数个数是可变的,因此可以根据需要无限增加.<br>其实转换函数的使用还是非常频繁的.在SQL语句中将NULL转换为其他值时就会用到转换函数.就像之前我们学习的那样,运算或者函数中含有NULL时,结果全都会变成NULL.能够避免这种结果的函数就是COALESCE</p>
<pre><code>案列: 将NULL转换为其他值
SELECT COALESCE(NULL, 1)    AS col_1,
 COALESCE(NULL,&#39;test&#39;,NULL) AS col_2,
 COALESCE(NULL,NULL,&#39;2009-11-01&#39;) AS col_3;
执行结果:
col_1    col_2     col_3
  1        test    2009-11-01
</code></pre><p>我们再使用SampleStr中的列举例</p>
<pre><code>SELECT COALESCE(str2,&#39;Null&#39;)
FROM SampleStr;
执行结果:    //其实就是用&#39;NULL&#39; 来替换掉NULL
COALESCE
-------
rt
def
太浪
&#39;Null&#39;
xyz
&#39;NULL&#39;
&#39;NULL&#39;
&#39;NULL&#39;
abc
abc
i
</code></pre><p>这样,即使包含NULL的列,也可以通过COALESCE 函数转换为其他值之后再应用到函数或者运算当中,这样就不会再是 NULL了.</p>
<h3>6-2谓词</h3>
<h4>什么是谓词</h4>
<p>本节我们将学习SQL的抽出条件中不可或缺的工具--&gt;谓词(predicate).虽然之前我们没有提及谓词这个概念,但其实我们已经使用过了.如,=、&lt;、&gt;、&lt;&gt;等比较运算符,其正式名称就是比较谓词.<br>谓词,通俗来讲就是6-1节中介绍的函数中的一种,是需要满足特定条件的函数.该条件就是&quot;<strong><em>返回值是真值</em></strong>&quot;.对通常的函数来说,返回值有可能是数字、字符串或者日期等等,但是谓词的返回值全都是真值(TRUE/FALSE/UNKNOWN),这也是谓词和函数的最大区别.<br>本节将会介绍一下谓词</p>
<ul>
<li>LIKE</li><li>BETWEEN</li><li>IS NULL,IS NOT NULL</li><li>IN</li><li>EXISTS</li></ul>
<h4>LIKE谓词--&gt;字符串的部分一致查询</h4>
<p>截止目前,我们使用字符串作为查询条件的例子中,使用的都是=.这里的 = 只有在字符串完全一致时才为真.与之襄樊,<strong><em>LIKE谓词</em></strong>更加模糊一些,当需要进行字符串的<strong><em>部分一致查询</em></strong>时需要使用该谓词.<br>部分一致大体可以分为前方一致、中间一致和后方一致三种类型.截下来我们一起看看具体示例.</p>
<p>首先创建一张SampleLike表</p>
<pre><code>CREATE TABLE SampleLike
( strcol VARCHAR(6) NOT NULL,
 PRIMARY KEY (strcol));
BEGIN TRANSACTION;

INSERT INTO SampleLike (strcol) VALUES (&#39;abcddd&#39;);
INSERT INTO SampleLike (strcol) VALUES (&#39;dddabc&#39;);
INSERT INTO SampleLike (strcol) VALUES (&#39;abcdd&#39;);
INSERT INTO SampleLike (strcol) VALUES (&#39;ddabc&#39;);
INSERT INTO SampleLike (strcol) VALUES (&#39;abddc&#39;);

COMMIT;
</code></pre><p>创建完成的表如下:</p>
<pre><code>strcol
------
abcddd
dddabc
abcdd
ddabc
abddc
</code></pre><p>想要从表中读取出包含字母&quot;ddd&quot;的记录时,可能会得到前方一致、中间一致、和后方一致等不同的结果.</p>
<ul>
<li><strong>前方一致:选取出&quot;dddabc&quot;</strong><br>所谓前方一致,就是选出作为查询条件的字符串(这里是&quot;ddd&quot;)与查询对象字符串起始部分相同的记录的查询方法.</li><li><strong>中间一致:选取出&quot;abcddd&quot;、&quot;dddabc&quot;、&quot;abdddc&quot;</strong><br>所谓中间一致,就是选取出查询对象字符串中含有作为查询条件的字符串(这里是&quot;ddd&quot;)的记录的查询方法.无论该字符串出现在对象字符串的最后还是中间都没关系.</li><li><strong>后方一致:选取出&quot;abcddd&quot;</strong><br>后方一致与前方一致相反,也就是选取出作为查询条件的字符串(这里是&quot;ddd&quot;)</li></ul>
<h5>进行前方一致查询</h5>
<pre><code>使用LIKE进行前方一致查询:
SELECT *
 FROM SampleLike
WHERE strcol LIKE &#39;ddd%&#39;;
执行结果:
strcol
 ---
dddabc
</code></pre><p><strong><em>其中的&quot;%&quot; 是代表&quot;0字符以上的任意字符串&quot;的特殊符号.本例中代表&quot;以ddd开头的所有字符&quot;</em></strong><br>这样我们就可以用LIKE和模式匹配来进行查询了.</p>
<h5>中间一致查询</h5>
<p>接下来我们看一个中间一致的例子,查询出包含字符串&quot;ddd&quot;的记录</p>
<pre><code>SELECT *
 FROM SampleLike
WHERE strcol LIKE &#39;%ddd%&#39;;
执行结果:
strcol
------
abcddd
dddabc
abdddc
</code></pre><p>在字符串的起始和结束位置加上%,就能取出&quot;包含ddd的字符串&quot;了.</p>
<h5>最后一致查询</h5>
<p>最后我们来看一下后方一致查询,选取出以字符串&quot;ddd&quot;结尾的记录</p>
<pre><code>SELECT *
FROM SampleLike
WHERE strcol LIKE &#39;%ddd&#39;;
执行结果:
strcol
------
abcddd
</code></pre><p>通过上述结果我们可以发现前方一致和后方一致正好相反.<br>此外,我们还可以使用_(下划线)来代替%,与%不同的是其代表了&quot;任意1个字符&quot;,比如下面的案例</p>
<pre><code>选取出strcol列的值为&quot;abc+任意两个字符&quot;的记录
SELECT *
 FROM SampleLike
WHERE strcol LIKE &#39;abc__&#39;;
执行结果为:
strcol
------
abcdd
</code></pre><p>&quot;abcddd&quot;也是以&quot;abc&quot;开头的字符串,但其中的&quot;ddd&quot;是3个字符,所以不满足__所指的2个字符的条件.因此该字符串并不在查询结果之中.</p>
<h4>BETWEEN谓词--&gt;范围查找</h4>
<p>使用BETWEEN可以进行范围查询.该谓词与其他谓词或者函数的不同之处在于它使用了3个参数.例如从shohin表中读取出销售单价(hanbai_tanka)为100日元到1000日元之间的商品时,可以使用下面的代码</p>
<pre><code>SELECT Shoin_mei,hanbai_tanka
FROM Shohin
WHERE hanbai_tanka BETWEEN 100 AND 1000;
执行结果:
shohin_mei    hanbai_tanka
------------------------
T恤    1000
打孔器    500
叉子    500
擦菜板    880
圆珠笔    100
</code></pre><p>BETWEEN的特点是结果中会包含100和1000这两个临界值.如果不想让结果中包含临界值,那就必须使用&lt;和&gt;,如下面的代码</p>
<pre><code>选取出销售单价为101-999日元的商品
SELECT shohin_mei,hanbai_tanka
FROM Shohin
WHERE hanbai_tanka &gt;100 
AND hanbai_tanka &lt;1000;
执行结果:
shohin_mei    hanbai_tanka
------------------------
打孔器    500
叉子    500
擦菜板    880
</code></pre><p>执行结果中不再包含100和1000</p>
<h4>IS NULL、IS NOT NULL --&gt; 判断是否为NULL</h4>
<p>为了选取出某些值为NULL的列的数据,不能使用=,而只能使用特定的谓词IS NULL,如下:</p>
<pre><code>选取出进货单价为NULL的商品
SELECT shohin_mei,shiire_tanka
FROM Shohin
WHERE shiire_tanka IS NULL;
执行结果:
shohin_mei    shiire_tanka
----------+-------------
叉子      |    
圆珠笔      |
</code></pre><p>与此相反,想要选取NULL以外的数据时,需要使用IS NOT NULL,代码如下:</p>
<pre><code>选取进货单价(shiire_tanka)不为NULL的商品
SELECT shohin_mei,shiire_tanka
FROM Shohin
WHERE shiire_tanka IS NOT NULL;
执行结果:
shohin_mei    shiire_tanka
----------+-------------
T恤          |        500
打孔器      |        320
运动T恤      |        2800
菜刀      |        2800
高压锅      |        5000
擦菜板      |        790
</code></pre><h4>IN谓词--&gt;OR的简便用法</h4>
<p>截下来我们思考一下如何选取出进货单价(shiire_tanka)为320元、500元、5000元的商品时.我们可以之前学过OR的用法,代码如下</p>
<pre><code>通过OR指定多个进货单价进行查询:
SELECT shohin_mei,shiire_tanka
FROM Shohin
WHERE shiire_tanka = 320
OR shiire_tanka = 500
OR shiire_tanka = 5000;
执行结果:
shohin_mei    shiire_tanka
----------+-------------
T恤          |     500
打孔器      |     320
高压锅      |     5000
</code></pre><p>虽然上述方法没有问题,但是存在一点不足支出,那就是随着希望选取的对象越来越多,SQL语句也会越来越长,阅读起来也会越来越困难.这是我们就可以使用<strong>IN谓词</strong>&quot;IN (值1,值2...)&quot;来替换上述的语句</p>
<pre><code>通过IN 来指定多个进货单价进行查询:
SELECT shohin_mei,shiire_tanka
FROM Shohin
WHERE shiire_tanka IN ( 320, 500, 5000);
执行结果:
shohin_mei    shiire_tanka
----------+-------------
T恤          |     500
打孔器      |     320
高压锅      |     5000
</code></pre><p>反之,希望选取出&quot;进货单价不是320元、500元、5000元&quot;的商品时,可以通过<strong>NOT IN</strong>来实现</p>
<pre><code>使用NOT IN进行查询时指定多个除外的进货单价进行查询:
SELECT Shohin_mei,shiire_tanka
FROM Shohin
WHERE shiire_tanka NOT IN ( 320, 500, 5000);
执行结果为:
shohin_mei    shiire_tanka
----------+-------------
运动T恤      |        2800
菜刀      |        2800
擦菜板      |        790
</code></pre><p>但需要注意的是,在使用IN和NOT IN时是<strong>无法选取出 NULL数据的</strong>.实际结果也是如此,上述两组结果中都不包含进货单价为NULL的叉子和圆珠笔.NULL终究还是需要使用IS NULL 和IS NOT NULL来进行判断.</p>
<h4>使用子查询作为IN谓词的参数</h4>
<h5>IN 和子查询</h5>
<p>IN谓词(NOT IN谓词) 具有其他谓词所没有的使用方法.那就是可以使用子查询作为其参数来使用.我们在之前章节中学习了子查询就是SQL内部生成的表.因此也可以说&quot;能够将表作为IN的参数&quot;.同理,我们还可以说&quot;能够将视图作为IN的参数&quot;.<br>为了掌握详细的使用方法,让我们再添加一张新表吧.之前我们使用的全部都是显示商品在库一览信息的Shohin(商品)表,但现实中这些商品可能会在个别的商店中进行销售.下面我们创建一个新表显示出哪些商店销售哪些商品的TenpoShohin(商店商品).<br>表的内容如下:</p>
<table>
<thead>
<tr>
<th>tenpo_id(商店)</th>
<th>tenpo_mei(商店名称)</th>
<th>shohin_id(商品编号)</th>
<th>suryo(数量)</th>
</tr>
</thead>
<tbody>
<tr>
<td>000A</td>
<td>东京</td>
<td>0001</td>
<td>30</td>
</tr>
<tr>
<td>000A</td>
<td>东京</td>
<td>0002</td>
<td>50</td>
</tr>
<tr>
<td>000A</td>
<td>东京</td>
<td>0003</td>
<td>15</td>
</tr>
<tr>
<td>000B</td>
<td>名古屋</td>
<td>0002</td>
<td>30</td>
</tr>
<tr>
<td>000B</td>
<td>名古屋</td>
<td>0003</td>
<td>120</td>
</tr>
<tr>
<td>000B</td>
<td>名古屋</td>
<td>0004</td>
<td>20</td>
</tr>
<tr>
<td>000B</td>
<td>名古屋</td>
<td>0006</td>
<td>10</td>
</tr>
<tr>
<td>000B</td>
<td>名古屋</td>
<td>0007</td>
<td>40</td>
</tr>
<tr>
<td>000C</td>
<td>大阪</td>
<td>0003</td>
<td>20</td>
</tr>
<tr>
<td>000C</td>
<td>大阪</td>
<td>0004</td>
<td>50</td>
</tr>
<tr>
<td>000C</td>
<td>大阪</td>
<td>0006</td>
<td>90</td>
</tr>
<tr>
<td>000C</td>
<td>大阪</td>
<td>0007</td>
<td>70</td>
</tr>
<tr>
<td>000D</td>
<td>福冈</td>
<td>0001</td>
<td>100</td>
</tr>
</tbody>
</table>
<p>商店和商品组合成一条记录.例如,该表显示出东京店销售的商品有001(T恤)、002(打孔器)、003(打孔器)三种.<br>创建该表的代码如下:</p>
<pre><code>创建tenpoShohin表的语句:
CREATE TABLE tenpoShohin
(tenpo_id  CHAR(4) NOT NULL,
tenpo_mei  VARCHAR(200) NOT NULL,
shohin_id  CHAR(4) NOT NULL,
suryo INTEGER NOT NULL,
PRIMARY KEY (tenpo_id,shohin_id));
</code></pre><p>上面语句中指定了2列作为主键(primary key).这样做的目的当然还是为了区分表中每一行数据,由于单独使用商店编号(tempo_mei)或者商品编号(shohin_mei)不能满足要求,所以需要对商店和商品进行组合.<br>实际上如果只使用商店编号进行区分,那么指定&quot;000A&quot;作为条件能查出3行数据.而单独使用商品编号进行区分的话,&quot;0001&quot;也会查出两行数据.都无法恰当区分每行数据.<br>下面我们将向tenpoShohin表中插入数据:</p>
<pre><code>BEGIN TRANSACTION;

INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000A&#39;,&#39;东京&#39;,&#39;0001&#39;,30 );
INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000A&#39;,&#39;东京&#39;,&#39;0002&#39;,50 );
INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000A&#39;,&#39;东京&#39;,&#39;0003&#39;,15 );
INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000B&#39;,&#39;名古屋&#39;,&#39;0002&#39;,30 );
INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000B&#39;,&#39;名古屋&#39;,&#39;0003&#39;,120 );
INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000B&#39;,&#39;名古屋&#39;,&#39;0004&#39;,20 );
INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000B&#39;,&#39;名古屋&#39;,&#39;0006&#39;,10 );
INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000B&#39;,&#39;名古屋&#39;,&#39;0007&#39;,40 );
INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000C&#39;,&#39;大阪&#39;,&#39;0003&#39;,20 );
INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000C&#39;,&#39;大阪&#39;,&#39;0004&#39;,520 );
INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000C&#39;,&#39;大阪&#39;,&#39;0006&#39;,90 );
INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000C&#39;,&#39;大阪&#39;,&#39;0007&#39;,70 );
INSERT INTO tenpoShohin (tenpo_id,tenpo_mei,shohin_id,suryO) VALUES (&#39;000D&#39;,&#39;福冈&#39;,&#39;0001&#39;,100 );

COMMIT;
</code></pre><p>这样我们就完成了全部准备工作,下面我们一起看看IN谓词中使用子查询的SQL写法<br>首先读取出&quot;大阪店(000C)在售商品(shohin_id)的销售单价(hanbai_tanka)&quot;<br>TenpoShohin(商店商品)表中大阪店的在售商品很容易就能找出,有如下4种:</p>
<ul>
<li>运动T恤(商品编号:0003)</li><li>菜刀(商品编号:0004)</li><li>叉子(商品编号:0006)</li><li>擦菜板(商品编号:0007)</li></ul>
<p>结果自然也应该是这样:</p>
<pre><code>shohin_mei | hanbaitanka
-----------+------------
运动T恤     |        4000
菜刀        |        3000
叉子        |         500
擦菜板      |         880
</code></pre><p>得到上述结果时,我们应该已经完成了如下两个步骤:</p>
<ol>
<li>从TenpoShohin表中选取出在大阪店(tenpo_id = &#39;000C&#39;)中销售的商品(shohin_id).</li><li><p>从Shohin表中选取出通过1得到的商品(shohin_id)的销售单价(hanbai_tanka).<br>SQL也是如此,同样要分两步来完成.首先,第一步如下:</p>
<pre><code>SELECT shohin_id
FROM TenpoShohin
WHERE tenpo_id = &#39;000C&#39;;
</code></pre><p>因为大阪店的商店编号(tenpo_id)是&quot;000C&quot;,所以我们可以将其作为条件写在WHERE子句中.截下来,我们就可以把上述的SELECT语句作为第二部中的条件来使用了.<br>最终得到的SELECT语句如下:</p>
<pre><code>读取出&quot;大阪店(000C)在售商品(shohin_id)的销售单价(hanbai_tanka)&quot;
SELECT shohin_mei,hanbai_tanka
FROM Shohin
where Shohin_id IN (SELECT shohin_id 
                 FROM TenpoShohin
                 WHERE tenpo_id = &#39;000C&#39;);
执行结果:
shohin_mei|hanbai_tanka
----------+------------
运动T恤        4000
菜刀        3000
叉子        500
擦菜板        880
</code></pre><p>如第5章所述,子查询是从内层开始执行的.因此该SELECT语句也是从内层和的子查询开始执行,然户像下面这样展开</p>
<pre><code>--子查询展开后的结果
SELECT shohin_mei,hanbai_tanka
FROM shohin
WHERE shohin_id IN (&#39;0003&#39;,&#39;0004&#39;,&#39;0006&#39;,&#39;0007&#39;);
</code></pre><p>这样就转换成我们之前学习过的IN的用法了,但是很多人可能会产生这样的疑问,既然我们可以用IN谓词可以查到我们为什么还要用子查询呢?<br>这是因为TenpoShohin(商店商品)表不是不是一成不变的.实际上由于各个商店销售的商品都在不断发生变化,所以TenpoShohin表内大阪店销售的商品也会发生变化.如果SELECT语句中没有使用子查询的话,一旦商品发生了改变,那么SELECT语句也不得不进行修改.而且这样的修改工作会变得没完没了.<br>反之,如果在SELECT语句中使用了子查询,那么即使数据发生了变更,还可以继续使用同样的SELECT语句,这样也减少了我们的常规作业(单纯的重复操作).<br>像这样可以完美对数据变更的程序称为&quot;易维护程序&quot;,或者&quot;免维护程序&quot;.</p>
<h5>NOT IN和子查询</h5>
<p>IN 的否定形式NOT IN同样可以使用子查询作为参数,其语法也和IN完全一样.</p>
<pre><code>使用子查询作为NOT IN 的参数
SELECT shohin_mei,hanbai_tanka 
FROM shohin 
WHERE shohin_id NOT IN (select shohin_id 
                     FROM TenpoShohin
                     WHERE tenpo_id = &#39;000A&#39;);
</code></pre><p>上面的代码是要选取的&quot;在东京店(000A)以外销售的商品(shohin_id)的销售单价(hanbai_tanka)&quot;.&quot;NOT IN&quot;代表了&quot;以外&quot;这样的否定含义.<br>我们也可看一下该SQL语句的执行步骤.因为还是首先执行子查询,所以会得到一下结果.</p>
<pre><code>--执行子查询
SELECT shohin_mei,hanbai_tanka
FROM Shohin
WHERE shohin_id NOT IN (&#39;0001&#39;,&#39;0002&#39;,&#39;0003&#39;);
</code></pre><p>之后就简单了,上述语句应该会返回0001-0003以外的结果.</p>
<pre><code>shohin_mei|hanbai_tanka
----------+------------
菜刀      |        3000
高压锅      |        6800
叉子      |        500
擦菜板      |        880
圆珠笔      |        100
</code></pre><h4>EXIST谓词</h4>
<p>本节最后我们圩西一下EXIST谓词.将它放到最后进行学习的原因有3点:</p>
</li><li><p>EXIST的使用方法与之前的都不同</p>
</li><li>语法理解起来比较困难</li><li>实际上即使不使用EXIST,基本也可以用IN(或者NOT IN)来代替.</li></ol>
<p>理由1和2都说明EXIST是使用方法特殊而难以理解的谓词.特别是使用否定形式NOT EXIST的SELECT语句,即使是DB工程师也常常无法迅速理解.此外,如理由3所述,由于使用IN作为替代的情况非常多(尽管不能完全替代让人有些伤脑筋),很多人虽然记住了使用方法但还是不能实际运用.<br>但是,如果大家能够熟练使用EXIST谓词的话,就能体会到它极大的便利性.</p>
<h5>EXIST谓词的使用方法</h5>
<p>一言以蔽之,谓词的作用就是&quot;判断是否存在满足某种条件的记录&quot;.如果存在这样的记录就返回真(TRUE),如果不存在就返回假(FALSE).EXIST(存在)谓词的主语是记录.<br>我们继续使用前一节的&quot;IN和子查询&quot;中的示例,使用EXIST选取出&quot;大阪店(000C)在售商品(shohin_id)的销售单价(hanbai_tanka)&quot;.</p>
<pre><code>使用EXIST选取出&quot;大阪店(000C)在售商品(shohin_id)的销售单价(hanbai_tanka)&quot;
SELECT shohin_mei,hanbai_tanka
FROM shohin AS S
WHERE EXISTS (SELECT *
            FROM tenposhohin AS TS
            WHERE TS.tenpo_id = &#39;000C&#39;
            AND S.shohin_id = TS.shohin_id);
执行结果:
shohin_mei|hanbai_tanka
----------+------------
运动T恤      |    4000
菜刀      |    3000
叉子      |    500
擦菜板      |    880
</code></pre><h6>EXIST的参数</h6>
<p>之前我们学过的谓词,基本都是&quot;列LIKE 字符串&quot; 或者&quot;列BETWEEN值1 AND 值2&quot;这样需要指定2个以上的参数.而EXIST的左侧并没有任何参数.很奇妙吧!这是因为EXIST是只有1个参数的谓词.EXIST只需要在右侧书写一个参数.该参数通常都会是一个子查询.<br>在这个情况下,</p>
<pre><code>(SELECT * 
FROM TenpoShohin AS TS
WHERE TS.tenpo_id = &#39;000C&#39;
AND TS.shohin_id = S.shohin_id)
</code></pre><p>这样的子查询就是唯一的参数.确切地说,由于通过条件&quot;TS.shohin_id = S.shohin_id&quot;将Shohin表和TenpoShohin表进行了联接,所以作为参数的是关联子查询.EXIST通常都会使用关联子查询作为参数.</p>
<ul>
<li>法则6-1 通常指定关联子查询作为EXIST的参数.</li></ul>
<h6>子查询中的SELECT *</h6>
<p>可能我们会觉得子查询中的SELECT * 稍微有些不同,就像我们之前学到的那样,由于EXIST只关心记录是否存在,所以返回哪些列都没有关系.EXIST是用来判断是否存在满足子查询中WHERE子句指定条件&quot;商店编号(tenpo_id)为&#39;000C&#39;,商品(Shohin)表和商店商品(TenpoShohin)表中商品编号(Shohin_id)相同&quot;的记录,只有存在这样的记录时才返回真(TRUE)的谓词.<br>因此即使写成下面这样,结果也不会变化</p>
<pre><code>写成下面这样,结果也不会变化:
SELECT shohin_mei,hanbai_tanka
FROM shohin AS S
WHERE EXISTS (SELECT 1    //此处可以书写适当的常数
            FROM tenposhohin AS TS
            WHERE TS.tenpo_id = &#39;000C&#39;
            AND S.shohin_id = TS.shohin_id);
</code></pre><p>我们可以把在EXIST的子查询中书写SELECT * 当做SQL的一种习惯.</p>
<ul>
<li>法则6-2 作为EXIST参数的子查询中常会使用SELECT *</li></ul>
<h6>使用NOT EXIST替换NOT IN</h6>
<p>就像EXIST 可以用来替换IN一样,NOT IN也可以用NOT EXIST来替换.下面就让我们使用NOT EXIST来编写一条SELECT 语句,读取出&quot;东京店(000A)在售之外的商品(Shohin_id)的销售单价(hanbai_tanka)&quot;</p>
<pre><code>东京店(000A)在售之外的商品(Shohin_id)的销售单价(hanbai_tanka)
SELECT shohin_mei,hanbai_tanka
FROM Shohin AS S
WHERE NOT EXISTS (SELECT *
                 FROM TenpoShohin AS TS
                 WHERE tenpo_id = &#39;000A&#39;
                 AND TS.shohin_id = S.shohin_id);
执行结果:
shohin_mei|hanbai_tanka
----------+------------
菜刀      |    3000
高压锅      |    6800
叉子      |    500
擦菜板      |    880
圆珠笔      |    100
</code></pre><p>NOT EXIST与EXIST 相反,当&quot;不存在&quot;满足子查询中指定条件的记录时返回值真(TRUE).<br>将IN和EXIST的SELECT语句进行比较,会得到怎样的结果呢.可能大家都觉得IN理解起来要容易一些.笔者也认为没有必要勉强使用EXIST.因为EXIST拥有IN所不具有的便利性,严格来说两者并不相同,还是希望我们能掌握这两种谓词的使用方法.</p>
<h3>6.3 CASE表达式</h3>
<h4>什么是CASE表达式</h4>
<p>本节将要学习的CASE表达式,和&quot;1+1&quot; 或者&quot;120/4&quot; 这样的表达式一样,是一种运行运算的功能.这就以为这CASE表达式也是函数的一种.它是SQL中数一数二的重要功能,希望我们能在这里好好学习和掌握.<br>CASE表达式,正如CASE(情况)这个次的含义所示,是在区分情况是使用的.这种情况的区分在程序中通常称为&quot;<strong><em>(条件)分歧</em></strong>&quot;.</p>
<h4>CASE表达式语法</h4>
<p>CASE表达式的语法分为<strong><em>简单表达式</em></strong>和<strong><em>搜索CASE表达式</em></strong>两种.<br>但是,由于搜索CASE表达式包含了简单CASE表达式的全部功能,因此本节只会介绍搜索CASE表达式.想要了解简单CASE表达式的话,可以参考本节末尾的&quot;简单表达式&quot;<br>下面我们就来学习搜索CASE表达式</p>
<pre><code>搜索CASE表达式
CASE WHEN &lt;判断表达式&gt; THEN &lt;表达式&gt;
     WHEN &lt;判断表达式&gt; THEN &lt;表达式&gt;
     WHEN &lt;判断表达式&gt; THEN &lt;表达式&gt;
     WHEN &lt;判断表达式&gt; THEN &lt;表达式&gt;
        ...
    ELSE &lt;表达式&gt;
END
</code></pre><p>WHEN 子句中华的&lt;判断表达式&gt;就是类似&quot;列 = 值&quot;这样,返回值为真值(TRUE/FALSE/UNKNOWN)的表达式.我们也可以将其看做使用=、!=、或者LIKE、BETWEEN等谓词编写出来的表达式.<br>CASE表达式会从对最初的WHEN子句中的&lt;判断表达式&gt;进行判断开始执行.所谓&quot;判断&quot;,就是要调查该表达式的真值是什么.如果结果为真&quot;TRUE&quot;,那么就返回<strong><em>THEN子句</em></strong>中的表达式,CASE表达式的执行到此为止.如果结果不为真,那么就跳转到下一条WHEN子句的判断中.如果直到最后的WHEN子句为止返回结果都不为真,那么就返回<strong><em>ELSE</em></strong>中的表达式,执行终止.<br>从CASE表达式名称中的&quot;表达式&quot;我们也能看出来,上述这些整体构成一个表达式.并且由于表达式最终会返回一个值,因此CASE表达式在SQL语句执行时,也会转化为一个值.虽然会使用分支众多的CASE便携数十行代码的情况也并不少见,但是无论多么庞大的CASE表达式,最后也只会返回类似&quot;1&quot;或者&quot;Mr.Aphey&quot;这样简单的值.</p>
<h4>CASE表达式的使用方法</h4>
<p>那么,我们现在来学习CASE表达式的具体使用方法.例如我们来考虑这样一种情况,现在Shohin(商品)表中包含衣服、办公用品和厨房用具3种商品类型.请大家考虑一下怎么样才能得到如下结果呢?</p>
<pre><code>A:衣服
B:办公用品
C:厨房用具
</code></pre><p>因为表中的记录并不包含&quot;A:&quot;或者&quot;B:&quot;这样的字符串,所以需要在SQL中进行添加.我们可以使用前面学过的字符串连接函数&quot;||&quot;来完成这项工作.<br>剩下的问题就是怎样正确地将&quot;A:&quot;&quot;B:&quot;&quot;C:&quot;与记录结合起来.这是我们就可以使用CASE表达式来实现这样的要求了</p>
<pre><code>通过CASE表达式将A-C的字符串假如到商品分类中
SELECT shohin_mei,
        CASE WHEN shohin_bunrui = &#39;衣服&#39;
        THEN &#39;A:&#39; || shohin_bunrui
        WHEN shohin_bunrui = &#39;办公用品&#39;
        THEN &#39;B:&#39; || shohin_bunrui
        WHEN shohin_bunrui = &#39;厨房用具&#39;
        THEN &#39;C:&#39; || shohin_bunrui
        ELSE NULL
    END AS abc_shohin_bunrui
FROM shohin;
执行结果:
shohin_mei|shohin_bunrui
----------+-------------
T恤          |  A:衣服
打孔器      |  B:办公用品
运动T恤      |  A:衣服
菜刀      |  C:厨房用具
高压锅      |  C:厨房用具
叉子      |  C:厨房用具
擦菜板      |  C:厨房用具
圆珠笔      |  B:办公用品
</code></pre><p>6行CASE表达式写代码最后相当于一列(abc_shohin_bunrui)而已,也许会让人感到吃惊,与商品种类(shohin<em>bunrui)的名称相对应,CASE表达式中包含了三条WHEN子句分支.最后的&quot;ELSE NULL&quot;代表了&quot;上述情况之外时返回NULL&quot;的意思.ELSE子句指定了不满足WHEN子句中条件的记录应该执行何种操作.NULL之外的其他值或者表达式也可以写在ELSE子句之中.但由于现在表中包含的商品种类只有3种,因此实际上有没有ELSE子句都是一样的.<br>ELSE子句也可以省略不写,这时会自动默认为&quot;<em>_ELSE NULL</em></em>&quot;.但为了防止有人漏读,所以还是希望大家能够写明ELSE子句.</p>
<ul>
<li>法则6-3 虽然CASE表达式中的ELSE子句可以省略,但还是希望大家不要省略.<br>此外,CASE表达式最后的&quot;END&quot;是不能省略的,请大家特别注意不要遗漏.忘记书写END会发生语法错误,这也是初学者最容易犯的错误.</li><li>法则6-4 CASE表达式中的END不能省略<h5>CASE表达式的书写位置</h5>
CASE表达式的便利之处就在于它是一个表达式.之所以这么说,是因为表达式可以书写在任意位置.也就像&quot;1+1&quot; 这样写在什么位置都可以的意思.例如,我们可以利用CASE表达式将下面的SELECT语句结果中的行和列进行互换.<pre><code>sum_tanka_ihuku| sum_tanka_kitchen| sum_tanka_jimu
---------------+------------------+---------------
      5000   |            11180 |            600
</code></pre>上述结果是根据商品种类计算出的销售单价的合计值,通常我们将商品种类列作为GROUP BY子句的聚合键来使用,但是这样得到的结果会以&quot;行&quot;的形式输出,而无法以列的形式进行排列<pre><code>通常使用GROUP BY也无法实现行列转换
SELECT shohin_bunrui
  SUM(hanbai_tanka) AS sum_tanka_ihuku
FROM Shohin
GROUP BY shohin_bunrui;
执行结果:
shohin_bunrui|sum_tanka
-------------+---------
衣服         |  5000
办公用品         |  600
厨房用具         |  11180
</code></pre>我们可以使用CASE表达式进行行列转换<pre><code>--对按照商品种类计算出的销售单价合计值进行行列转换
SELECT SUM(CASE WHEN shohin_bunrui = &#39;衣服&#39;
          THEN hanbai_tanka ELSE 0 END) AS sum_tanka_ihuku,
      SUM(CASE WHEN shohin_bunrui = &#39;厨房用具&#39;
          THEN hanbai_tanka ELSE 0 END) AS sum_tanka_kitchen,
      SUM(CASE WHEN shohin_bunrui = &#39;办公用品&#39;
          THEN hanbai_tanka ELSE 0 END) AS sum_tanka_jimu
FROM shohin;
执行结果:
sum_tanka_ihuku| sum_tanka_kitchen| sum_tanka_jimu
---------------+------------------+---------------
      5000   |    11180         |      600
</code></pre>上述CASE表达式,在满足商品种类(Shohin_bunrui)为&quot;衣服&quot;或者&quot;办公用品&quot;等定值时,输出该商品的销售单价(hanbai_tanka),不满足时输出0.对该结果进行合计处理,就能得到特定商品种类的销售单价合计值了.<br>CASE 表达式在对SELECT语句的结果进行编辑时,能够发挥较大作用.<h4>专栏</h4>
<h5>简单CASE表达式</h5>
CASE表达式分为两种,一种是本节学习的&quot;搜索CASE表达式&quot;,另一种就是其简化形式----&quot;简单CASE表达式&quot;.<br>简单CASE表达式比搜索CASE表达式简单,但是会收到条件的约束.因此,通常情况下都会使用搜索CASE表达式.再次我们简单了解一下简单CASE表达式的语法结构.<br>简单CASE表达式的语法如下所示.<br>语法6-A 简单CASE表达式<pre><code>CASE &lt;表达式&gt;
WHEN &lt;表达式&gt; THEN&lt;表达式&gt;
WHEN &lt;表达式&gt; THEN&lt;表达式&gt;
WHEN &lt;表达式&gt; THEN&lt;表达式&gt;
...
ELSE &lt;表达式&gt;    
END
</code></pre>与搜索CASE表达式一样,简单CASE表达式也是从最初的WHEN子句开始进行,逐一判断每个WHEN子句知道返回真值为止.此外,没有能够返回真值的WHEN子句时,也会返回ELSE子句指定的表达式.两者的不同之处在于,简单CASE表达式最初的&quot;CASE&lt;表达式&gt;&quot; 也会作为判断的对象.<br>下面我们看一个例子,分别使用搜索CASE表达式和简单CASE表达式<br>```<br>--使用搜索CASE表达式,将字符串A~C添加到商品种类中<br>SELECT shohin_mei,<br>  CASE WHEN shohin_bunrui = &#39;衣服&#39;<pre><code>  THEN &#39;A:&#39; ||shohin_bunrui
  WHEN shohin_bunrui = &#39;办公用品&#39;
  THEN &#39;B:&#39; ||shohin_bunrui        
  WHEN shohin_bunrui = &#39;厨房用具&#39;
  THEN &#39;C:&#39; ||shohin_bunrui        
  ELSE NULL
</code></pre>  END AS abc_shohin_bunrui<br>FROM shohin;</li></ul>
<p>--使用简单CASE表达式<br>SELECT shohin_mei,<br>    CASE shohin_bunrui<br>        WHEN &#39;衣服&#39;    THEN &#39;A:&#39;||shohin_bunrui<br>        WHEN &#39;办公用品&#39;    THEN &#39;B:&#39;||shohin_bunrui<br>        WHEN &#39;厨房用具&#39;    THEN &#39;C:&#39;||shohin_bunrui<br>        ELSE NULL<br>    END AS abc_shohin_bunrui<br>FROM shohin;<br>像&quot;CASE shohin_mei&quot; 这样,简单CASE表达式在将想要判断的表达式(这里是列)书写过一次之后,<br>就无需在之后的WHEN子句中重复书写&quot;shohin_bunrui&quot;了.虽然看上去简化了书写,但是想要在WHEN<br>子句中指定不同列时,简单CASE表达式就无能为力了.</p>
<pre><code>## 第七章 集合运算
### 7-1 表的加减法
#### 什么是集合运算
本章我们要学习&quot;集合运算&quot;操作.在数学领域,&quot;集合&quot;表示&quot;(各种各样)事物的总和&quot;;在数据库领域,表示&quot;___记录的集合___&quot;.具体来说,表、视图和查询的执行结果都是&quot;记录的集合&quot;.
截止目前,我们已经学习了从表中读取数据以及插入数据的方法.所谓集合运算,就是对满足同一规则的记录进行的加减等&quot;四则运算&quot;.通过集合运算,可以得到两张表中记录的集合,或者是公共记录的集合,又或者是其中某张表记录的集合.像这样用来进行集合运算的运算符称为&quot;集合运算符&quot;.
#### 表的加法
首先介绍的是集合运算符是进行记录加法运算的UNION(并集).
在学习具体的使用方法之前,我们首先添加一张表.该表的结构与之前我们使用的Shohin(商品)表相同,只是表名变为Shohin2(商品2)
</code></pre><p>CREATE TABLE Shohin2<br>(shohin_id    char(4)    NOT NULL,<br>shohin_mei    varchar(100)    NOT NULL,<br>shohin_bunrui    varchar(32)    NOT NULL,<br>hanbai_tanka    INTEGER        ,<br>shiire_tanka    INTEGER        ,<br>torokubi        DATE        ,<br>PRIMARY KEY    (shohin_id));</p>
<pre><code>截下来,我们将下面的5跳记录插入到Shohin2表中.商品编号(shohin_id) 为&quot;0001&quot;~&quot;0003&quot;的商品之前Shohin表中的商品相同,而编号为&quot;0009&quot;的&quot;手套&quot;和&quot;0010&quot;的&quot;水壶&quot;是Shohin表中没有的商品
</code></pre><p>BEGIN TRANSACTION;<br>INSERT INTO Shohin2 VALUES (&#39;0001&#39;,&#39;T恤衫&#39;,&#39;衣服&#39;,1000,500,&#39;2009-09-20&#39;);<br>INSERT INTO Shohin2 VALUES (&#39;0002&#39;,&#39;打孔器&#39;,&#39;办公用品&#39;,500,320,&#39;2009-09-11&#39;);<br>INSERT INTO Shohin2 VALUES (&#39;0003&#39;,&#39;运动T恤&#39;,&#39;衣服&#39;,4000,2800,NULL);<br>INSERT INTO Shohin2 VALUES (&#39;0009&#39;,&#39;手套&#39;,&#39;衣服&#39;,800,500,NULL);<br>INSERT INTO Shohin2 VALUES (&#39;0010&#39;,&#39;水壶&#39;,&#39;厨房用具&#39;,2000,1700,&#39;2009-09-20&#39;);<br>COMMIT;</p>
<pre><code>这样,我们的准备工作就完成了.截下来,就让我们对上述两张表进行&quot;shohin表 + shohin2 表&quot;这样的加法计算吧.
</code></pre><p>使用UNION 对表进行加法运算<br>SELECT shohin_id, shohin_mei<br>FROM Shohin<br>UNION<br>SELECT shohin_id,shohin_mei<br>FROM shohin2;<br>执行结果:</p>
<h2>shohin_id| shohin_mei</h2>
<p>+-----------<br>0001     |    T恤衫<br>0002     |    打孔器<br>0003     |    运动T恤<br>0004     |    菜刀<br>0005     |    高压锅<br>0006     |    叉子<br>0007     |    擦菜板<br>0008     |    圆珠笔<br>0009     |    手套<br>0010     |    水壶</p>
<pre><code>上述结果包含了两张表中的全部商品(去除了重复的项目).
- 法则7-1 集合运算符会除去重复的记录
#### 集合运算的注意事项
其实结果中也可以包含重复的记录,在介绍这个方法之前,我们还是来学习一下使用集合运算符时的注意事项吧.不仅限于UNION,之后将要学习的所有运算符都要遵守这些注意是想.
##### 注意事项1--&gt;作为运算对象的记录的列数必须相同
例如,像下面这样,一部分记录包含2列,另一部分包含3列时会发生错误,无法进行加法运算.
</code></pre><p>--列数不一致时会发生错误,下面为错误代码<br>SELECT shohin_id,shohin_mei<br>FROM Shohin<br>UNION<br>SELECT shohin_id,shohin_mei,hanbai_tanka<br>FROM Shohin2<br>执行结果:报错<br>[2016-11-23 13:23:28] [42601] ERROR: each UNION query must have the same number of columns<br>  位置：54</p>
<pre><code>##### 注意事项2--&gt;作为运算对象的记录中列的类型必须一致
从左侧开始,相同位置上的列必须是同一数据类型.例如,下面的SQL语句,虽然列数相同,但是第2列的数据类型并不一致(一个是数值类型,一个是日期类型),因此会发生错误
</code></pre><p>--数据类型不一致时会发生错误<br>SELECT shohin_id,hanbai_tanka<br>FROM Shohin<br>UNION<br>SELECT shohin_id,torokubi<br>FROM Shohin2;<br>执行结果:报错<br>[2016-11-23 13:27:26] [42804] ERROR: UNION types integer and date cannot be matched<br>  位置：66</p>
<pre><code>一定要使用不同数据类型的列时,可以试用前面学过的类型转换函数CAST.
##### 注意事项3--&gt;可以使用任何SELECT语句,但是ORDER BY子句只能在最后使用1次
通过UNION进行并集运算时可以使用任何形式的SELECT语句.之前学过的WHERE、GROUP BY、HAVING等子句都可以使用.但是ORDER BY只能在最后使用一次
</code></pre><p>-- ORDER BY子句只在最后使用一次<br>SELECT shohin_id,shohin_mei<br>FROM Shohin<br>WHERE shohin_bunrui=&#39;厨房用具&#39;<br>UNION<br>SELECT shohin_id,shohin_mei<br>FROM Shohin2<br>WHERE shohin_bunrui=&#39;厨房用具&#39;<br>ORDER BY shohin_id<br>执行结果:</p>
<h2>shohin_id| shohin_mei</h2>
<p>+----------<br>0004     |    菜刀<br>0005     |    高压锅<br>0006     |    叉子<br>0007     |    擦菜板<br>0010     |    水壶</p>
<pre><code>#### 包含重复行的集合运算--&gt;ALL 选项
接下来我们学习在UNION的结果中保留重复行的语法.其实非常简单,只要在UNION后面添加ALL关键字就可以了.这里ALL选项,在UNION之外的集合运算符中同样可以使用
</code></pre><p>--保留重复行<br>SELECT shohin_id,shohin_mei<br>FROM Shohin<br>UNION ALL<br>SELECT shohin_id,shohin_mei<br>FROM shohin2;<br>执行结果:</p>
<h2>shohin_id| shohin_mei</h2>
<p>+-----------<br>0001     |    T恤衫<br>0002     |    打孔器<br>0003     |    运动T恤<br>0004     |    菜刀<br>0005     |    高压锅<br>0006     |    叉子<br>0007     |    擦菜板<br>0008     |    圆珠笔<br>0001     |    T恤衫<br>0002     |    打孔器<br>0003     |    运动T恤<br>0009     |    手套<br>0010     |    水壶</p>
<pre><code>- 法则7-2 在集合运算符中使用ALL选项,可以保留重复行.

#### 选取表中的公共部分(交集)--&gt;INTERSECT
下面学习的集合运算符在数学的四则运算中并不存在,其实也不是很难理解,那就是选取2个记录集合中的公共部分的INTERSECT(交集)
其语法和UNION完全一样
</code></pre><p>--INTERSECT语法,选取表中的公共部分<br>SELECT shohin_id,shohin_mei<br>FROM Shohin<br>INTERSECT<br>SELECT shohin_id,shohin_mei<br>FROM Shohin2<br>ORDER BY shohin_id;<br>执行结果:</p>
<h2>shohin_id| shohin_mei</h2>
<p>+-----------<br>0002     |    打孔器<br>0003     |    运动T恤</p>
<pre><code>我们可以发现,结果中只包含两张表中公共部分.
与使用AND可以选取出一张表中满足多个条件的公共部分不同,___INTERSECT应用于两张表,选取出它们当中的公共记录___.
其注意事项与UNION相同,我们在&quot;集合运算的注意是想&quot;和&quot;保留重复行的集合运算中&quot;希望保留重复行时同样需要INTERSECT ALL.
#### 记录的减法(差集)--&gt;EXCEPT
本节最后我们学习一下集合运算符就是进行减法运算的EXCEPT(差集).其语法也与UNION相同.
其意思是减去两张表的交集部分,被减数(EXCEPT上面的那张表)剩下来的部分.
</code></pre><p>--使用EXCEPT对记录进行减法运算<br>SELECT shohin_id,shohin_mei<br>FROM Shohin<br>EXCEPT<br>SELECT shohin_id,shohin_mei<br>FROM Shohin2<br>ORDER BY shohin_id;<br>执行结果:</p>
<h2>shohin_id| shohin_mei</h2>
<p>+-----------<br>0004     |    菜刀<br>0005     |    高压锅<br>0006     |    叉子<br>0007     |    擦菜板<br>0008     |    圆珠笔</p>
<pre><code>我们可以发现,结果中只包含了Shohin表的记录中除去___Shohin2表中记录___(Aphey备注:这里应该是两张表的共有部分.)的剩余部分.
EXCEPT有一点与UNION和INTERSECT不同,需要注意一下.那就是在减法运算中减数和被减数的位置不同,所得到的结果也不相同,4-2和2-4的结果也不一样.因此我们将之前SQL中的Shohin和Shohin2互换,就能得到下面的结果
</code></pre><p>--被减数和减数的位置不同,得到的结果也不同<br>SELECT shohin_id,shohin_mei<br>FROM shohin 2<br>EXCEPT<br>SELECT shohin_id,shohin_mei<br>FROM Shohin<br>ORDER BY shohin_id;<br>执行结果:</p>
<h2>shohin_id| shohin_mei</h2>
<p>+-----------<br>0009     |    手套<br>0010     |    水壶</p>
<pre><code>到此,对SQL提供的集合运算符的学习就结束了,大家可能会有&quot;怎么没有乘法和除法&quot;这样的疑问.关于乘法的相关内容,我们在下一节进行详细介绍.此外SQL中虽然也存在除法,但由于除法是比较难理解的运算,属于中级内容,在本章末尾的专栏会有一些介绍.
### 7-2联结(以列为单位对表进行联结)
#### 什么是联结
前面我们学习了UNION和INTERSECT等集合运算.这些集合运算的特征就是以___行方向___为单位进行操作.通俗来说就是进行这些集合运算时,会导致记录行数的增减.使用UNION会增加记录行数,而使用INTERSECT或者EXCEPT会减少记录行数.
但这些运算不会导致列数的改变.作为集合运算对象表的前提就是列数要一致.因此,运算结果不会导致列的增减.
本节将要学习的链接(JOIN)运算,简单来说就是将其他表中的列添加过来,进行&quot;添加列&quot;的运算.该操作通常用于无法从一张表中获取期望数据(列)的情况.截止目前,本书中出现的示例基本都是从一张表中选取数据,但实际上,期望得到的数据往往分散在不同的表之中.使用链接就可以从多张表(3张以上的表也没关系)中选取数据了.
SQL的联结根据其用途可以分为很多种类.这里需要掌握两种:内联结和外联结
#### 内联结--&gt;INNER JOIN
首先,我们来学习内联结,它是应用最广泛的联结运算.大家现在可以暂时忽略&quot;内&quot;这个字,之后会进行详细说明
本例中我们会继续使用Shohin表和第六章创建的TenpoShohin表.下面我们先看下这两张表的内容
___Shohin表:___

shohin\_id|shohin\_mei|shohin\_bunrui|hanbai\_tanka|shiire_tanka|torokubi
---|---|---|---|---|---
0001|    T恤       | 衣服|        1000|    500    |    2009-09-20
0002|    打孔器|    办公用品|    500    |    320    |    2009-09-11
0003|    运动T恤|    衣服|        4000|    2800|    NULL
0004|    菜刀|    厨房用具|    3000|    2800|    2009-09-20
0005|    高压锅|    厨房用具|    6800|    5000|    2009-01-15
0006|    叉子|    厨房用具|    500    |    NULL    |    2009-09-20
0007|    擦菜板|    厨房用具|    880    |    790    |    2008-04-28
0008|    圆珠笔|    办公用品|    100    |    NULL    |    2009-11-11

___TenpoShohin表:___

tenpo\_id(商店编号)|tenpo\_mei(商店名称)|shohin\_id(商品编号)|shohin\_mei(商品名称)
---|---|---|---
000A|    东京|    0001|    30
000A|    东京|    0002|    50
000A|    东京|    0003|    15
000B|    名古屋|    0002|    30
000B|    名古屋|    0003|    120
000B|    名古屋|    0004|    20
000B|    名古屋|    0006|    10
000B|    名古屋|    0007|    40
000C|    大阪|    0003|    20
000C|    大阪|    0004|    520
000C|    大阪|    0006|    90
000C|    大阪|    0007|    70
000D|    福冈|    0001|    100

对这两张表包含的列进行整理后结果如下所示

项目名称|Shohin|TenpoShohin
---|---|---
商品编号|○|○
商品名称|○|---
商品分类|○|---
销售单价|○|---
进货单价|○|---
登记日期|○|---
商店编号|---|○
商店名称|---|○
数量|---|○

如上表所示,两张表中的列可以分为如下两类:
A. 两张表中都包含的列 --&gt; 商品编号
B. 只存在与一张表内的列 --&gt; 商品编号以外的列

所谓链接运算,一言以蔽之,就是&quot;以A中的列作为桥梁,将B中的满足同样条件的列汇集到同一结果之中&quot;.具体过程如下所述.
从tenpoShohin表中的数据我们能够知道,东京店(000A)销售商品的编号为0001、0002和0003.但这些商品具体的名称(shohin\_mei)和销售单价(hanbai\_tanka)在TenpoShohin表中并不存在.这些信息都保存在Shohin表中.大阪店和名古屋店情况也是如此.
下面我们就试着从Shohin表中去除商品名称(shohin\_mei)和销售单价(hanbai\_tanka),与TenpoShohin表中的内容进行结合.
</code></pre><p>--将两张表进行内联结<br>SELECT TS.tenpo_id,TS.tenpo_mei,TS.shohin_id,S.shohin_mei,S.hanbai_tanka<br>FROM TenpoShohin AS TS INNER JOIN Shohin AS S<br>    ON TS.shohin_id = S.shohin_id;</p>
<pre><code>
执行结果如下:

tenpo\_id|tenpo\_mei|shohin\_id|shohin\_mei|hanbai\_tanka
---|---|---|---|---
000D|    福冈|    0001|    T恤    |    1000
000A|    东京|    0001|    T恤    |    1000
000B|    名古屋|    0002|    打孔器|    500
000A|    东京|    0002|    打孔器|    500
000C|    大阪|    0003|    运动T恤|    4000
000B|    名古屋|    0003|    运动T恤|    4000
000A|    东京|    0003|    运动T恤|    4000
000C|    大阪|    0004|    菜刀|    3000
000B|    名古屋|    0004|    菜刀|    3000
000C|    大阪|    0006|    叉子|    500
000B|    名古屋|    0006|    叉子|    500
000C|    大阪|    0007|    擦菜板|    880
000B|    名古屋|    0007|    擦菜板|    880

关于内联结,请注意以下三点:
##### 内联要点1--&gt;FROM子句
第1点要注意的是,之前的FROM子句中只有一张表,而这次我们同时使用了TenpoShohin和Shohin两张表
</code></pre><p>FROM TenpoShohin AS TS INNER JOIN Shohin AS S</p>
<pre><code>
使用关键字INNER JOIN就可以将两张表联结在一起了.TS和S分别是这两张表的别名,但别名并不是必须的.在SELECT子句中直接使用TenpoShohin和Shohin这样的表的原名也没有关系.但由于表名太长会影响SQL语句的可读性,所以还是希望我们能够习惯使用别名.
- 法则7-3 进行联结时需要在FROM子句中使用多张表.

##### 内联要点2--&gt;ON子句
第2点要注意的是ON后面所记载的联络条件
</code></pre><p>ON TS.Shohin_id = S.Shohin_id</p>
<pre><code>我们可以在ON之后指定两张表联结所使用的列(___联结键___).本例中使用的是商品编号(Shohin_id).也就是说ON是专门用来指定联结条件的,它能起到与WHERE相同的作用.需要指定多个键时,同样可以使用AND、OR. ON子句在进行内联时是必不可少的(如果没有ON会发生错误).并且ON必须书写在FROM与WHERE之间
- 法则7-4 进行内联结时必须使用ON子句,并且要书写在FROM和WHERE之间.

举个直观的例子,ON就像链接河流两岸城镇的桥梁一样.
联结条件也可以使用&quot;=&quot;来记述,在语法上,还可以使用&lt;=和BETWEEN等谓词.但是由于实际应用中九成以上都可以用&quot;=&quot;进行联结,所以开始时大家只要记住使用&quot;=&quot;就可以了.使用&quot;=&quot;将联结键进行关联,就能够将两张表中满足相同条件的记录进行&quot;联结&quot;了.
##### 内联结要点3--&gt;SELECT子句
第3点要注意的是,在SELECT子句中指定的列
</code></pre><p>SELECT TS.tenpo_id,tenpo_mei,TS.shohin_id,S.shohin_mei,S.hanbai_banka</p>
<pre><code>在SELECT子句中,使用像TS.tenpo\_id和S.hanbai\_tanka这样&lt;表的别名&gt;.&lt;列名&gt;的形式来指定列.这和使用一张表时的情况不同,由于多表联结时,某个列到底属于哪张表比较混乱,所以采用了这样的防范措施.语法上必须使用这样书写方式的只是那些同时存在于两张表中的列(这里是shohin\_id),其他的列可以像tenpo\_id这样直接书写列名,而不会发生错误.但是就像前面说的那样,为了避免混乱,还是希望我们能够在使用联结时按照&lt;表的别名&gt;.&lt;列名&gt;的格式来书写SELECT子句中全部的列.
- 法则7-5 使用联结时,SELECT子句中的列需要按照&lt;表的别名&gt;.&lt;列名&gt;的格式来书写.

##### 内联结和WHERE子句结合使用
如果并不想了解所有商店的情况,例如只想知道东京店(000A)的信息时,可以像之前学习那样在WHERE子句中添加条件.这样我们就可以根据下面的代码中得到的全部商店信息中选取出东京店的记录了.
</code></pre><p>--内联结和WHERE子句结合使用,查询东京店的记录<br>SELECT TS.tenpo_id,TS.Tenpo_mei,TS.shohin_id,S.shohin_mei,S.hanbai_tanka<br>FROM TenpoShohin AS TS INNER JOIN Shohin AS S<br>ON TS.shohin_id = S.shohin_id<br>WHERE TS.tenpo_id = &#39;000A&#39;;</p>
<pre><code>
执行结果:
tenpo\_id|tenpo\_mei|shohin\_id|shohin\_mei|hanbai_tanka
---|---|---|---|---
000A|    东京|    0001|    T恤    |    1000
000A|    东京|    0002|    打孔器|    500
000A|    东京|    0003|    运动T恤|    4000

像这样使用联结运算将满足相同规定的表联结起来时,WHERE、GROUP BY、HAVING、ORDER BY等工具都可以正常使用.我们可以将联结之后的结果想象为新创建出来的一张表(如下表),对这张表使用WHERE子句等工具,这样理解起来就容易多了

tenpo\_id|tenpo\_mei|shohin\_id|shohin\_mei|hanbai\_tanka
---|---|---|---|---
000A|    东京|    0001|    T恤    |    1000
000A|    东京|    0002|    打孔器|    500
000A|    东京|    0003|    运动T恤|    4000
000B|    名古屋|    0002|    打孔器|    500
000B|    名古屋|    0003|    运动T恤|    4000
000B|    名古屋|    0004|    菜刀|    3000
000B|    名古屋|    0006|    叉子|    500
000B|    名古屋|    0007|    擦菜板|    880
000C|    大阪|    0003|    运动T恤|    4000
000C|    大阪|    0004|    菜刀|    3000
000C|    大阪|    0006|    叉子|    500
000C|    大阪|    0007|    擦菜板|    880
000D|    福冈|    0001|    T恤    |    1000

当然,这张&quot;表&quot;只在SELECT语句执行期间存在,SELECT语句执行之后就会消失,如果希望继续使用这张&quot;表&quot;,还是将它创建成试图吧.

### 外联结--&gt;OUTER JOIN
内联结之外比较重要的就是外联结了.我们再来回顾一下前面的例子.
在前例中,我们将TenpoShohin表和Shohin表进行内联结,从两张表中取出各个商店销售的商品信息.其中,实现&quot;读取两张表信息&quot;的就是联结功能.
外联结也是通过ON子句使用联结键将两张表进行联结,同时从两张表中选区相应的列.基本的使用方法并没有发生改变,只是结果有所不同.
我们把之前的内联结语句转换为外联结试试看,结果有何不同
</code></pre><p>--将两张表进行外联结<br>SELECT TS.tenpo_id, TS.tenpo_mei, TS.shohin_id, S.shohin_mei,S.hanbai_tanka<br>FROM tenpoShohin AS TS RIGHT OUTERR JOIN Shohin AS S<br>ON TS.shohin_id = S.shohin_id;</p>
<pre><code>
执行结果:

tenpo\_id|tenpo\_mei|shohin\_id|shohin\_mei|hanbai\_tanka
---|---|---|---|---
000A|    东京|    0002|    打孔器|    500
000A|    东京|    0003|    运动T恤|    4000
000A|    东京|    0001|    T恤    |    1000
000B|    名古屋|    0006|    叉子|    500
000B|    名古屋|    0002|    打孔器|    500
000B|    名古屋|    0003|    运动T恤|    4000
000B|    名古屋|    0004|    菜刀|    3000
000B|    名古屋|    0007|    擦菜板|    880
000C|    大阪|    0006|    叉子|    500
000C|    大阪|    0007|    擦菜板|    880
000C|    大阪|    0003|    运动T恤|    4000
000C|    大阪|    0004|    菜刀|    3000
000D|    福冈|    0001|    T恤    |    1000
\---    |    \---    |    \---    |    高压锅|    6800
\---    |    \---    |    \---    |    圆珠笔|    100

_最后两行内联结时,并不存在_

##### 外联结要点1--&gt;选取出单张表中全部的信息
与内联结的结果相比,不同点显而易见,那就是结果的行数不一样.内联结的结果中有13条记录,而外联结的结果中有15条记录.增加的两条记录到底是什么呢?
这正是外联结的关键点.多出的两条记录是高压锅和圆珠笔.这两条记录在TenpoShohin表中并不存在.也就是说这两种商品在任何商店中都没有销售.由于内联结只能选取出同时存在于两张表中的数据,所以只在Shohin表中存在的2种商品并没有出现在结果之中.
相反,对于外联结来说,只要数据存在于某一张表当中,就能够读取出来.在实际的业务当中,例如想要生成固定行数的定型单据时,就需要使用外联结.如果使用内联结的话,根据SELECT语句执行时商店库存状况的不同,结果行数也会发生改变生成单据的外观也会受到影响而使用外联结能够得到固定行数的结果.
话虽如此,那些表中不存在的数据我们还是无法得到结果中高压锅和圆珠笔的商店编号和商店名称都是NULL(具体信息大家都不知道,真是无可奈何).外联结名称的由来也跟NULL有关.所谓&quot;外部&quot;,也就是&quot;包含元表中不存在(在元表之外)的信息&quot;的意思,相反,只包含表内信息的联结也就被称为&quot;内&quot;联结了.

##### 外联结要点2--&gt;每张表都是主表吗?
外联结还有一点非常重要,那就是要把那张表作为主表.最终的结果中会包含主表内所有的数据.指定主表的关键字是___LEFT___和___RIGHT___.如其名称所示,使用LEFT时FROM子句中写在左侧的表是主表,使用RIGHT时,右侧的表也就是Shohin表是主表.
我们还可以像下面这样进行调换,意思完全相同.
</code></pre><p>SELECT TS.tenpo_id, TS.tenpo_mei, TS.shohin_id, S.shohin_mei,S.hanbai_tanka<br>FROM Shohin AS S LEFT OUTER JOIN tenpoShohin AS TS<br>ON TS.shohin_id = S.shohin_id<br>ORDER BY tenpo_id;</p>
<pre><code>
执行结果与上面一段代码的执行结果完全一样:

执行结果:

tenpo\_id|tenpo\_mei|shohin\_id|shohin\_mei|hanbai\_tanka
---|---|---|---|---
000A|    东京|    0002|    打孔器|    500
000A|    东京|    0003|    运动T恤|    4000
000A|    东京|    0001|    T恤    |    1000
000B|    名古屋|    0006|    叉子|    500
000B|    名古屋|    0002|    打孔器|    500
000B|    名古屋|    0003|    运动T恤|    4000
000B|    名古屋|    0004|    菜刀|    3000
000B|    名古屋|    0007|    擦菜板|    880
000C|    大阪|    0006|    叉子|    500
000C|    大阪|    0007|    擦菜板|    880
000C|    大阪|    0003|    运动T恤|    4000
000C|    大阪|    0004|    菜刀|    3000
000D|    福冈|    0001|    T恤    |    1000
\---    |    \---    |    \---    |    高压锅|    6800
\---    |    \---    |    \---    |    圆珠笔|    100

其实LEFT 和RIGHT的功能没有任何区别,使用哪一个都可以.通常,使用LEFT的情况会多一点,但并没有非使用这个不可的理由,使用RIGHT也没有任何问题.
- 法则7-6 外联结中,使用LEFT、RIGHT来指定主表.使用二者所得到的结果完全一致

#### 3张以上表的联结
通常联结只设计两张表,但有事也会出现必须同时联结3张以上表的情况.原则上联结表的数量并没有限制.下面我们就来看下3张表的联结吧.
首先我们创建一张用来管理库存的表ZaikoShohin.假设商品都保存在SOO1,S002这两个仓库中.
</code></pre><p>-- 代码清单7-13,创建ZaikoShohin,并,向表中插入数据:<br>-- DDL:创建表<br>CREATE TABLE ZaikoShohin(<br>souko_id    CHAR(4)        NOT NULL,<br>shohin_id     CHAR(4)        NOT NULL,<br>zaiko_suryo INTEGER        NOT NULL,<br>PRIMARY KEY (souko_id, shohin_id));<br>-- DML:插入数据:<br>BEGIN TRANSACTION;</p>
<p>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S001&#39; ,&#39;0001&#39;,0);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S001&#39; ,&#39;0002&#39;,120);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S001&#39; ,&#39;0003&#39;,200);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S001&#39; ,&#39;0004&#39;,3);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S001&#39; ,&#39;0005&#39;,0);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S001&#39; ,&#39;0006&#39;,99);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S001&#39; ,&#39;0007&#39;,999);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S001&#39; ,&#39;0008&#39;,200);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S002&#39; ,&#39;0001&#39;,10);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S002&#39; ,&#39;0002&#39;,25);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S002&#39; ,&#39;0003&#39;,34);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S002&#39; ,&#39;0004&#39;,19);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S002&#39; ,&#39;0005&#39;,99);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S002&#39; ,&#39;0006&#39;,0);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S002&#39; ,&#39;0007&#39;,0);<br>INSERT INTO ZaikoShohin (souko_id,shohin_id,zaiko_suryo) VALUES (&#39;S002&#39; ,&#39;0008&#39;,18);</p>
<p>COMMIT;</p>
<p>执行结果:</p>
<h2>souku_id |    shohin_id |     suryo</h2>
<p>+------------+--------<br>  S001     |      0001      |      0<br>  S001     |      0002      |      120<br>  S001     |      0003      |      200<br>  S001     |      0004      |      3<br>  S001     |      0005      |      0<br>  S001     |      0006      |      99<br>  S001     |      0007      |      999<br>  S001     |      0008      |      200<br>  S002     |      0001      |      10<br>  S002     |      0002      |      25<br>  S002     |      0003      |      34<br>  S002     |      0004      |      19<br>  S002     |      0005      |      99<br>  S002     |      0006      |      0<br>  S002     |      0007      |      0<br>  S002     |      0008      |      18</p>
<pre><code>
下面我们从上表中取出保存在S001仓库中的商品数量,并将该列添加到带啊清单7-11所得到的的结果中.联结方式为内联结(外联结的使用方法完全相同),联结键为商品编号(shohin_id)
</code></pre><p>代码7-14对3张表进行联结:<br>SELECT TS.tenpo_id,TS.tenpo_mei,TS.shohin_id,S.shohin_mei,S.hanbai_tanka,ZS.zaiko_suryo<br>FROM TenpoShohin AS TS INNER JOIN Shohin AS S<br>ON TS.Shohin_id = S.shohin_id<br>INNER JOIN ZaikoShohin AS ZS<br>ON TS.shohin_id = ZS.shohin_id<br>WHERE ZS.souko_id = &quot;S001&quot;;<br>执行结果:</p>
<h2>tenpo_id  |    tenpo_mei    |  shohin_id |  shohin_mei  | hanbai_tanka | suryo    </h2>
<p>+-------------+------------+--------------+--------------+-------<br>000A          东京            0001            T恤            1000          0<br>000A          东京            0002            打孔器        500              120<br>000A          东京            0003            运动T恤        4000          200<br>000B          名古屋            0002            打孔器        500              120<br>000B          名古屋            0003            运动T恤        4000          200<br>000B          名古屋            0004            菜刀        3000          3<br>000B          名古屋            0006            叉子        500              99<br>000B          名古屋            0007            擦菜板        880              999<br>000C          大阪            0003            运动T恤        4000          200<br>000C          大阪            0004            菜刀        3000          3<br>000C          大阪            0006            叉子        500              99<br>000C          大阪            0007            擦菜板        880              999<br>000D          福冈            0001            T恤            1000          0</p>
<pre><code>
ZaikoShohin表也添加进来:
</code></pre><p>FROM TenpoShohin AS TS INNER JOIN Shohin AS S<br>ON TS.shohin_id = S.shohin_id<br>INNER JOIN ZaikoShohin AS ZS<br>ON TS.shohin_id = ZS.Shohin_id</p>
<pre><code>通过ON子句指定联结条件的方式也没有发生改变.使用等号将作为联结条件的Shohin表和TenpoShohin表中的商品编号(Shohin_id)联结起来.由于Shohin表和TenpoShohin表已经进行了联结,所以这里无需再对Shohin表和ZaikoShohin表进行联结了(虽然也可以进行联结,但结果不会发生改变).
即使想要把联结的表增加到4张,5张……,使用INNER JOIN进行添加的方式也是完全相同的
#### 交叉联结--&gt;CROSS JOIN
接下来,我们要学习第三种联结方式--&gt;交叉联结.其实这种联结在实际业务中并没有使用过(作者也很少使用这种联结).但是价差联结是所有联结运算的基础.
交叉联结本身非常简单,但是其结果有点麻烦.下面我们试着将Shohin表和TenpoShohin表进行交叉联结
</code></pre><p>--代码7-15 将两张表进行交叉联结:<br>SELECT TS.tenpo_id,TS.tenpo_mei,TS.shohin_id,S.shohin_mei,S.hanbai_tanka<br>FROM tenpoShohin AS TS CROSS JOIN Shohin AS S;<br>执行结果:<br>tenpo_id| tenpo_mei| shohin_id| shohin_mei| hanbao_tanka<br>000A          东京       0001          T恤            1000<br>000A          东京       0002          T恤            1000<br>000A          东京       0003          T恤            1000<br>000B          名古屋       0002          T恤            1000<br>000B          名古屋       0003          T恤            1000<br>000B          名古屋       0004          T恤            1000<br>000B          名古屋       0006          T恤            1000<br>000B          名古屋       0007          T恤            1000<br>000C          大阪       0003          T恤            1000<br>000C          大阪       0004          T恤            1000<br>000C          大阪       0006          T恤            1000<br>000C          大阪       0007          T恤            1000<br>000D          福冈       0001          T恤            1000<br>000A          东京       0001          打孔器            500<br>000A          东京       0002          打孔器            500<br>000A          东京       0003          打孔器            500<br>000B          名古屋       0002          打孔器            500<br>000B          名古屋       0003          打孔器            500<br>000B          名古屋       0004          打孔器            500<br>000B          名古屋       0006          打孔器            500<br>000B          名古屋       0007          打孔器            500<br>000C          大阪       0003          打孔器            500<br>000C          大阪       0004          打孔器            500<br>000C          大阪       0006          打孔器            500<br>000C          大阪       0007          打孔器            500<br>000D          福冈       0001          打孔器            500<br>000A          东京       0001          运动T恤        4000<br>000A          东京       0002          运动T恤        4000<br>000A          东京       0003          运动T恤        4000<br>000B          名古屋       0002          运动T恤        4000<br>000B          名古屋       0003          运动T恤        4000<br>000B          名古屋       0004          运动T恤        4000<br>000B          名古屋       0006          运动T恤        4000<br>000B          名古屋       0007          运动T恤        4000<br>000C          大阪       0003          运动T恤        4000<br>000C          大阪       0004          运动T恤        4000<br>000C          大阪       0006          运动T恤        4000<br>000C          大阪       0007          运动T恤        4000<br>000D          福冈       0001          运动T恤        4000<br>000A          东京       0001          菜刀            3000<br>000A          东京       0002          菜刀            3000<br>000A          东京       0003          菜刀            3000<br>000B          名古屋       0002          菜刀            3000<br>000B          名古屋       0003          菜刀            3000<br>000B          名古屋       0004          菜刀            3000<br>000B          名古屋       0006          菜刀            3000<br>000B          名古屋       0007          菜刀            3000<br>000C          大阪       0003          菜刀            3000<br>000C          大阪       0004          菜刀            3000<br>000C          大阪       0006          菜刀            3000<br>000C          大阪       0007          菜刀            3000<br>000D          福冈       0001          菜刀            3000<br>000A          东京       0001          高压锅            6800<br>000A          东京       0002          高压锅            6800<br>000A          东京       0003          高压锅            6800<br>000B          名古屋       0002          高压锅            6800<br>000B          名古屋       0003          高压锅            6800<br>000B          名古屋       0004          高压锅            6800<br>000B          名古屋       0006          高压锅            6800<br>000B          名古屋       0007          高压锅            6800<br>000C          大阪       0003          高压锅            6800<br>000C          大阪       0004          高压锅            6800<br>000C          大阪       0006          高压锅            6800<br>000C          大阪       0007          高压锅            6800<br>000D          福冈       0001          高压锅            6800<br>000A          东京       0001          叉子            500<br>000A          东京       0002          叉子            500<br>000A          东京       0003          叉子            500<br>000B          名古屋       0002          叉子            500<br>000B          名古屋       0003          叉子            500<br>000B          名古屋       0004          叉子            500<br>000B          名古屋       0006          叉子            500<br>000B          名古屋       0007          叉子            500<br>000C          大阪       0003          叉子            500<br>000C          大阪       0004          叉子            500<br>000C          大阪       0006          叉子            500<br>000C          大阪       0007          叉子            500<br>000D          福冈       0001          叉子            500<br>000A          东京       0001          擦菜板            880<br>000A          东京       0002          擦菜板            880<br>000A          东京       0003          擦菜板            880<br>000B          名古屋       0002          擦菜板            880<br>000B          名古屋       0003          擦菜板            880<br>000B          名古屋       0004          擦菜板            880<br>000B          名古屋       0006          擦菜板            880<br>000B          名古屋       0007          擦菜板            880<br>000C          大阪       0003          擦菜板            880<br>000C          大阪       0004          擦菜板            880<br>000C          大阪       0006          擦菜板            880<br>000C          大阪       0007          擦菜板            880<br>000D          福冈       0001          擦菜板            880<br>000A          东京       0001          圆珠笔            100<br>000A          东京       0002          圆珠笔            100<br>000A          东京       0003          圆珠笔            100<br>000B          名古屋       0002          圆珠笔            100<br>000B          名古屋       0003          圆珠笔            100<br>000B          名古屋       0004          圆珠笔            100<br>000B          名古屋       0006          圆珠笔            100<br>000B          名古屋       0007          圆珠笔            100<br>000C          大阪       0003          圆珠笔            100<br>000C          大阪       0004          圆珠笔            100<br>000C          大阪       0006          圆珠笔            100<br>000C          大阪       0007          圆珠笔            100<br>000D          福冈       0001          圆珠笔            100</p>
<pre><code>
我们可能被结果的行数惊到了,但是我们还是先来介绍一下语法结构,对满足相同规定的表进行交叉联结的集合运算符是CROSS JOIN(笛卡尔积).进行交叉联结时无法使用内联结和外联结所使用的ON子句,这是因为交叉联结是对两张表中的全部记录进行交叉组合,因此结果中的记录数通常是两张表中行数的乘积.前例中,由于TenpoShohin表存在13条记录,Shohin表存在8条记录,所以结果中就有13*8=104条记录.
可能这时会有人想起在前一节最后,我们提到了集合运算中的乘法会在本届中进行详细学习,这就是上面介绍的交叉联结.
内联结是交叉联结的一部分.&quot;内部&quot;也可以理解为&quot;包含在交叉联结结果中的部分&quot;.相反,外联结可以理解为&quot;交叉联结结果之外的部分&quot;.
交叉联结没有应用到实际业务之中的原因有两个.一个是其结果没有实用价值,二是由于其结果行数太多,需要花费大量的运算时间和高性能设备的支持.

#### 特定的联结语句和过时的语法
之前我们学习的内联结和外联结语法都符合标准SQL的规定,可以在所有的DBMS中执行.因此,我们可以放心使用,但是如果我们之后从事系统开发工作的话,一定会碰到需要阅读他人写的代码并进行维护的情况.而那些使用特定和过时语法的程序就会成为我们的麻烦.
SQL是一门特定及过时语法非常多的语言,虽然之前书中也多次提及,但联结是其中特定语法的部分,现在还有不少年长的程序员和系统工程师仍在使用这些特定的语法.
例如,我们学习的内联结的SELECT语句替换为过时语法的结果如下所示:
</code></pre><p>--代码7-16使用过时语法的内联结<br>SELECT TS.tenpo_id, TS.tenpo_mei, TS.shohin_id,S.shohin_mei,S.hanba_tanka<br>FROM tenpoShohin TS,Shohin S<br>WHERE TS.shohin_id = S.shohin_id<br>AND TS.tenpo_id = &#39;000A&#39;;</p>
<pre><code>这样的书写方式得到的结果与标准语法完全相同.并且,这样的语法可以在所有的DMBS中执行,并不能算是特定的语法,只是过时了而已.
但是,由于这样的语法不仅过时,而且还存在很多其他的问题,所以不推荐使用.理由主要有以下三点:

1. 使用这样的语法无法马上判断出到底是内联结还是外联结(又或者是其他种类的联结)

2. 由于链接条件都写在WHERE子句之中,所以无法在短时间内分辨出那部分是联结条件,那部分是用来选区记录的限制条件.

3. 就是我们不知道这样的语法到底还能用多久,每个DMBS的开发这都会考虑放弃过时的语法,转而支持新的语法,虽然并不是马上就不能使用了,但那一天总会到来

虽然这么说,但是现在使用这些过时语法编写的程序还有很多,到目前为止还都能正常执行.我们很可能会碰到这样的代码,因此最好还是能了解.
- 法则7-7 那些过时和特定的联结书写方式,虽然我们自己不使用,但必须要能读懂

#### 关系除法
本章中我们学习了以下4个集合运算符:

- Union(并集)
- Except(差集) 
- Intersect(交集)
- CROSS JOIN(笛卡尔积)

虽然交集是独立的一种集合运算,但实际上它是&quot;只包含公共部分的特殊Union&quot;.剩下的3个在四则运算中也有对应的运算.但是,除法运算还没有介绍.
难道集合运算中没有除法吗?当然不是,除法运算是存在的.集合运算中的除法通常称为&quot;关系除法&quot;,关系是除法领域中对表或者视图的称谓.但是并没有定义像UNION或者EXCEPT这样专用的运算符号.如果要定义,估计应该DIVIDE(除)吧.但截止目前并没有DBMS使用这样的运算符.
为什么只有除法运算不使用运算符(只有除法)对被除数进行与水暖呢?其中的理由有点复杂,还是让我们先来介绍一下&quot;表的除法&quot;具体是一种什么样的运算吧.
我们创建两张表作为示例用表:
</code></pre><p>--创建SkillS表/EmpSkills表<br>--DDL:创建表:<br>CREATE TABLE Skills<br>(skill VARCHAR(32),<br>PRIMARY KEY (skill));</p>
<p>CREATE TABLE EmpSkills<br>(emp VARCHAR(32),<br>skill VARCHAR(32)<br>PRIMARY KEY(emp,skill));</p>
<p>--DML:插入数据:<br>INSERT INTO Skills VALUES (&#39;Oracle&#39;);<br>INSERT INTO Skills VALUES (&#39;UNIX&#39;);<br>INSERT INTO Skills VALUES (&#39;JAVA&#39;);</p>
<p>INSERT INTO EmpSkills VALUES(&#39;相田&#39;,&#39;Oracle&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;相田&#39;,&#39;UNIX&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;相田&#39;,&#39;JAVA&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;相田&#39;,&#39;C#&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;神崎&#39;,&#39;Oracle&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;神崎&#39;,&#39;UNIX&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;神崎&#39;,&#39;JAVA&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;平井&#39;,&#39;UNIX&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;平井&#39;,&#39;Oracle&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;平井&#39;,&#39;PHP&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;平井&#39;,&#39;Perl&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;平井&#39;,&#39;C++&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;若田部&#39;,&#39;Perl&#39;);<br>INSERT INTO EmpSkills VALUES(&#39;渡来&#39;,&#39;Oracle&#39;);</p>
<p>COMMIT;</p>
<pre><code>
得到下面两张表:
Skills(技术)表
Skill|---
---|---
Oracle|---
UNIX|---
Java|---

EmpSkills(员工技术)表:
emp|Skills
---|---
相田|Oracle
相田|UNIX
相田|JAVA
相田|C#
神崎|Oracle
神崎|UNIX
神崎|JAVA
平井|UNIX
平井|Oracle
平井|PHP
平井|Perl
平井|C++
若田部|Perl
渡来|Oracle

EmpSkills表中保存了某个系统公司员工所掌握的技术信息.例如,从该表中我们可以了解到相田掌握了Oracle、UNIX、JAVA、C#这四种技术.
下面我们来思考一下如何从该表中选取出掌握了Skills表中所有3个领域技术的员工吧.
</code></pre><p>SELECT DISTINCT emp<br>FROM EmpSkills ES1<br>WHERE NOT EXISTS<br>(SELECT SkillS<br>    FROM SkillS<br>EXCEPT<br>SELECT skill<br>FROM EmpSkills ES2<br>WHERE ES1.emp = ES2.emp);<br>执行结果:</p>
<h2>emp</h2>
<p>相田<br>神崎</p>
<pre><code>这样我们就得到了&quot;相田&quot;和&quot;神崎&quot;两个人.虽然平井也掌握了Oracle和UNIX,但是他不会JAVA,所以没选出来.
这样的运算结果满足了除法运算的基本规则.肯定有人会问,到底上述运算中什么地方是除法运算呢?实际上这和数值的除法既相似又有所不同.
除法和乘法是相辅相成的关系,除法运算的结果(商)乘以除数就能得到运算前的被除数了.
关系除法中,这样的规则也是成立的.商和除数相乘,也就是交叉联结,就能够得到作为被除数的集合了.(虽然不能恢复成完整的被除数,但这里我们也不追究了.)
综上所述,除法运算是集合运算中最复杂的运算,但是其在实际业务中的应用十分广泛,因此最好还是能够了解掌握.
## 第八章 SQL高级处理
### 8-1 窗口函数
#### 什么是窗口函数
窗口函数也称OLAP函数.为了快速形成直观印象,才起了这样一个容易理解的名称(&quot;窗口&quot;的含义我们将在随后进行说明).
OLAP是Online Analytical Processing的简称,意为对数据库数据进行实时分析处理.例如,市场分析、创建财务报表、创建计划等日常性商务工作.
窗口函数就是为了实现OLAP而添加的标准SQL功能.(__目前MySQL数据还不支持窗口函数__)
##### 窗口函数的支持情况
很多数据库相关工作者过去都会有这样的想法:&quot;好不容易将业务数据插入到了数据库中,如果能够使用SQL对齐进行实时分析的话,一定会很方便吧.&quot;但是关系数据库提供好OLAP用途的功能仅仅只有10年左右的时间
其中的理由有很多,这里我们不一一介绍了.值得注意的是,还有一部分DBMS并不支持这样的新功能.
我们现在学习的窗口函数也是其中之一,截止20105月,Oracle 11g、SQL SERVER2008、DB2 9.7、PostgreSQL都已经支持了该功能.但是MySQL 5.5还是不支持此功能.
#### 窗口函数的语法
接下来,就让我们通过示例来学习窗口函数.窗口函数的语法有些复杂.
</code></pre><p>--语法8.1 窗口函数<br>&lt;窗口函数&gt; OVER ([PARTITION BY &lt;列清单&gt;]<br>                ORDER BY &lt;拍序用列清单&gt;)<br>注:[]中的内容可以省略</p>
<pre><code>
其中重要的关键字是PARTITION BY 和 ORDER BY.首先,理解这两个关键字的作用是帮我们理解窗口函数的关键.
##### 能够作为窗口函数使用的函数
在学习PARTITION BY 和 ORDER BY之前,我们先来列举一下能够作为窗口函数使用的函数.窗口函数大体可以分为以下两种.
1. 能够作为窗口函数的聚合函数(SUM、AVG、COUNT、MAX、MIN)
2. RANK、DENSE\_RANK、ROW\_NUMBER等__专用窗口函数__

其中第二条中的函数是标准SQL定义的OLAP专用函数.我们将它们统称为&quot;专用窗口函数&quot;从这些函数的名称很容易就可以看出其OLAP的作用.
上面的第一条使我们在第三章学习的聚合函数.通过将聚合函数书写在&quot;语法8-1&quot;的&lt;窗口函数&gt;中,就能够作为窗口函数来使用了.总之,集约函数根据使用语法的不同,可以在集约函数和窗口函数之间进行转换.
#### 语法的基本使用方法--&gt;使用RANK函数
首先让我们通过专用窗口函数RANK来理解一下窗口函数的语法吧.正如其名称所示,RANK是用来计算记录排序的函数.
例如,我们将从各种类的商品(shohin\_bunrui),按照销售单价(hanbai\_tanka)从低到高的顺序,制作出之前曾使用过的shohin表中8件商品的排序表
</code></pre><p>--代码8-1 将各种商品,按照销售单价从低到高的顺序创建排序表<br>SELECT shohin_mei,shohin_bunrui, hanbai_tanka,<br>    RANK() OVER (PARTITION BY shohin_bunrui<br>                ORDER BY hanbai_tanka) AS ranking<br>FROM shohin;</p>
<pre><code>执行结果:

shohin\_mei|shohin\_bunrui|hanbai\_tanka|rank
---|---|---|---
圆珠笔|    办公用品|100|1
打孔器|    办公用品|500|2
叉子|    厨房用具|500|1
擦菜板|    厨房用具|880|2
菜刀|    厨房用具|3000|3
高压锅|    厨房用具|6800|4
T恤    |    衣服|1000|1
运动T恤|    衣服|4000|2

在上表中,以厨房用具为例,销售单价最便宜的&quot;叉子&quot;排在第一位,最贵的&quot;高压锅&quot;排在第四位,确实按照我们的要求进行了排序.
在代码中,__PARTITION BY__能够设定排序的对象范围.本例中为了按照商品种类进行排序,我们指定了shohin\_bunrui.
__ORDER BY__能够指定按照那一列、何种顺序进行排序.为了按照销售单价的升序进行排列,我们指定了hanbai\_tanka.此外,窗口函数中的ORDER BY与SELECT语句末尾的ORDER BY一样,可以通过关键字ASC/DESC来指定升序或者降序.省略该关键字时会默认按照ASC,也就是升序进行排序.
窗口函数兼具之前我们学过的GROUP BY 子句的分组功能,以及ORDER BY子句的排序功能.但是PARTTION BY子句并不具备GROUP BY子句的聚合功能.因此使用RANK函数并不会减少元素中记录的行数,结果依然是8行数据.

- 法则8-1 窗口函数具有分组和排序两种功能.

通过PARTITION BY分组后的记录集合称为&quot;窗口&quot;.此处的窗口并非&quot;窗户&quot;的意思,而是代表了&quot;__范围__&quot;.这也就是&quot;窗口函数&quot;名称的由来.

- 法则8-2 通过PARTITION BY分组后的记录集合称为&quot;窗口&quot;.

此外,各个窗口在定义上绝对不会包含共通的部分.就像刀切蛋糕一样,干净利落.这与通过GROUP BY子句分割后的集合具有相同的特征.

#### 无需指定PARTITION BY

使用窗口函数时祈祷关键作用的是PARTITION BY和GROUP BY.其中PARTITION BY 并不是必须的.即使不指定也可以正常使用窗口函数.
那么就让我们来确认一下不指定PARTITION BY会得到什么样的结果吧.这和使用没有GROUP BY的聚合参数时的效果是一样的.也就是将整个表作为一个大的窗口来使用,我们一起来试试吧.
</code></pre><p>--代码8-2 不指定PARTITION BY<br>SELECT shohin_mei,shohin_bunrui,hanbai_tanka,<br>    RANK() OVER (ORDER BY hanbai_tanka) AS ranking<br>FROM Shohin;</p>
<pre><code>
执行结果:

shohin\_mei|shohin\_bunrui|hanbai\_tanka|ranking
---|---|---|---
圆珠笔|    办公用品|100    |1
叉子|    厨房用具|500    |2
打孔器|    办公用品|500    |2
擦菜板|    厨房用具|880    |4
T恤    |    衣服|1000    |5
菜刀|    厨房用具|3000|6
运动T恤|    衣服|4000    |7
高压锅|    厨房用具|6800|8

之前,我们得到的是按照商品种类分组后的排序,而这次变成了全部商品的排序.PARTITION BY 可以将表中的数据分为多个部分(窗口),是希望使用窗口函数时的一个选项.
#### 专用窗口函数的种类
从上述结果中我们可以看到,&quot;打孔器&quot;和&quot;叉子&quot;都排在第2位,而之后的&quot;擦菜板&quot;跳过了第3位,直接拍到了第4位.这也是通常的排序方法.但某些情况下可能并不希望跳过某个位次来进行排序.
这时可以使用RANK函数之外的函数来实现.下面我们就来总结一下有代表性的专用窗口函数.

- RANK函数
    计算排序时,如果存在相同位次的记录,则会跳过之后的位次
    例) 有三条记录排在第一位时: 1位,1位,1位,4位

- DENSE_RANK函数
    同样是计算排序,即使存在相同位次的记录,也不会跳过之后的位次.
    例) 有三条记录排在第一位时: 1位,1位,1位,2位

- ROw_NUMBER函数
    赋予唯一的连续位次.
    例) 有三条记录排在第一位时: 1位,2位,3位,4位

除此之外,各DBMS还提供了各自特有的窗口函数.上述3个函数(对于支持窗口函数的DBMS来说)在所有的DBMS中都能使用,下面就让我们比较一下使用这三个函数的结果吧
</code></pre><p>--代码8-3 比较RANK,DENSE_RANK 和 ROW_NUMBER的区别:<br>SELECT shohin_mei,shohin_bunrui,hanbai_tanka,<br>    RANK () OVER (ORDER BY hanbai_tanka) AS ranking,<br>    DENSE_RANK () OVER (ORDER BY hanbai_tanka) AS dense_ranking,<br>    ROW_NUMBER ()　OVER (ORDER BY hanbai_tank) AS row_num<br>FROOM shohin;</p>
<pre><code>
执行结果:

shohin\_mei|shohin\_bunrui|hanbai\_tanka|ranking|dense\_ranking|row\_num
---|---|---|---|---|---
圆珠笔|    办公用品|100    |    1|    1|    1
叉子|    厨房用具|500    |    2|    2|    2
打孔器|    办公用品|500    |    2|    2|    3
擦菜板|    厨房用具|880    |    4|    3|    4
T恤    |    衣服|1000    |    5|    4|    5
菜刀|    厨房用具|3000|    6|    5|    6
运动T恤|    衣服|4000    |    7|    6|    7
高压锅|    厨房用具|6800|    8|    7|    8

将结果中的ranking列和dense\_ranking列进行比较可以发现,dense\_ranking列中有连续2个第2位,这和ranking列的情况相同.但是接下来的&quot;擦菜板&quot;的位次并不是第4位,而是第3.这就是使用DENSE_RANK函数的效果了.
此外,我们可以看到,在row\_num列中,不管销售单价(hanbai\_tanka)是否相同,每件商品都会按照销售单价从低到高的顺序得到一个连续的位次.销售单价相同时,DBMS会根据适当的顺序进行排列.想为记录赋予唯一的连续位次时,就可以像这样使用ROW_NUMBER来实现.
使用RANK或者ROW\_NUMBER时无需任何参数,只需要像RANK()或者ROW\_NUMBER()这样保持括号中为空就可以了,这也是专用窗口函数通常的使用方式,请务必牢记.
- 法则8-3 由于专用窗口函数无需参数,所以通常括号中都是空的.

#### 窗口函数的适用范围
目前为止我们学过的函数大部分都没有使用位置的限制.最多也就是在WHERE子句中使用聚合参数时会有些注意事项.但是,适用窗口函数的位置却有非常大的限制.更确切些说,窗口函数只能书写在一个特定的位置.
这个位置就是在SELECT子句中,反过来说,就是这类函数不能在WHERE子句或者GROUP BY子句中使用.

- 法则8-4 原则上窗口 函数只能在SELECT子句中使用.

虽然,我们可以把它当做一种规则司机硬背下来,但是为什么窗口函数只能在SELECT子句中使用呢?(也就是不能在WHERE子句或者GROUP BY子句中使用.) 下面我们就来简单说明一下其中的理由.
其理由就是,在DBMS内部,窗口函数是对WHERE子句或者GROUP BY子句处理后的&quot;结果&quot;进行操作.我们可以仔细想一想,在得到用户想要的结果之前,即使进行了排序处理,结果也是错误的.在得到排序结果之后,如果通过WHERE子句中的条件出去了某些记录,或者使用GROUP BY子句进行了聚合处理,那好不容易得到的排序结果也就无法使用了(___反之,之所以在ORDER BY子句中能够使用窗口函数,是因为ORDER BY子句会在SELECT子句之后执行,并且记录保证不会减少___).
正是由于这样的原因,__在SELECT子句之外&quot;使用窗口函数是没有意义的&quot;__,所以在语法上才会有这样的限制.
___备注:其实,语法上,除了SELECT子句,ORDER BY子句或者UPDATE语句的SET子句也是可以使用窗口函数的,但是由于几乎没有实际业务会这么操作,所以我们就记得&quot;只能在SELECT子句中使用&quot;就可以了___

#### 作为窗口函数使用的聚合参数
 前面我们学习了使用专用窗口函数的示例.下面我们看看如何把之前学过的SUM或者AVG等聚合函数作为窗口函数的使用方法.
 所有的聚合函数都能用作窗口函数,其语法和专用窗口函数完全相同,但是我们对于所能得到的结果没有一个直观的印象,所以我们还是通过具体的示例来进行学习:
</code></pre><p>--代码8-4 将SUM函数作为窗口函数使用<br>SELECT shohin_id,shohin_mei,hanbai_tanka,<br>     SUM(hanbai_tanka) OVER (ORDER BY Shohin_id) AS current_sum<br>FROM shohin;</p>
<pre><code>
执行结果:

shohin\_id|shohin\_mei|hanbai\_tanka|current\_sum
---|---|---|---
0001|    T恤    |    1000|1000
0002|    打孔器|    500    |1500 &lt;--1000+500
0003|    运动T恤|    4000|5500 &lt;--1000+500+4000
0004|    菜刀|    3000|8500 &lt;--1000+500+4000+3000
0005|    高压锅|    6800|15300        ....
0006|    叉子|    500    |15800
0007|    擦菜板|    880    |16680
0008|    圆珠笔|    100    |16780

使用SUM函数时,并不像RANK或者ROW\_NUMBER那样括号中的内容为空.而是和之前我们学过的一样,需要在括号内指定作为聚合对象的列.本例中我们计算出了销售单价(hanbai\_tanka)的合计值(current\_sum).
但是我们得到的并不仅仅是合计值.而是按照ORDER BY子句指定的Shohin\_id的升序进行排列,计算出商品编号&quot;小于自己&quot;的商品的销售单价的合计值.因此计算该合计值的逻辑就像金字塔堆积那样,一行一行的逐渐添加计算对象.在计算随时增加的销售总额,特别是需要按照时间顺序计算时,通常都会使用这种称为&quot;__累计__&quot;的统计方法.
使用其他聚合函数时的操作逻辑也和本例相同.例如,使用AVG来代替SELECT语句中的SUM
</code></pre><p>--代码8-5 将AVG函数作为窗口函数使用<br>SELECT shohin_id,shohin_mei,hanbai_tanka,<br>AVG(hanbai_tanka) OVER (ORDER BY shohin_id) AS current_avg<br>FROM shohin;</p>
<pre><code>
执行结果:

shohin\_id|shohin\_mei|hanba\_tanka|current\_avg
---|---|---|---
0001|    T恤    |    1000|    1000 &lt;--1000/1
0002|    打孔器|    500    |    750  &lt;--(1000+500)/2 下面依次类推
0003|    运动T恤|    4000|    1833.3333333333333333
0004|    菜刀|    3000|    2125
0005|    高压锅|    6800|    3060
0006|    叉子|    500    |    2633.3333333333333333
0007|    擦菜板|    880    |    2382.8571428571428571
0008|    圆珠笔|    100    |    2097.5

从结果中我们可以看到,current\_avg的计算方法,确实是计算平均值的方法.但作为统计对象的却只是&quot;排在自己之上&quot;的记录.像这样以&quot;自身记录(当前记录)&quot;作为基准进行统计,就是将聚合函数用作窗口函数使用时的最大特征.

#### 计算移动平均
窗口函数就是将表以窗口为单位进行分割,并在其中进行排序的函数.其实其中还包含在窗口中指定更加详细的统计范围的备选功能.该备选功能中的统计范围称为&quot;框架&quot;.
其语法如下面代码所示,需要在ORDER BY子句之后使用范围的关键字
</code></pre><p>--代码 8-6 指定&quot;最靠近3行&quot;作为统计对象<br>SELECT shohin_id,shohin_mei,hanbai_tanka<br>AVG(hanbai_tanka) OVER (ORDER BY shohin_id ROWS 2 PRECEDING) AS moving_avg<br>FROM shohin;</p>
<pre><code>执行结果:

shohin\_id|shohin\_mei|hanbai\_tanka|moving\_avg
---|---|---|---
0001|    T恤        |1000    |1000 &lt;--(1000)/1
0002|    打孔器    |500    |750  &lt;-- (1000+500)/2
0003|    运动T恤    |4000    |1833.33... &lt;--(1000+500+4000)/3
0004|    菜刀    |3000    |2500 &lt;--(500+4000+3000)/3
0005|    高压锅    |6800    |4600 &lt;--(4000+3000+6800)/3
0006|    叉子    |500    |3433.33.. 依次类推
0007|    擦菜板    |880    |2726.66..  依次类推
0008|    圆珠笔    |100    |493.33..  依次类推

##### 指定框架(统计范围)
我们将上述结果与之前的结果进行比较,可以发现商品编号为&quot;0004&quot;的&quot;菜刀&quot;以下的记录和窗口函数的计算结果并不相同,这是因为我们指定了框架,将统计对象限定为&quot;最靠近的3行&quot;的缘故.
这里我们使用了__ROWS__(行) 和 __PRECEDING__(之前)两个关键字,将框架指定为&quot;截止到之前~行&quot;. 因此&quot;ROWS 2 PRECEDING&quot;也就是将框架指定为&quot;截止到之前2行&quot;,作为统计对象的记录就限定为如下的&quot;最靠近的3行&quot;.也就是说,由于框架是根据当前记录来决定的,所以和固定窗口不同,其范围会随着当前记录的变化而变化.
如果将条件中数字变成&quot;ROWS 5 PRECEDING&quot;,就是&quot;截止到之前5行&quot;(最靠近的6行)的意思.
这样的统计方法称为移动平均(moving average).由于这种方法在希望实时把握&quot;最近状态&quot;时非常方便,所以常常会应用在对股市趋势的实时跟踪当中.
使用关键字__FOLLOWING(之后)__替换__PRECEDING__,就可以指定&quot;截止到之后~行&quot;.

#####将当钱记录的前后行作为统计对象
如果希望将当前记录的前后行作为统计对象时,可以同时使用 ___PRECEDING___ 和 ___FOLLOWING___ 关键字来实现
</code></pre><p>-- 代码8-7 将当前记录的前后航作为统计对象<br>SELECT shohin_id,shohin_mei,hanbai_tanka,<br>    AVG(hanbai_tanka) OVER (ORDER BY shohin_id<br>                        ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS moving_avg<br>FROM shohin;</p>
<pre><code>
执行结果:

shohin\_id|shohin\_mei|hanbai\_tanka|moving\_avg
---|---|---|---
0001|    T恤    |    1000| 750 &lt;-- (1000+500)/2
0002|    打孔器|    500    | 1833.33.. &lt;-- (1000+500+4000)/3
0003|    运动T恤|    4000| 2500 &lt;-- (500+4000+3000)/3
0004|    菜刀|    3000| 4600 &lt;-- (4000+3000+6800)/3
0005|    高压锅|    6800| 3433.33..    依次类推
0006|    叉子|    500    | 2726.66.. 依次类推
0007|    擦菜板|    880    | 493.33.. 依次类推
0008|    圆珠笔|    100    | 490  &lt;-- (880+100)/2

在上述代码中,我们通过指定框架,将&quot;1 PRECEDING(之前一行)&quot;和&quot;1 FOLLOWING(之后一行)&quot;的取件作为统计对象.具体来说就是将__&quot;上一行,自身行,下一行&quot;__3行作为统计对象来进行计算.
如果能熟练掌握框架功能的话,就能称为窗口函数的高手.

#### 两个ORDER BY
最后我们来介绍一下使用窗口函数时,关于结果形式的注意点,那就是记录的排列顺序.由于使用窗口函数时必须要在OVER子句中使用ORDER BY,所以乍一看,可能大家会觉得结果中的记录不会按照ORDER BY所指定的顺序进行排序.
但其实这只是一种错觉.OVER 子句中的ORDER BY只是用来决定窗口函数按照什么样的顺序进行计算的,对结果的排序顺序并没有影响.因此也有可能像下面代码那样得到一个记录的排列顺序比较混乱的结果.有些DBMS也可以按照窗口函数的ORDER BY子句所指定的顺序对结果进行排序,但那也仅仅是个例而已.
</code></pre><p>--代码8-8 无法保证SELECT 语句结果的排列顺序<br>SELECT shohin_mei,shohin_bunrui,hanbai_tanka,<br>RANK() OVER (ORDER BY hanbai_tanka) AS ranking<br>FROM shohin;</p>
<pre><code>
执行结果:
shohin\_me|shohin\_bunrui|hanbai\_tanka|ranking
---|---|---|---
圆珠笔|    办公用品|    100    |    1
叉子|    厨房用具|    500    |    2
打孔器|    办公用品|    500    |    2
擦菜板|    厨房用具|    880    |    4
T恤    |    衣服|        1000|    5
菜刀|    厨房用具|    3000|    6
运动T恤|    衣服|        4000|    7
高压锅|    厨房用具|    6800|    8

那么如何才能让记录切实按照ranking列的顺序排列呢?
答案其实很简单,那就是在SELECT语句的最后,使用ORDER BY子句进行指定(代码清单8-9).这样就能保证SELECT语句结果中记录的排列顺序了,除此之外没有其他办法了.
</code></pre><p>--代码8-9 在语句末位使用ORDER BY子句对结果进行排序<br>SELECT shohin_mei,shohin_bunrui,hanbai_tanka,<br>    RANK() OVER (ORDER BY hanbai_tanka) AS ranking<br>FROM Shohin<br>ORDER BY ranking;</p>
<pre><code>
执行结果:

shohin\_mei|shohin\_bunrui|hanbai\_tanka|ranking
---|---|---|---
圆珠笔|    办公用品|    100    |    1
叉子|    厨房用具|    500    |    2
打孔器|    办公用品|    500    |    2
擦菜板|    厨房用具|    880    |    4
T恤    |    衣服|        1000|    5
菜刀|    厨房用具|    3000|    6
运动T恤|    衣服|    4000    |    7
高压锅|    厨房用具|    6800|    8

我们也许会觉得在一条SELECT语句中使用两次ORDER BY会有些别扭,但是尽管这两个ORDER BY看上去是相同的,但其实它们的功能却完全不同.
- 法则8-5 将聚合函数作为窗口函数使用时,会以当前记录为基准来决定统计对象的记录.

### 8-2 GROUPING运算符
#### 学习重点

- 只使用GROUP BY 子句和聚合函数是无法同时计算出小计,合计值的.如果想要一次得到这两个值可以使用GROUPING运算符.
- 理解GROUPING 运算符中CUBE的关键在与形成&quot;积木搭建出的立方体&quot;的印象.
- 虽然GROUPING 运算符是标准SQL的功能,但是还有些DBMS尚未支持这一功能. 

#### 同时计算出合计值
我们在3-2节中学习过GROUP BY子句和聚合函数的使用方法,当时有人可能会想,是否能够通过GROUP BY子句得到表8-1那样的结果呢?
表8-1

合计|16780 &lt;-- 合计行
---|---
厨房用具| 11180
衣服| 5000
办公用品| 600

虽然这是按照商品种类计算销售单价总额时得到的结果,但问题在于最上面多出一行合计行.使用代码清单8-10中GROUP BY子句的语法无法得到这一行.
</code></pre><p>--代码8-10 使用GROUP BY无法得到合计行<br>SELECT shohin_bunrui,SUM(hanbai_tanka)<br>FROM Shohin<br>GROUP BY shohin_bunrui;</p>
<pre><code>
执行结果:
shohin\_mei|sum
---|---
衣服|5000
办公用品|600
厨房用具|11180

由于GROUP BY子句是用来指定聚合键的场所,所以这里指定的键只能用来进行分割数据,而合计行是不指定聚合键时得到的聚合结果,因此与之下3行通过聚合键得到的结果并不相同.按通常的思路想一次得到这两种结果是不可能的.
如果想要获得那样的结果,过去通常会分别计算出合计行和按照商品种类进行聚合的结果,然后通过__UNION ALL__(虽然也可以用UNION来代替UNION ALL,但由于两条SELECT语句的聚合键不同,一定不会出现重复行,所以可以使用UNION ALL.UNION ALL和UNION不同之处在于它不会对结果进行排序,因此比UNION的性能更好)
</code></pre><p>--代码 8-11 分别计算出合计行和聚合结果再通过UNION ALL进行连接<br>SELECT &#39;合计&#39; AS shohin_bunrui,SUM(hanbai_tanka)<br>FROM Shohin<br>UNION ALL<br>SELECT shohin_bunrui,SUM(hanbai_tanka)<br>FROM shohin<br>GROUP BY shohin_bunrui; </p>
<pre><code>
执行结果:
shohin\_bunrui|sum
---|---
衣服|5000
办公用品|600
厨房用具|11180

这样一来为了得到想要的结果,需要执行两次几乎相同的SELECT语句,再将其结果进行连接.不但看上去十分繁琐,DBMS内部处理成本也非常高.难道没有更合适的实现方法了吗?

#### ROLLUP--&gt;同时计算出合计值和小计值
为了满足用户的需求,标准SQL引入了GROUPING运算符.我们将在本节中着重介绍.使用该运算符就能通过非常简单的SQL,得到之前那样聚合单位不同的聚合结果了.
GROUPING 运算符包含一下3种:

- ROLLUP
- CUBE
- GROUPING SETS

##### ROLLUP
我们先从ROLLUP 开始学习,使用ROLLUP就可以通过非常简单的SELECT 语句同时计算出合计行了(代码清单8-12)
</code></pre><p>--代码清单8-12 使用ROLLUP同时计算出合计行和小计<br>SELECT shohin_bunrui,SUM(hanbai_tanka) AS sum_tanka<br>FROM Shohin<br>GROUP BY ROLLUP(shohin_bunrui);</p>
<pre><code>
执行结果:

shohin\_bunrui|sum\_tanka
---|---
null|16780
厨房用具|11180
衣服|5000
办公用品|600

在语法上,就是将GROUP BY 子句中的聚合键清单像__ROLLUP(&lt;列1&gt;,&lt;列2&gt;,...)__这样进行使用.该运算符的作用,一言以蔽之,就是&quot;一次计算出不同聚合键的组合结果&quot;.例如,在本例中就是一次计算出了如下2组组合的聚合结果.

1. GROUP BY ()
2. GROUP BY (shohin_bunrui)

1中的GROUP BY ()并没有聚合键,也就相当于没有GROUP BY 子句(这时候会得到全部数据的合计行的记录).该合计行记录称为__超级分组记录(super group row)__.虽然名字听上去很炫,但我们还是需要把它当做未使用GROUP BY的合计行来使用理解.
超级分组记录的shohin_bunrui列的键值(对DBMS来说)并不明确,因此会默认使用NULL,之后我们会学习在此处插入恰当字符串的方法.
- 法则8-6 超级分组记录默认使用NULL 作为聚合键.

##### 将&quot;登记日期&quot;添加到聚合键当中
仅仅通过刚才一个例子,我们的印象可能不够深刻,下面我们再添加一个聚合键&quot;登记日期(torokubi)&quot;试试看吧.首先从不使用ROLLUP开始(代码清单8-13)
</code></pre><p>--代码清单8-13 在GROUP BY 中添加登记日期(不使用ROLLUP)<br>SELECT shohin_bunrui,torokubi,SUM(hanbai_tanka) AS sum_tanka<br>FROM shohin<br>GROUP BY shohin_bunrui,torokubi;</p>
<pre><code>
执行结果如下:

shohin\_bunrui|torokubi|sum\_tanka
---|---|---
厨房用具|    2009-01-15|    6800
办公用品|    2009-11-11|    100
衣服|    NULL        |    4000
办公用品|    2009-09-11|    500
厨房用具|    2008-04-28|    880
厨房用具|    2009-09-20|    3500
衣服|    2009-09-20    |    1000

在上述GROUP BY子句中使用ROLLUP之后,结果会发生什么变化吗?
</code></pre><p>--代码8-14: 在代码8-13 GROUP BY 中添加&quot;登记日期(使用ROLLUP)<br>SELECT shohin_bunrui,torokubi,SUM(hanbai_tanka) AS sum_tanka<br>FROM Shohin<br>GROUP BY ROLLUP (shohin_bunrui,torokubi);</p>
<pre><code>
执行结果:

shohin\_bunrui|torokubi|sum_tanka
---|---|---
办公用品|    2009-09-11|    500
办公用品|    2009-11-11|    100
办公用品|null        |    600
厨房用具|    2008-04-28|    880
厨房用具|    2009-01-15|    6800
厨房用具|    2009-09-20|    3500
厨房用具|    null    |    11180
衣服|    2009-09-20    |    1000
衣服|    null        |    4000
衣服|        null    |    5000
null|null|            |    16780

将上述两个结果进行比较后我们发现,使用ROLLUP时多出了最下面的合计行,以及3条不同商品种类的小计行(也就是未使用登记日期作为聚合键的记录).这4行就是我们所说的超级分组记录.也就是说该SELECT语句的结果相当于使用UNION对如下3种模式聚合级的不同结果进行链接.
1. GROUP BY ()
2. GROUP BY (Shohin_bunrui)
3. GROUP BY (shohin_bunrui, torokubi)

ROLLUP是&quot;卷起的意思&quot;,比如卷起百叶窗、窗帘等等,其名称也形象地说明了该操作能够得到像从小计到合计这样,从最小的聚合级开始,聚合单位逐渐扩大的结果.
- 法则8-7 ROLLUP可以同时计算出合计和小计,是非常方便的工具

#### GROUPING函数--&gt;让NULL更加容易分辨
可能有人会注意到,之前使用ROLLUP所得到的结果(代码8-14的执行结果)有些蹊跷.问题就出在&quot;衣服&quot;的分组之中.有两条记录的torokubi列为NULL,但其原因却并不相同.
sum_tanka为4000元的记录,由于商品表中运动T恤的注册日期为NULL,所以就把NULL作为聚合键了,在这之前的实例中我们也曾见到过.
相反,sum_tanka为5000元的记录,毫无疑问就是超级分组记录NULL了(细目为1000元+4000元=5000元).但由于两者看上去都是&quot;NULL&quot;,实在是难以分辨.
</code></pre><h2>shohin_bunrui    torokubi    sum_tanka</h2>
<hr>
<p>衣服                           5000 &lt;--由于是超级分组记录的缘故,登记日期为NULL<br>衣服            2009-09-20     1000<br>衣服                           1000 &lt;--仅仅因为登记日期为NULL</p>
<pre><code>
为了避免混淆,SQL提供了一个用来判断超级分组记录的NULL的特定函数--&gt;GROUPING函数.该函数在其参数列的值为超级分组记录所产生的NULL时返回1,其它情况返回0(代码清单8-15).
</code></pre><p>--代码8-15 使用GROUPING函数来判断NULL<br>SELECT GROUPING(shohin_bunrui) AS shohin_bunrui,<br>    GROUPING(torokubi) AS torokubi,SUM(hanbai_tanka) AS sum_tanka_ihuku<br>FROM Shohin<br>GROUP BY ROLLUP(shohin_bunrui,torokubi);<br>执行结果:<br>shohin_bunrui    torokubi    sum_tanka<br>    0            0              500<br>    0            0              100<br>    0            1              600<br>    0            0              880<br>    0            0              6800<br>    0            0              3500<br>    0            1              11180<br>    0            0              1000 &lt;-- 原始数据为NULL时返回0<br>    0            0              4000<br>    0            1              5000 &lt;-- 碰到超级分组记录中的NULL时会返回1<br>    1            1              16780 </p>
<pre><code>
这样就能判断出是超级分组记录中的NULL还是原始数据本身为NULL了.使用GROUPING函数还能在超级分组记录的键值中插入字符串.也就是说,当GROUPING函数返回值为1时,指定&quot;合计&quot;或者&quot;小计&quot;等字符串,其他情况返回通常的列的值(代码清单8-16).
</code></pre><p>--代码清单8-16 在超级分组记录的键值中插入恰当的字符串<br>SELECT CASE WHEN GROUPING(Shohin_bunrui) = 1<br>            THEN &#39;商品总类 合计&#39;<br>            ELSE shohin_bunrui END AS shohin_bunrui,<br>        CASE WHEN GROUPING(torokubi) = 1<br>        THEN &#39;登记日期 合计&#39;<br>        ELSE CAST(torokubi AS VARCHAR(16)) END AS torokubi,<br>        SUM(hanbai_tanka) AS sum_tanka_ihuku<br>    FROM Shohin<br>GROUP BY ROLLUP(shohin_bunrui,torokubi);<br>执行结果:</p>
<h2>shohin_bunrui     torokubi    sum_tanka</h2>
<hr>
<p>办公用品            2009-09-11        500<br>办公用品            2009-11-11        100<br>办公用品            登记日期 合计        600<br>厨房用具            2008-04-28        880<br>厨房用具            2009-01-15        6800<br>厨房用具            2009-09-20        3500<br>厨房用具            登记日期 合计        11180<br>衣服            2009-09-20        1000<br>衣服                            4000 &lt;-- 原始数据中的NULL保持不变<br>衣服            登记日期 合计        5000 &lt;-- 将超级分组记录中的NULL替换为&quot;登记日期 合计&quot;<br>商品总类 合计        登记日期 合计        16780 </p>
<pre><code>
在实际业务中,需要获取包含合计或者小计的统计结果(这种情况是最多的)时,就可以使用ROLLUP和GROUPING函数来实现了.
</code></pre><p>CAST(torokubi AS VARCHAR(16))</p>
<pre><code>
那为什么还要将SELECT子句中的torokubi列转换为CAST(torokubi AS VARCHAR(16))形式的字符串呢?这是为了满足CASE表达式所有分支的返回值必须一致的规定.如果不这样的话,那么各个分支会分别返回日期类型和字符串类型的值,执行时就会发生语法错误.
- 法则8-8 使用GROUPING 函数能够简单地分析出原始数据中的NULL和超级分组记录中的NULL.

#### CUBE--&gt;用数据来搭积木
ROLLUP之后我们来学习另一个常用的GROUPING运算符--&gt;CUBE.CUBE是&quot;立方体&quot;的意思,这个奇怪的名字和ROLLUP一样,都能形象地说明该函数的动作.究竟是什么样的动作呢,还是让我们通过一个例子来看一看吧.
CUBE 的语法和ROLLUP相同,只要将ROLLUP替换为CUBE就可以了.下面我们就把代码清单8-16中的SELECT语句替换为CUBE试试看吧(代码清单8-17).
</code></pre><p>--代码清单8-17 使用CUBE取得全部组合的结果<br>SELECT CASE WHEN GROUPING(Shohin_bunrui) = 1<br>            THEN &#39;商品总类 合计&#39;<br>            ELSE shohin_bunrui END AS shohin_bunrui,<br>        CASE WHEN GROUPING(torokubi) = 1<br>        THEN &#39;登记日期 合计&#39;<br>        ELSE CAST(torokubi AS VARCHAR(16)) END AS torokubi,<br>        SUM(hanbai_tanka) AS sum_tanka_ihuku<br>    FROM Shohin<br>GROUP BY CUBE(shohin_bunrui,torokubi);<br>执行结果:</p>
<h2>shohin_bunrui     torokubi    sum_tanka</h2>
<hr>
<p>办公用品            2009-09-11      500<br>办公用品            2009-11-11      100<br>办公用品            登记日期 合计      600<br>厨房用具            2008-04-28      880<br>厨房用具            2009-01-15      6800<br>厨房用具            2009-09-20      3500<br>厨房用具            登记日期 合计      11180<br>衣服            2009-09-20      1000<br>衣服                          4000<br>衣服            登记日期 合计      5000<br>商品种类 合计        登记日期 合计      16780<br>商品种类 合计        2008-04-28      880  &lt;--追加<br>商品种类 合计        2009-01-15      6800 &lt;--追加<br>商品种类 合计        2009-09-11      500  &lt;--追加<br>商品种类 合计        2009-09-20      4500 &lt;--追加<br>商品种类 合计        2009-11-11      100  &lt;--追加<br>商品种类 合计                      4000 &lt;--追加 </p>
<pre><code>
与ROLLUP的结果相比,CUBE的结果中多出了几行记录.我们看一下就明白了多出来的记录就是只把torokubi作为聚合键所得到的聚合结果:
1. GROUP BY
2. GROUP BY(shohin_bunrui)
3. GROUP BY(torokubi) &lt;--新添加的组合
4. GROUP BY(shohin_bunrui,torokubi)

所谓CUBE,就是将GROUP BY子句中的聚合键的&quot;所有可能组合&quot;的聚合击中到一个结果中的功能.因此,组合的个数就是2的n次方(n是聚合键的个数),本例中聚合键有2个,所以2的2次方是4,如果再添加1个变成3个聚合键的话,就是2的3次方为8.__注:使用ROLLUP时组合的个数是n+1.随着组合个数的增加,结果的行数也会增加,因此如果使用CUBE时,不加以注意的话,往往会得到意想不到的巨大结果.顺带说一下,ROLLUP的结果一定是包含在CUBE结果之中.__
到这里,我们就会感到很奇怪,究竟CUBE运算符和立方体有什么关系呢/.
众所周知,立方体由长、宽、高三个轴组成.对于CUBE来说,一个聚合键就相当于其中一个轴而结果就是将数据想积木那样堆积起来,如下图
![](https://img.alicdn.com/imgextra/i2/3044451280/TB2oqiReceK.eBjSszgXXczFpXa_!!3044451280.jpg)
由于本例中只有商品种类(shohin_bunrui)和登记日期(torokubi)两个轴,所以我们看到的其实是个正方形,请大家把他看做缺了一个轴的立方体.通过CUBE当然也可以指定4个以上的轴,但由于那已经属于4维空间的范畴了,无法用图形来表示.
- 法则 8-9 可以把CUBE理解为将使用聚合键进行切割的模块堆积成一个立方体.

#### GROUPING SETS--&gt; 去的期望的积木
最后要学习的GROUPING运算符是GROUPING SETS.该运算符可以用从ROLLUP或者CUBE的结果中取出部分记录.
例如,之前的CUBE的结果就是根据聚合键的所有可能组合计算而来的.如果希望从中选取出&quot;商品种类&quot;和&quot;登记日期&quot;各自作为聚合键的结果,反之,不想得到&quot;合计记录和使用2个聚合键的记录&quot;时,可以使用GROUPING SETS(代码清单8-18)
</code></pre><p>--代码8-18 使用GROUPING SETS取得部分组合结果<br>SELECT CASE WHEN GROUPING(shohin_bunrui) = 1<br>            THEN &#39;商品种类 合计&#39;<br>            ELSE shohin_bunrui END AS shohin_bunrui,<br>       CASE WHEN GROUPING(torokubi) = 1<br>            THEN &#39;登记日期 合计&#39;<br>            ELSE CAST(torokubi AS VARCHAR(16)) END AS torokubi,<br>       SUM(hanbai_tanka) AS sum_tanka<br>  FROM Shohin<br> GROUP BY GROUPING SETS (shohin_bunrui, torokubi);<br>执行结果:</p>
<h2>shohin_bunrui     torokubi    sum_tanka</h2>
<hr>
<p>办公用品            登记日期 合计      600<br>厨房用具            登记日期 合计      11180<br>衣服            登记日期 合计      5000<br>商品种类 合计        2008-04-28      880<br>商品种类 合计        2009-01-15      6800<br>商品种类 合计        2009-09-11      500<br>商品种类 合计        2009-09-20      4500<br>商品种类 合计        2009-11-11      100<br>商品种类 合计                      4000<br>```<br>上述结果中也没有全体的合计行(16780元).与ROLLUP或者CUBE能够得到规定的(业务上称为&quot;固定的&quot;)结果相对,GROUPING SETS用于从中取出个别条件对应的不固定的结果.然而,由于期望获得不固定结果的情况少之又少,所以与ROLLUP或者CUBE比起来,使用GROUPING SETS的机会也就很少了.</p>
</div>
<script>
function MathJaxDone(){
	window.status='ready';
}
window.status='ready';
hljs.initHighlightingOnLoad();
var tocs = document.getElementsByTagName('toc');
var tocs=$("*[name='toc']");
if( tocs.length ){
	var toc=generated_toc.generate('content');
	tocs.each(function(){
		$(this).html( toc );
	});
}
</script>
</body>
</html>